/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s6[32] = {13, 13, 0, 0, 0, 0, 4, 8, 12, 16, 16, 16, 16, 16, 16, 16, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s7[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s8[4] = {0, 1, 0, 0};
static const casadi_int casadi_s9[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* atmos_ff_cost_y_e_hess:(i0[13],i1[0],i2[0],i3[10],i4[],i5[25])->(o0[13x13,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr;
  casadi_real *w0=w+1, *w1=w+17, *w2=w+30, *w3=w+34, *w4=w+38, w5, w6, w7, w8, *w9=w+52, *w10=w+56;
  /* #0: @0 = zeros(13x13,16nz) */
  casadi_clear(w0, 16);
  /* #1: @1 = input[5][0] */
  casadi_copy(arg[5], 13, w1);
  /* #2: @2 = @1[3:7] */
  for (rr=w2, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #3: @3 = @2' */
  casadi_copy(w2, 4, w3);
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 10, w4);
  /* #5: {NULL, @5, NULL, NULL} = vertsplit(@4) */
  w5 = w4[3];
  /* #6: @6 = 0 */
  w6 = 0.;
  /* #7: @4 = ones(13x1,10nz) */
  casadi_fill(w4, 10, 1.);
  /* #8: {NULL, @7, NULL, NULL} = vertsplit(@4) */
  w7 = w4[3];
  /* #9: @7 = @7' */
  /* #10: @8 = mac(@7,@2,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes((&w7), casadi_s2, w2, casadi_s1, (&w8), casadi_s0, w, 0);
  /* #11: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #12: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #13: @9 = (@3*@8) */
  for (i=0, rr=w9, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #14: @9 = @9' */
  /* #15: (@0[:16:4] = @9) */
  for (rr=w0+0, ss=w9; rr!=w0+16; rr+=4) *rr = *ss++;
  /* #16: @8 = ones(13x1,1nz) */
  w8 = 1.;
  /* #17: {NULL, @7, NULL, NULL} = vertsplit(@8) */
  w7 = w8;
  /* #18: @7 = @7' */
  /* #19: @8 = mac(@7,@2,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes((&w7), casadi_s3, w2, casadi_s1, (&w8), casadi_s0, w, 0);
  /* #20: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #21: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #22: @9 = (@3*@8) */
  for (i=0, rr=w9, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #23: @9 = @9' */
  /* #24: (@0[1:17:4] = @9) */
  for (rr=w0+1, ss=w9; rr!=w0+17; rr+=4) *rr = *ss++;
  /* #25: @8 = ones(13x1,1nz) */
  w8 = 1.;
  /* #26: {NULL, @7, NULL, NULL} = vertsplit(@8) */
  w7 = w8;
  /* #27: @7 = @7' */
  /* #28: @8 = mac(@7,@2,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes((&w7), casadi_s4, w2, casadi_s1, (&w8), casadi_s0, w, 0);
  /* #29: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #30: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #31: @9 = (@3*@8) */
  for (i=0, rr=w9, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #32: @9 = @9' */
  /* #33: (@0[2:18:4] = @9) */
  for (rr=w0+2, ss=w9; rr!=w0+18; rr+=4) *rr = *ss++;
  /* #34: @8 = ones(13x1,1nz) */
  w8 = 1.;
  /* #35: {NULL, @7, NULL, NULL} = vertsplit(@8) */
  w7 = w8;
  /* #36: @7 = @7' */
  /* #37: @6 = mac(@7,@2,@6) */
  casadi_mtimes((&w7), casadi_s5, w2, casadi_s1, (&w6), casadi_s0, w, 0);
  /* #38: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #39: @5 = (@5*@6) */
  w5 *= w6;
  /* #40: @3 = (@3*@5) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) *= w5;
  /* #41: @3 = @3' */
  /* #42: (@0[3:19:4] = @3) */
  for (rr=w0+3, ss=w3; rr!=w0+19; rr+=4) *rr = *ss++;
  /* #43: @10 = @0' */
  casadi_trans(w0,casadi_s6, w10, casadi_s6, iw);
  /* #44: output[0][0] = @10 */
  casadi_copy(w10, 16, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    case 4: return casadi_s10;
    case 5: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 72;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 72*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
