/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* atmos_ff_cost_y_e_fun:(i0[13],i1[0],i2[0],i3[],i4[25])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+16, *w3=w+19, w4, *w5=w+24, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #6: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #7: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #8: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #9: @5 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w5);
  /* #10: @6 = ||@5||_F */
  w6 = sqrt(casadi_dot(4, w5, w5));
  /* #11: @5 = (@5/@6) */
  for (i=0, rr=w5; i<4; ++i) (*rr++) /= w6;
  /* #12: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #13: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #14: @8 = @3[1] */
  for (rr=(&w8), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #15: @9 = @5[1] */
  for (rr=(&w9), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #16: @10 = (@8*@9) */
  w10  = (w8*w9);
  /* #17: @7 = (@7+@10) */
  w7 += w10;
  /* #18: @10 = @3[2] */
  for (rr=(&w10), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #19: @11 = @5[2] */
  for (rr=(&w11), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #20: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #21: @7 = (@7+@12) */
  w7 += w12;
  /* #22: @12 = @3[3] */
  for (rr=(&w12), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #23: @13 = @5[3] */
  for (rr=(&w13), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #24: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #25: @7 = (@7+@14) */
  w7 += w14;
  /* #26: @14 = (@8*@6) */
  w14  = (w8*w6);
  /* #27: @15 = (@4*@9) */
  w15  = (w4*w9);
  /* #28: @14 = (@14-@15) */
  w14 -= w15;
  /* #29: @15 = (@10*@13) */
  w15  = (w10*w13);
  /* #30: @14 = (@14-@15) */
  w14 -= w15;
  /* #31: @15 = (@12*@11) */
  w15  = (w12*w11);
  /* #32: @14 = (@14+@15) */
  w14 += w15;
  /* #33: @15 = (@8*@13) */
  w15  = (w8*w13);
  /* #34: @16 = (@4*@11) */
  w16  = (w4*w11);
  /* #35: @15 = (@15-@16) */
  w15 -= w16;
  /* #36: @16 = (@10*@6) */
  w16  = (w10*w6);
  /* #37: @15 = (@15+@16) */
  w15 += w16;
  /* #38: @16 = (@12*@9) */
  w16  = (w12*w9);
  /* #39: @15 = (@15-@16) */
  w15 -= w16;
  /* #40: @8 = (@8*@11) */
  w8 *= w11;
  /* #41: @8 = (-@8) */
  w8 = (- w8 );
  /* #42: @4 = (@4*@13) */
  w4 *= w13;
  /* #43: @8 = (@8-@4) */
  w8 -= w4;
  /* #44: @10 = (@10*@9) */
  w10 *= w9;
  /* #45: @8 = (@8+@10) */
  w8 += w10;
  /* #46: @12 = (@12*@6) */
  w12 *= w6;
  /* #47: @8 = (@8+@12) */
  w8 += w12;
  /* #48: @5 = vertcat(@7, @14, @15, @8) */
  rr=w5;
  *rr++ = w7;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w8;
  /* #49: @7 = sign(@7) */
  w7 = casadi_sign( w7 );
  /* #50: @5 = (@5*@7) */
  for (i=0, rr=w5; i<4; ++i) (*rr++) *= w7;
  /* #51: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 4, res[0]+3);
  /* #52: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #53: @2 = @1[7:10] */
  for (rr=w2, ss=w1+7; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #54: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #55: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #56: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #57: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #58: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #59: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_e_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_cost_y_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 39*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
