/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s5[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* atmos_ff_cost_y_0_fun:(i0[13],i1[6],i2[0],i3[],i4[19])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+1, *w1=w+4, *w2=w+17, w3, w4, *w5=w+22, *w6=w+26, w7, *w8=w+31, *w9=w+37;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #6: @2 = @1[3:6] */
  for (rr=w2, ss=w1+3; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #7: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #8: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #9: @3 = 0 */
  w3 = 0.;
  /* #10: @4 = 1 */
  w4 = 1.;
  /* #11: @5 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w5);
  /* #12: @5 = @5' */
  /* #13: @6 = @1[6:10] */
  for (rr=w6, ss=w1+6; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #14: @7 = mac(@5,@6,@3) */
  casadi_copy((&w3), 1, (&w7));
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #15: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #16: @4 = fmin(@4,@7) */
  w4  = casadi_fmin(w4,w7);
  /* #17: @3 = fmax(@3,@4) */
  w3  = casadi_fmax(w3,w4);
  /* #18: output[0][2] = @3 */
  if (res[0]) res[0][6] = w3;
  /* #19: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #20: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #21: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #23: @8 = input[1][0] */
  casadi_copy(arg[1], 6, w8);
  /* #24: @9 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+13 : 0, 6, w9);
  /* #25: @8 = (@8-@9) */
  for (i=0, rr=w8, cs=w9; i<6; ++i) (*rr++) -= (*cs++);
  /* #26: output[0][4] = @8 */
  if (res[0]) casadi_copy(w8, 6, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 43;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 43*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
