/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s5[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s6[38] = {19, 16, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {16, 0, 0};

/* atmos_ff_cost_y_0_fun_jac_ut_xt:(i0[13],i1[6],i2[0],i3[],i4[19])->(o0[16],o1[19x16,19nz],o2[16x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+1, *w1=w+4, *w2=w+17, w3, w4, *w5=w+22, *w6=w+26, w7, w8, w9, w10, *w11=w+34, *w12=w+40, *w13=w+46, *w14=w+65, *w15=w+81, w16;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #6: @2 = @1[3:6] */
  for (rr=w2, ss=w1+3; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #7: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #8: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #9: @3 = 0 */
  w3 = 0.;
  /* #10: @4 = 1 */
  w4 = 1.;
  /* #11: @5 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w5);
  /* #12: @5 = @5' */
  /* #13: @6 = @1[6:10] */
  for (rr=w6, ss=w1+6; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #14: @7 = mac(@5,@6,@3) */
  casadi_copy((&w3), 1, (&w7));
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #15: @8 = fabs(@7) */
  w8 = casadi_fabs( w7 );
  /* #16: @9 = fmin(@4,@8) */
  w9  = casadi_fmin(w4,w8);
  /* #17: @10 = fmax(@3,@9) */
  w10  = casadi_fmax(w3,w9);
  /* #18: output[0][2] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #19: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #20: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #21: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #23: @11 = input[1][0] */
  casadi_copy(arg[1], 6, w11);
  /* #24: @12 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+13 : 0, 6, w12);
  /* #25: @11 = (@11-@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) -= (*cs++);
  /* #26: output[0][4] = @11 */
  if (res[0]) casadi_copy(w11, 6, res[0]+10);
  /* #27: @13 = zeros(19x16,19nz) */
  casadi_clear(w13, 19);
  /* #28: @14 = ones(16x1) */
  casadi_fill(w14, 16, 1.);
  /* #29: {@0, @2, @10, @15, @11} = vertsplit(@14) */
  casadi_copy(w14, 3, w0);
  casadi_copy(w14+3, 3, w2);
  w10 = w14[6];
  casadi_copy(w14+7, 3, w15);
  casadi_copy(w14+10, 6, w11);
  /* #30: @16 = @0[0] */
  for (rr=(&w16), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #31: (@13[0] = @16) */
  for (rr=w13+0, ss=(&w16); rr!=w13+1; rr+=1) *rr = *ss++;
  /* #32: @16 = @0[1] */
  for (rr=(&w16), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #33: (@13[1] = @16) */
  for (rr=w13+1, ss=(&w16); rr!=w13+2; rr+=1) *rr = *ss++;
  /* #34: @16 = @0[2] */
  for (rr=(&w16), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #35: (@13[2] = @16) */
  for (rr=w13+2, ss=(&w16); rr!=w13+3; rr+=1) *rr = *ss++;
  /* #36: @16 = @2[0] */
  for (rr=(&w16), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #37: (@13[3] = @16) */
  for (rr=w13+3, ss=(&w16); rr!=w13+4; rr+=1) *rr = *ss++;
  /* #38: @16 = @2[1] */
  for (rr=(&w16), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #39: (@13[4] = @16) */
  for (rr=w13+4, ss=(&w16); rr!=w13+5; rr+=1) *rr = *ss++;
  /* #40: @16 = @2[2] */
  for (rr=(&w16), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #41: (@13[5] = @16) */
  for (rr=w13+5, ss=(&w16); rr!=w13+6; rr+=1) *rr = *ss++;
  /* #42: @7 = sign(@7) */
  w7 = casadi_sign( w7 );
  /* #43: @16 = (@8<=@4) */
  w16  = (w8<=w4);
  /* #44: @4 = (@4<=@8) */
  w4  = (w4<=w8);
  /* #45: @4 = (@4+@16) */
  w4 += w16;
  /* #46: @16 = (@16/@4) */
  w16 /= w4;
  /* #47: @4 = (@3<=@9) */
  w4  = (w3<=w9);
  /* #48: @9 = (@9<=@3) */
  w9  = (w9<=w3);
  /* #49: @9 = (@9+@4) */
  w9 += w4;
  /* #50: @4 = (@4/@9) */
  w4 /= w9;
  /* #51: @4 = (@4*@10) */
  w4 *= w10;
  /* #52: @16 = (@16*@4) */
  w16 *= w4;
  /* #53: @7 = (@7*@16) */
  w7 *= w16;
  /* #54: @6 = @6' */
  /* #55: @6 = (@7*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #56: @6 = @6' */
  /* #57: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #58: (@13[6] = @7) */
  for (rr=w13+6, ss=(&w7); rr!=w13+7; rr+=1) *rr = *ss++;
  /* #59: @7 = @6[1] */
  for (rr=(&w7), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #60: (@13[7] = @7) */
  for (rr=w13+7, ss=(&w7); rr!=w13+8; rr+=1) *rr = *ss++;
  /* #61: @7 = @6[2] */
  for (rr=(&w7), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #62: (@13[8] = @7) */
  for (rr=w13+8, ss=(&w7); rr!=w13+9; rr+=1) *rr = *ss++;
  /* #63: @7 = @6[3] */
  for (rr=(&w7), ss=w6+3; ss!=w6+4; ss+=1) *rr++ = *ss;
  /* #64: (@13[9] = @7) */
  for (rr=w13+9, ss=(&w7); rr!=w13+10; rr+=1) *rr = *ss++;
  /* #65: @7 = @15[0] */
  for (rr=(&w7), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #66: (@13[10] = @7) */
  for (rr=w13+10, ss=(&w7); rr!=w13+11; rr+=1) *rr = *ss++;
  /* #67: @7 = @15[1] */
  for (rr=(&w7), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #68: (@13[11] = @7) */
  for (rr=w13+11, ss=(&w7); rr!=w13+12; rr+=1) *rr = *ss++;
  /* #69: @7 = @15[2] */
  for (rr=(&w7), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #70: (@13[12] = @7) */
  for (rr=w13+12, ss=(&w7); rr!=w13+13; rr+=1) *rr = *ss++;
  /* #71: @7 = @11[0] */
  for (rr=(&w7), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #72: (@13[13] = @7) */
  for (rr=w13+13, ss=(&w7); rr!=w13+14; rr+=1) *rr = *ss++;
  /* #73: @7 = @11[1] */
  for (rr=(&w7), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #74: (@13[14] = @7) */
  for (rr=w13+14, ss=(&w7); rr!=w13+15; rr+=1) *rr = *ss++;
  /* #75: @7 = @11[2] */
  for (rr=(&w7), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #76: (@13[15] = @7) */
  for (rr=w13+15, ss=(&w7); rr!=w13+16; rr+=1) *rr = *ss++;
  /* #77: @7 = @11[3] */
  for (rr=(&w7), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #78: (@13[16] = @7) */
  for (rr=w13+16, ss=(&w7); rr!=w13+17; rr+=1) *rr = *ss++;
  /* #79: @7 = @11[4] */
  for (rr=(&w7), ss=w11+4; ss!=w11+5; ss+=1) *rr++ = *ss;
  /* #80: (@13[17] = @7) */
  for (rr=w13+17, ss=(&w7); rr!=w13+18; rr+=1) *rr = *ss++;
  /* #81: @7 = @11[5] */
  for (rr=(&w7), ss=w11+5; ss!=w11+6; ss+=1) *rr++ = *ss;
  /* #82: (@13[18] = @7) */
  for (rr=w13+18, ss=(&w7); rr!=w13+19; rr+=1) *rr = *ss++;
  /* #83: output[1][0] = @13 */
  casadi_copy(w13, 19, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 85;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 85*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
