/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s3[20] = {19, 1, 0, 16, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};

static const casadi_real casadi_c0[9] = {3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01};
static const casadi_real casadi_c1[9] = {3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00};

/* atmos_ff_expl_vde_adj:(i0[13],i1[13],i2[6],i3[25])->(o0[19x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+7, w2, w3, *w4=w+13, w5, *w6=w+23, *w7=w+36, *w8=w+39, *w9=w+43, *w10=w+46, *w11=w+49, w12, w13, *w14=w+57, *w15=w+60, *w16=w+69, *w17=w+78, *w18=w+81, w19, w20, w21, w22, w23, w24, w25, w26, *w27=w+92, *w28=w+95, *w29=w+104, *w30=w+113, w31;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = (2.*@2) */
  w3 = (2.* w2 );
  /* #4: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #5: @5 = 0.0595238 */
  w5 = 5.9523809523809521e-02;
  /* #6: @6 = input[1][0] */
  casadi_copy(arg[1], 13, w6);
  /* #7: {@7, @8, @9, @10} = vertsplit(@6) */
  casadi_copy(w6, 3, w7);
  casadi_copy(w6+3, 4, w8);
  casadi_copy(w6+7, 3, w9);
  casadi_copy(w6+10, 3, w10);
  /* #8: @9 = (@5*@9) */
  for (i=0, rr=w9, cs=w9; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #9: @11 = input[2][0] */
  casadi_copy(arg[2], 6, w11);
  /* #10: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #11: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #12: @13 = @11[2] */
  for (rr=(&w13), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #13: @14 = vertcat(@5, @12, @13) */
  rr=w14;
  *rr++ = w5;
  *rr++ = w12;
  *rr++ = w13;
  /* #14: @14 = @14' */
  /* #15: @15 = mac(@9,@14,@4) */
  casadi_copy(w4, 9, w15);
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w14+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #16: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #17: {@14, @17, @18} = horzsplit(@16) */
  casadi_copy(w16, 3, w14);
  casadi_copy(w16+3, 3, w17);
  casadi_copy(w16+6, 3, w18);
  /* #18: @18 = @18' */
  /* #19: {@5, @12, @13} = horzsplit(@18) */
  w5 = w18[0];
  w12 = w18[1];
  w13 = w18[2];
  /* #20: @13 = (-@13) */
  w13 = (- w13 );
  /* #21: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #22: @19 = (@3*@13) */
  w19  = (w3*w13);
  /* #23: (@0[2] += @19) */
  for (rr=w0+2, ss=(&w19); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #24: @19 = @1[1] */
  for (rr=(&w19), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #25: @20 = (2.*@19) */
  w20 = (2.* w19 );
  /* #26: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #27: (@0[1] += @13) */
  for (rr=w0+1, ss=(&w13); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #28: @13 = @1[0] */
  for (rr=(&w13), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #29: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #30: @21 = (@13*@12) */
  w21  = (w13*w12);
  /* #31: (@0[1] += @21) */
  for (rr=w0+1, ss=(&w21); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #32: @21 = (@19*@12) */
  w21  = (w19*w12);
  /* #33: (@0[0] += @21) */
  for (rr=w0+0, ss=(&w21); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #34: @21 = (@2*@12) */
  w21  = (w2*w12);
  /* #35: (@0[3] += @21) */
  for (rr=w0+3, ss=(&w21); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #36: @21 = @1[3] */
  for (rr=(&w21), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #37: @12 = (@21*@12) */
  w12  = (w21*w12);
  /* #38: (@0[2] += @12) */
  for (rr=w0+2, ss=(&w12); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #39: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #40: @12 = (@13*@5) */
  w12  = (w13*w5);
  /* #41: @12 = (-@12) */
  w12 = (- w12 );
  /* #42: (@0[2] += @12) */
  for (rr=w0+2, ss=(&w12); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #43: @12 = (@2*@5) */
  w12  = (w2*w5);
  /* #44: @12 = (-@12) */
  w12 = (- w12 );
  /* #45: (@0[0] += @12) */
  for (rr=w0+0, ss=(&w12); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #46: @12 = (@19*@5) */
  w12  = (w19*w5);
  /* #47: (@0[3] += @12) */
  for (rr=w0+3, ss=(&w12); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #48: @5 = (@21*@5) */
  w5  = (w21*w5);
  /* #49: (@0[1] += @5) */
  for (rr=w0+1, ss=(&w5); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #50: @17 = @17' */
  /* #51: {@5, @12, @22} = horzsplit(@17) */
  w5 = w17[0];
  w12 = w17[1];
  w22 = w17[2];
  /* #52: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #53: @23 = (@13*@22) */
  w23  = (w13*w22);
  /* #54: @23 = (-@23) */
  w23 = (- w23 );
  /* #55: (@0[1] += @23) */
  for (rr=w0+1, ss=(&w23); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #56: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #57: @23 = (-@23) */
  w23 = (- w23 );
  /* #58: (@0[0] += @23) */
  for (rr=w0+0, ss=(&w23); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #59: @23 = (@2*@22) */
  w23  = (w2*w22);
  /* #60: (@0[3] += @23) */
  for (rr=w0+3, ss=(&w23); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #61: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #62: (@0[2] += @22) */
  for (rr=w0+2, ss=(&w22); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #63: @22 = (2.*@21) */
  w22 = (2.* w21 );
  /* #64: @12 = (-@12) */
  w12 = (- w12 );
  /* #65: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #66: @23 = (@22*@12) */
  w23  = (w22*w12);
  /* #67: (@0[3] += @23) */
  for (rr=w0+3, ss=(&w23); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #68: @20 = (@20*@12) */
  w20 *= w12;
  /* #69: (@0[1] += @20) */
  for (rr=w0+1, ss=(&w20); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #70: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #71: @20 = (@13*@5) */
  w20  = (w13*w5);
  /* #72: (@0[3] += @20) */
  for (rr=w0+3, ss=(&w20); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #73: @20 = (@21*@5) */
  w20  = (w21*w5);
  /* #74: (@0[0] += @20) */
  for (rr=w0+0, ss=(&w20); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #75: @20 = (@19*@5) */
  w20  = (w19*w5);
  /* #76: (@0[2] += @20) */
  for (rr=w0+2, ss=(&w20); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #77: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #78: (@0[1] += @5) */
  for (rr=w0+1, ss=(&w5); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #79: @14 = @14' */
  /* #80: {@5, @20, @12} = horzsplit(@14) */
  w5 = w14[0];
  w20 = w14[1];
  w12 = w14[2];
  /* #81: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #82: @23 = (@13*@12) */
  w23  = (w13*w12);
  /* #83: (@0[2] += @23) */
  for (rr=w0+2, ss=(&w23); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #84: @23 = (@2*@12) */
  w23  = (w2*w12);
  /* #85: (@0[0] += @23) */
  for (rr=w0+0, ss=(&w23); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #86: @23 = (@19*@12) */
  w23  = (w19*w12);
  /* #87: (@0[3] += @23) */
  for (rr=w0+3, ss=(&w23); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #88: @12 = (@21*@12) */
  w12  = (w21*w12);
  /* #89: (@0[1] += @12) */
  for (rr=w0+1, ss=(&w12); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #90: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #91: @12 = (@13*@20) */
  w12  = (w13*w20);
  /* #92: @12 = (-@12) */
  w12 = (- w12 );
  /* #93: (@0[3] += @12) */
  for (rr=w0+3, ss=(&w12); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #94: @12 = (@21*@20) */
  w12  = (w21*w20);
  /* #95: @12 = (-@12) */
  w12 = (- w12 );
  /* #96: (@0[0] += @12) */
  for (rr=w0+0, ss=(&w12); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #97: @12 = (@19*@20) */
  w12  = (w19*w20);
  /* #98: (@0[2] += @12) */
  for (rr=w0+2, ss=(&w12); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #99: @20 = (@2*@20) */
  w20  = (w2*w20);
  /* #100: (@0[1] += @20) */
  for (rr=w0+1, ss=(&w20); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #101: @5 = (-@5) */
  w5 = (- w5 );
  /* #102: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #103: @22 = (@22*@5) */
  w22 *= w5;
  /* #104: (@0[3] += @22) */
  for (rr=w0+3, ss=(&w22); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #105: @3 = (@3*@5) */
  w3 *= w5;
  /* #106: (@0[2] += @3) */
  for (rr=w0+2, ss=(&w3); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #107: @14 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w14);
  /* #108: @3 = @14[0] */
  for (rr=(&w3), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #109: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #110: @8 = (@5*@8) */
  for (i=0, rr=w8, cs=w8; i<4; ++i) (*rr++)  = (w5*(*cs++));
  /* #111: {@5, @22, @20, @12} = vertsplit(@8) */
  w5 = w8[0];
  w22 = w8[1];
  w20 = w8[2];
  w12 = w8[3];
  /* #112: @23 = (@3*@12) */
  w23  = (w3*w12);
  /* #113: @23 = (-@23) */
  w23 = (- w23 );
  /* #114: (@0[2] += @23) */
  for (rr=w0+2, ss=(&w23); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #115: @23 = @14[1] */
  for (rr=(&w23), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #116: @24 = (@23*@12) */
  w24  = (w23*w12);
  /* #117: (@0[1] += @24) */
  for (rr=w0+1, ss=(&w24); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #118: @24 = @14[2] */
  for (rr=(&w24), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #119: @25 = (@24*@12) */
  w25  = (w24*w12);
  /* #120: (@0[0] += @25) */
  for (rr=w0+0, ss=(&w25); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #121: @25 = (@3*@20) */
  w25  = (w3*w20);
  /* #122: (@0[3] += @25) */
  for (rr=w0+3, ss=(&w25); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #123: @25 = (@24*@20) */
  w25  = (w24*w20);
  /* #124: @25 = (-@25) */
  w25 = (- w25 );
  /* #125: (@0[1] += @25) */
  for (rr=w0+1, ss=(&w25); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #126: @25 = (@23*@20) */
  w25  = (w23*w20);
  /* #127: (@0[0] += @25) */
  for (rr=w0+0, ss=(&w25); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #128: @25 = (@23*@22) */
  w25  = (w23*w22);
  /* #129: @25 = (-@25) */
  w25 = (- w25 );
  /* #130: (@0[3] += @25) */
  for (rr=w0+3, ss=(&w25); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #131: @25 = (@24*@22) */
  w25  = (w24*w22);
  /* #132: (@0[2] += @25) */
  for (rr=w0+2, ss=(&w25); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #133: @25 = (@3*@22) */
  w25  = (w3*w22);
  /* #134: (@0[0] += @25) */
  for (rr=w0+0, ss=(&w25); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #135: @25 = (@24*@5) */
  w25  = (w24*w5);
  /* #136: @25 = (-@25) */
  w25 = (- w25 );
  /* #137: (@0[3] += @25) */
  for (rr=w0+3, ss=(&w25); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #138: @25 = (@23*@5) */
  w25  = (w23*w5);
  /* #139: @25 = (-@25) */
  w25 = (- w25 );
  /* #140: (@0[2] += @25) */
  for (rr=w0+2, ss=(&w25); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #141: @25 = (@3*@5) */
  w25  = (w3*w5);
  /* #142: @25 = (-@25) */
  w25 = (- w25 );
  /* #143: (@0[1] += @25) */
  for (rr=w0+1, ss=(&w25); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #144: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #145: output[0][1] = @7 */
  if (res[0]) casadi_copy(w7, 3, res[0]+4);
  /* #146: @7 = zeros(3x1) */
  casadi_clear(w7, 3);
  /* #147: @16 = 
  [[0.315, 0, 0], 
   [0, 0.315, 0], 
   [0, 0, 0.315]] */
  casadi_copy(casadi_c0, 9, w16);
  /* #148: @15 = @16' */
  for (i=0, rr=w15, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #149: @25 = 0 */
  w25 = 0.;
  /* #150: @26 = (-@24) */
  w26 = (- w24 );
  /* #151: @17 = horzcat(@25, @26, @23) */
  rr=w17;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w23;
  /* #152: @17 = @17' */
  /* #153: @26 = (-@3) */
  w26 = (- w3 );
  /* #154: @18 = horzcat(@24, @25, @26) */
  rr=w18;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  /* #155: @18 = @18' */
  /* #156: @23 = (-@23) */
  w23 = (- w23 );
  /* #157: @27 = horzcat(@23, @3, @25) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w3;
  *rr++ = w25;
  /* #158: @27 = @27' */
  /* #159: @28 = horzcat(@17, @18, @27) */
  rr=w28;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #160: @29 = 
  [[3.1746, 0, 0], 
   [0, 3.1746, 0], 
   [0, 0, 3.1746]] */
  casadi_copy(casadi_c1, 9, w29);
  /* #161: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #162: @17 = mac(@30,@10,@7) */
  casadi_copy(w7, 3, w17);
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w30+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #163: @10 = (-@17) */
  for (i=0, rr=w10, cs=w17; i<3; ++i) *rr++ = (- *cs++ );
  /* #164: @18 = mac(@28,@10,@7) */
  casadi_copy(w7, 3, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #165: @27 = mac(@15,@18,@7) */
  casadi_copy(w7, 3, w27);
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #166: @18 = mac(@16,@14,@7) */
  casadi_copy(w7, 3, w18);
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #167: @18 = @18' */
  /* #168: @4 = mac(@10,@18,@4) */
  for (i=0, rr=w4; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w18+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #169: @16 = @4' */
  for (i=0, rr=w16, cs=w4; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #170: {@10, @18, @14} = horzsplit(@16) */
  casadi_copy(w16, 3, w10);
  casadi_copy(w16+3, 3, w18);
  casadi_copy(w16+6, 3, w14);
  /* #171: @14 = @14' */
  /* #172: {@23, @3, NULL} = horzsplit(@14) */
  w23 = w14[0];
  w3 = w14[1];
  /* #173: (@27[0] += @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #174: @23 = (-@23) */
  w23 = (- w23 );
  /* #175: (@27[1] += @23) */
  for (rr=w27+1, ss=(&w23); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #176: @18 = @18' */
  /* #177: {@23, NULL, @3} = horzsplit(@18) */
  w23 = w18[0];
  w3 = w18[2];
  /* #178: @3 = (-@3) */
  w3 = (- w3 );
  /* #179: (@27[0] += @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #180: (@27[2] += @23) */
  for (rr=w27+2, ss=(&w23); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #181: @10 = @10' */
  /* #182: {NULL, @23, @3} = horzsplit(@10) */
  w23 = w10[1];
  w3 = w10[2];
  /* #183: (@27[1] += @3) */
  for (rr=w27+1, ss=(&w3); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #184: @23 = (-@23) */
  w23 = (- w23 );
  /* #185: (@27[2] += @23) */
  for (rr=w27+2, ss=(&w23); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #186: @23 = (@2*@12) */
  w23  = (w2*w12);
  /* #187: @23 = (-@23) */
  w23 = (- w23 );
  /* #188: (@27[0] += @23) */
  for (rr=w27+0, ss=(&w23); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #189: @23 = (@19*@12) */
  w23  = (w19*w12);
  /* #190: (@27[1] += @23) */
  for (rr=w27+1, ss=(&w23); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #191: @12 = (@13*@12) */
  w12  = (w13*w12);
  /* #192: (@27[2] += @12) */
  for (rr=w27+2, ss=(&w12); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #193: @12 = (@21*@20) */
  w12  = (w21*w20);
  /* #194: (@27[0] += @12) */
  for (rr=w27+0, ss=(&w12); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #195: @12 = (@19*@20) */
  w12  = (w19*w20);
  /* #196: @12 = (-@12) */
  w12 = (- w12 );
  /* #197: (@27[2] += @12) */
  for (rr=w27+2, ss=(&w12); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #198: @20 = (@13*@20) */
  w20  = (w13*w20);
  /* #199: (@27[1] += @20) */
  for (rr=w27+1, ss=(&w20); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #200: @20 = (@21*@22) */
  w20  = (w21*w22);
  /* #201: @20 = (-@20) */
  w20 = (- w20 );
  /* #202: (@27[1] += @20) */
  for (rr=w27+1, ss=(&w20); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #203: @20 = (@2*@22) */
  w20  = (w2*w22);
  /* #204: (@27[2] += @20) */
  for (rr=w27+2, ss=(&w20); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #205: @22 = (@13*@22) */
  w22  = (w13*w22);
  /* #206: (@27[0] += @22) */
  for (rr=w27+0, ss=(&w22); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #207: @22 = (@21*@5) */
  w22  = (w21*w5);
  /* #208: @22 = (-@22) */
  w22 = (- w22 );
  /* #209: (@27[2] += @22) */
  for (rr=w27+2, ss=(&w22); rr!=w27+3; rr+=1) *rr += *ss++;
  /* #210: @22 = (@2*@5) */
  w22  = (w2*w5);
  /* #211: @22 = (-@22) */
  w22 = (- w22 );
  /* #212: (@27[1] += @22) */
  for (rr=w27+1, ss=(&w22); rr!=w27+2; rr+=1) *rr += *ss++;
  /* #213: @5 = (@19*@5) */
  w5  = (w19*w5);
  /* #214: @5 = (-@5) */
  w5 = (- w5 );
  /* #215: (@27[0] += @5) */
  for (rr=w27+0, ss=(&w5); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #216: output[0][2] = @27 */
  if (res[0]) casadi_copy(w27, 3, res[0]+7);
  /* #217: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #218: {@5, @22, @20} = vertsplit(@17) */
  w5 = w17[0];
  w22 = w17[1];
  w20 = w17[2];
  /* #219: (@11[5] += @20) */
  for (rr=w11+5, ss=(&w20); rr!=w11+6; rr+=1) *rr += *ss++;
  /* #220: (@11[4] += @22) */
  for (rr=w11+4, ss=(&w22); rr!=w11+5; rr+=1) *rr += *ss++;
  /* #221: (@11[3] += @5) */
  for (rr=w11+3, ss=(&w5); rr!=w11+4; rr+=1) *rr += *ss++;
  /* #222: @5 = 1 */
  w5 = 1.;
  /* #223: @22 = sq(@2) */
  w22 = casadi_sq( w2 );
  /* #224: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #225: @20 = (@5-@22) */
  w20  = (w5-w22);
  /* #226: @12 = sq(@21) */
  w12 = casadi_sq( w21 );
  /* #227: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #228: @20 = (@20-@12) */
  w20 -= w12;
  /* #229: @23 = (@19*@2) */
  w23  = (w19*w2);
  /* #230: @3 = (@13*@21) */
  w3  = (w13*w21);
  /* #231: @25 = (@23-@3) */
  w25  = (w23-w3);
  /* #232: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #233: @24 = (@19*@21) */
  w24  = (w19*w21);
  /* #234: @26 = (@13*@2) */
  w26  = (w13*w2);
  /* #235: @31 = (@24+@26) */
  w31  = (w24+w26);
  /* #236: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #237: @17 = horzcat(@20, @25, @31) */
  rr=w17;
  *rr++ = w20;
  *rr++ = w25;
  *rr++ = w31;
  /* #238: @17 = @17' */
  /* #239: @23 = (@23+@3) */
  w23 += w3;
  /* #240: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #241: @3 = sq(@19) */
  w3 = casadi_sq( w19 );
  /* #242: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #243: @5 = (@5-@3) */
  w5 -= w3;
  /* #244: @12 = (@5-@12) */
  w12  = (w5-w12);
  /* #245: @2 = (@2*@21) */
  w2 *= w21;
  /* #246: @13 = (@13*@19) */
  w13 *= w19;
  /* #247: @19 = (@2-@13) */
  w19  = (w2-w13);
  /* #248: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #249: @27 = horzcat(@23, @12, @19) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w12;
  *rr++ = w19;
  /* #250: @27 = @27' */
  /* #251: @24 = (@24-@26) */
  w24 -= w26;
  /* #252: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #253: @2 = (@2+@13) */
  w2 += w13;
  /* #254: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #255: @5 = (@5-@22) */
  w5 -= w22;
  /* #256: @10 = horzcat(@24, @2, @5) */
  rr=w10;
  *rr++ = w24;
  *rr++ = w2;
  *rr++ = w5;
  /* #257: @10 = @10' */
  /* #258: @16 = horzcat(@17, @27, @10) */
  rr=w16;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  /* #259: @7 = mac(@16,@9,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #260: {@24, @2, @5} = vertsplit(@7) */
  w24 = w7[0];
  w2 = w7[1];
  w5 = w7[2];
  /* #261: (@11[2] += @5) */
  for (rr=w11+2, ss=(&w5); rr!=w11+3; rr+=1) *rr += *ss++;
  /* #262: (@11[1] += @2) */
  for (rr=w11+1, ss=(&w2); rr!=w11+2; rr+=1) *rr += *ss++;
  /* #263: (@11[0] += @24) */
  for (rr=w11+0, ss=(&w24); rr!=w11+1; rr+=1) *rr += *ss++;
  /* #264: output[0][3] = @11 */
  if (res[0]) casadi_copy(w11, 6, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 123;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 123*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
