/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

static const casadi_real casadi_c0[9] = {3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00};
static const casadi_real casadi_c1[9] = {3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01};

/* atmos_ff_expl_ode_fun:(i0[13],i1[6],i2[25])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+23, w16, w17, w18, w19, w20, *w21=w+31, *w22=w+34, *w23=w+37, *w24=w+40, *w25=w+49, *w26=w+58, *w27=w+64, *w28=w+67;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #3: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w2);
  /* #4: @3 = @2[1] */
  for (rr=(&w3), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #5: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #6: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #7: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #8: @5 = (-@5) */
  w5 = (- w5 );
  /* #9: @6 = @2[2] */
  for (rr=(&w6), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #10: @7 = @0[1] */
  for (rr=(&w7), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #11: @8 = (@6*@7) */
  w8  = (w6*w7);
  /* #12: @5 = (@5-@8) */
  w5 -= w8;
  /* #13: @8 = @2[3] */
  for (rr=(&w8), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #14: @9 = @0[2] */
  for (rr=(&w9), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #15: @10 = (@8*@9) */
  w10  = (w8*w9);
  /* #16: @5 = (@5-@10) */
  w5 -= w10;
  /* #17: @10 = @2[0] */
  for (rr=(&w10), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #18: @11 = (@10*@4) */
  w11  = (w10*w4);
  /* #19: @12 = (@6*@9) */
  w12  = (w6*w9);
  /* #20: @11 = (@11+@12) */
  w11 += w12;
  /* #21: @12 = (@8*@7) */
  w12  = (w8*w7);
  /* #22: @11 = (@11-@12) */
  w11 -= w12;
  /* #23: @12 = (@10*@7) */
  w12  = (w10*w7);
  /* #24: @13 = (@3*@9) */
  w13  = (w3*w9);
  /* #25: @12 = (@12-@13) */
  w12 -= w13;
  /* #26: @13 = (@8*@4) */
  w13  = (w8*w4);
  /* #27: @12 = (@12+@13) */
  w12 += w13;
  /* #28: @13 = (@10*@9) */
  w13  = (w10*w9);
  /* #29: @14 = (@3*@7) */
  w14  = (w3*w7);
  /* #30: @13 = (@13+@14) */
  w13 += w14;
  /* #31: @14 = (@6*@4) */
  w14  = (w6*w4);
  /* #32: @13 = (@13-@14) */
  w13 -= w14;
  /* #33: @2 = vertcat(@5, @11, @12, @13) */
  rr=w2;
  *rr++ = w5;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #34: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #35: output[0][1] = @2 */
  if (res[0]) casadi_copy(w2, 4, res[0]+3);
  /* #36: @1 = 0.0595238 */
  w1 = 5.9523809523809521e-02;
  /* #37: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #38: @5 = 1 */
  w5 = 1.;
  /* #39: @11 = sq(@6) */
  w11 = casadi_sq( w6 );
  /* #40: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #41: @12 = (@5-@11) */
  w12  = (w5-w11);
  /* #42: @13 = sq(@8) */
  w13 = casadi_sq( w8 );
  /* #43: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #44: @12 = (@12-@13) */
  w12 -= w13;
  /* #45: @14 = (@3*@6) */
  w14  = (w3*w6);
  /* #46: @16 = (@10*@8) */
  w16  = (w10*w8);
  /* #47: @17 = (@14-@16) */
  w17  = (w14-w16);
  /* #48: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #49: @18 = (@3*@8) */
  w18  = (w3*w8);
  /* #50: @19 = (@10*@6) */
  w19  = (w10*w6);
  /* #51: @20 = (@18+@19) */
  w20  = (w18+w19);
  /* #52: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #53: @21 = horzcat(@12, @17, @20) */
  rr=w21;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w20;
  /* #54: @21 = @21' */
  /* #55: @14 = (@14+@16) */
  w14 += w16;
  /* #56: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #57: @16 = sq(@3) */
  w16 = casadi_sq( w3 );
  /* #58: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #59: @5 = (@5-@16) */
  w5 -= w16;
  /* #60: @13 = (@5-@13) */
  w13  = (w5-w13);
  /* #61: @6 = (@6*@8) */
  w6 *= w8;
  /* #62: @10 = (@10*@3) */
  w10 *= w3;
  /* #63: @3 = (@6-@10) */
  w3  = (w6-w10);
  /* #64: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #65: @22 = horzcat(@14, @13, @3) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w3;
  /* #66: @22 = @22' */
  /* #67: @18 = (@18-@19) */
  w18 -= w19;
  /* #68: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #69: @6 = (@6+@10) */
  w6 += w10;
  /* #70: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #71: @5 = (@5-@11) */
  w5 -= w11;
  /* #72: @23 = horzcat(@18, @6, @5) */
  rr=w23;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w5;
  /* #73: @23 = @23' */
  /* #74: @24 = horzcat(@21, @22, @23) */
  rr=w24;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #75: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #76: @26 = input[1][0] */
  casadi_copy(arg[1], 6, w26);
  /* #77: @18 = @26[0] */
  for (rr=(&w18), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #78: @6 = @26[1] */
  for (rr=(&w6), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #79: @5 = @26[2] */
  for (rr=(&w5), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #80: @21 = vertcat(@18, @6, @5) */
  rr=w21;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w5;
  /* #81: @22 = mac(@25,@21,@15) */
  casadi_copy(w15, 3, w22);
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #82: @22 = (@1*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #83: @21 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+19 : 0, 3, w21);
  /* #84: @21 = (@1*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #85: @22 = (@22+@21) */
  for (i=0, rr=w22, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #86: output[0][2] = @22 */
  if (res[0]) casadi_copy(w22, 3, res[0]+7);
  /* #87: @25 = 
  [[3.1746, 0, 0], 
   [0, 3.1746, 0], 
   [0, 0, 3.1746]] */
  casadi_copy(casadi_c0, 9, w25);
  /* #88: @1 = @26[3] */
  for (rr=(&w1), ss=w26+3; ss!=w26+4; ss+=1) *rr++ = *ss;
  /* #89: @18 = @26[4] */
  for (rr=(&w18), ss=w26+4; ss!=w26+5; ss+=1) *rr++ = *ss;
  /* #90: @6 = @26[5] */
  for (rr=(&w6), ss=w26+5; ss!=w26+6; ss+=1) *rr++ = *ss;
  /* #91: @22 = vertcat(@1, @18, @6) */
  rr=w22;
  *rr++ = w1;
  *rr++ = w18;
  *rr++ = w6;
  /* #92: @21 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+22 : 0, 3, w21);
  /* #93: @22 = (@22+@21) */
  for (i=0, rr=w22, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #94: @1 = 0 */
  w1 = 0.;
  /* #95: @18 = (-@9) */
  w18 = (- w9 );
  /* #96: @21 = horzcat(@1, @18, @7) */
  rr=w21;
  *rr++ = w1;
  *rr++ = w18;
  *rr++ = w7;
  /* #97: @21 = @21' */
  /* #98: @18 = (-@4) */
  w18 = (- w4 );
  /* #99: @23 = horzcat(@9, @1, @18) */
  rr=w23;
  *rr++ = w9;
  *rr++ = w1;
  *rr++ = w18;
  /* #100: @23 = @23' */
  /* #101: @7 = (-@7) */
  w7 = (- w7 );
  /* #102: @27 = horzcat(@7, @4, @1) */
  rr=w27;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w1;
  /* #103: @27 = @27' */
  /* #104: @24 = horzcat(@21, @23, @27) */
  rr=w24;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #105: @28 = @24' */
  for (i=0, rr=w28, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #106: @24 = 
  [[0.315, 0, 0], 
   [0, 0.315, 0], 
   [0, 0, 0.315]] */
  casadi_copy(casadi_c1, 9, w24);
  /* #107: @21 = mac(@24,@0,@15) */
  casadi_copy(w15, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #108: @0 = mac(@28,@21,@15) */
  casadi_copy(w15, 3, w0);
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #109: @22 = (@22-@0) */
  for (i=0, rr=w22, cs=w0; i<3; ++i) (*rr++) -= (*cs++);
  /* #110: @15 = mac(@25,@22,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #111: output[0][3] = @15 */
  if (res[0]) casadi_copy(w15, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 76;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 76*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
