/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) atmos_ff_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s3[20] = {19, 1, 0, 16, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};

static const casadi_real casadi_c0[9] = {3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01, 0., 0., 0., 3.1500000000000000e-01};
static const casadi_real casadi_c1[9] = {3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00, 0., 0., 0., 3.1746031746031744e+00};

/* atmos_ff_expl_vde_adj:(i0[13],i1[13],i2[6],i3[19])->(o0[19x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+16, *w2=w+19, *w3=w+22, *w4=w+26, *w5=w+29, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+42, w16, *w17=w+52, w18, w19, *w20=w+60, *w21=w+63, *w22=w+72, *w23=w+81, *w24=w+84, w25, w26, w27, w28, w29, *w30=w+92, *w31=w+95, *w32=w+104, *w33=w+113;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  casadi_copy(w0, 3, w1);
  casadi_copy(w0+3, 3, w2);
  casadi_copy(w0+6, 4, w3);
  casadi_copy(w0+10, 3, w4);
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @5 = zeros(4x1) */
  casadi_clear(w5, 4);
  /* #4: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w1);
  /* #5: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #6: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #7: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #8: {@7, @8, @9, @10} = vertsplit(@3) */
  w7 = w3[0];
  w8 = w3[1];
  w9 = w3[2];
  w10 = w3[3];
  /* #9: @11 = (@6*@10) */
  w11  = (w6*w10);
  /* #10: @11 = (-@11) */
  w11 = (- w11 );
  /* #11: (@5[2] += @11) */
  for (rr=w5+2, ss=(&w11); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #12: @11 = @1[1] */
  for (rr=(&w11), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #13: @12 = (@11*@10) */
  w12  = (w11*w10);
  /* #14: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #15: @12 = @1[2] */
  for (rr=(&w12), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #16: @13 = (@12*@10) */
  w13  = (w12*w10);
  /* #17: (@5[0] += @13) */
  for (rr=w5+0, ss=(&w13); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #18: @13 = (@6*@9) */
  w13  = (w6*w9);
  /* #19: (@5[3] += @13) */
  for (rr=w5+3, ss=(&w13); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #20: @13 = (@12*@9) */
  w13  = (w12*w9);
  /* #21: @13 = (-@13) */
  w13 = (- w13 );
  /* #22: (@5[1] += @13) */
  for (rr=w5+1, ss=(&w13); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #23: @13 = (@11*@9) */
  w13  = (w11*w9);
  /* #24: (@5[0] += @13) */
  for (rr=w5+0, ss=(&w13); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #25: @13 = (@11*@8) */
  w13  = (w11*w8);
  /* #26: @13 = (-@13) */
  w13 = (- w13 );
  /* #27: (@5[3] += @13) */
  for (rr=w5+3, ss=(&w13); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #28: @13 = (@12*@8) */
  w13  = (w12*w8);
  /* #29: (@5[2] += @13) */
  for (rr=w5+2, ss=(&w13); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #30: @13 = (@6*@8) */
  w13  = (w6*w8);
  /* #31: (@5[0] += @13) */
  for (rr=w5+0, ss=(&w13); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #32: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #33: @13 = (-@13) */
  w13 = (- w13 );
  /* #34: (@5[3] += @13) */
  for (rr=w5+3, ss=(&w13); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #35: @13 = (@11*@7) */
  w13  = (w11*w7);
  /* #36: @13 = (-@13) */
  w13 = (- w13 );
  /* #37: (@5[2] += @13) */
  for (rr=w5+2, ss=(&w13); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #38: @13 = (@6*@7) */
  w13  = (w6*w7);
  /* #39: @13 = (-@13) */
  w13 = (- w13 );
  /* #40: (@5[1] += @13) */
  for (rr=w5+1, ss=(&w13); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #41: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #42: @13 = @3[2] */
  for (rr=(&w13), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #43: @14 = (2.*@13) */
  w14 = (2.* w13 );
  /* #44: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #45: @16 = 0.0561798 */
  w16 = 5.6179775280898875e-02;
  /* #46: @2 = (@16*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #47: @17 = input[2][0] */
  casadi_copy(arg[2], 6, w17);
  /* #48: @16 = @17[0] */
  for (rr=(&w16), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #49: @18 = @17[1] */
  for (rr=(&w18), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #50: @19 = @17[2] */
  for (rr=(&w19), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #51: @20 = vertcat(@16, @18, @19) */
  rr=w20;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w19;
  /* #52: @20 = @20' */
  /* #53: @21 = mac(@2,@20,@15) */
  casadi_copy(w15, 9, w21);
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w20+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #54: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #55: {@20, @23, @24} = horzsplit(@22) */
  casadi_copy(w22, 3, w20);
  casadi_copy(w22+3, 3, w23);
  casadi_copy(w22+6, 3, w24);
  /* #56: @24 = @24' */
  /* #57: {@16, @18, @19} = horzsplit(@24) */
  w16 = w24[0];
  w18 = w24[1];
  w19 = w24[2];
  /* #58: @19 = (-@19) */
  w19 = (- w19 );
  /* #59: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #60: @25 = (@14*@19) */
  w25  = (w14*w19);
  /* #61: (@5[2] += @25) */
  for (rr=w5+2, ss=(&w25); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #62: @25 = @3[1] */
  for (rr=(&w25), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #63: @26 = (2.*@25) */
  w26 = (2.* w25 );
  /* #64: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #65: (@5[1] += @19) */
  for (rr=w5+1, ss=(&w19); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #66: @19 = @3[0] */
  for (rr=(&w19), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #67: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #68: @27 = (@19*@18) */
  w27  = (w19*w18);
  /* #69: (@5[1] += @27) */
  for (rr=w5+1, ss=(&w27); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #70: @27 = (@25*@18) */
  w27  = (w25*w18);
  /* #71: (@5[0] += @27) */
  for (rr=w5+0, ss=(&w27); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #72: @27 = (@13*@18) */
  w27  = (w13*w18);
  /* #73: (@5[3] += @27) */
  for (rr=w5+3, ss=(&w27); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #74: @27 = @3[3] */
  for (rr=(&w27), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #75: @18 = (@27*@18) */
  w18  = (w27*w18);
  /* #76: (@5[2] += @18) */
  for (rr=w5+2, ss=(&w18); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #77: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #78: @18 = (@19*@16) */
  w18  = (w19*w16);
  /* #79: @18 = (-@18) */
  w18 = (- w18 );
  /* #80: (@5[2] += @18) */
  for (rr=w5+2, ss=(&w18); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #81: @18 = (@13*@16) */
  w18  = (w13*w16);
  /* #82: @18 = (-@18) */
  w18 = (- w18 );
  /* #83: (@5[0] += @18) */
  for (rr=w5+0, ss=(&w18); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #84: @18 = (@25*@16) */
  w18  = (w25*w16);
  /* #85: (@5[3] += @18) */
  for (rr=w5+3, ss=(&w18); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #86: @16 = (@27*@16) */
  w16  = (w27*w16);
  /* #87: (@5[1] += @16) */
  for (rr=w5+1, ss=(&w16); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #88: @23 = @23' */
  /* #89: {@16, @18, @28} = horzsplit(@23) */
  w16 = w23[0];
  w18 = w23[1];
  w28 = w23[2];
  /* #90: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #91: @29 = (@19*@28) */
  w29  = (w19*w28);
  /* #92: @29 = (-@29) */
  w29 = (- w29 );
  /* #93: (@5[1] += @29) */
  for (rr=w5+1, ss=(&w29); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #94: @29 = (@25*@28) */
  w29  = (w25*w28);
  /* #95: @29 = (-@29) */
  w29 = (- w29 );
  /* #96: (@5[0] += @29) */
  for (rr=w5+0, ss=(&w29); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #97: @29 = (@13*@28) */
  w29  = (w13*w28);
  /* #98: (@5[3] += @29) */
  for (rr=w5+3, ss=(&w29); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #99: @28 = (@27*@28) */
  w28  = (w27*w28);
  /* #100: (@5[2] += @28) */
  for (rr=w5+2, ss=(&w28); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #101: @28 = (2.*@27) */
  w28 = (2.* w27 );
  /* #102: @18 = (-@18) */
  w18 = (- w18 );
  /* #103: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #104: @29 = (@28*@18) */
  w29  = (w28*w18);
  /* #105: (@5[3] += @29) */
  for (rr=w5+3, ss=(&w29); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #106: @26 = (@26*@18) */
  w26 *= w18;
  /* #107: (@5[1] += @26) */
  for (rr=w5+1, ss=(&w26); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #108: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #109: @26 = (@19*@16) */
  w26  = (w19*w16);
  /* #110: (@5[3] += @26) */
  for (rr=w5+3, ss=(&w26); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #111: @26 = (@27*@16) */
  w26  = (w27*w16);
  /* #112: (@5[0] += @26) */
  for (rr=w5+0, ss=(&w26); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #113: @26 = (@25*@16) */
  w26  = (w25*w16);
  /* #114: (@5[2] += @26) */
  for (rr=w5+2, ss=(&w26); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #115: @16 = (@13*@16) */
  w16  = (w13*w16);
  /* #116: (@5[1] += @16) */
  for (rr=w5+1, ss=(&w16); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #117: @20 = @20' */
  /* #118: {@16, @26, @18} = horzsplit(@20) */
  w16 = w20[0];
  w26 = w20[1];
  w18 = w20[2];
  /* #119: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #120: @29 = (@19*@18) */
  w29  = (w19*w18);
  /* #121: (@5[2] += @29) */
  for (rr=w5+2, ss=(&w29); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #122: @29 = (@13*@18) */
  w29  = (w13*w18);
  /* #123: (@5[0] += @29) */
  for (rr=w5+0, ss=(&w29); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #124: @29 = (@25*@18) */
  w29  = (w25*w18);
  /* #125: (@5[3] += @29) */
  for (rr=w5+3, ss=(&w29); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #126: @18 = (@27*@18) */
  w18  = (w27*w18);
  /* #127: (@5[1] += @18) */
  for (rr=w5+1, ss=(&w18); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #128: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #129: @18 = (@19*@26) */
  w18  = (w19*w26);
  /* #130: @18 = (-@18) */
  w18 = (- w18 );
  /* #131: (@5[3] += @18) */
  for (rr=w5+3, ss=(&w18); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #132: @18 = (@27*@26) */
  w18  = (w27*w26);
  /* #133: @18 = (-@18) */
  w18 = (- w18 );
  /* #134: (@5[0] += @18) */
  for (rr=w5+0, ss=(&w18); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #135: @18 = (@25*@26) */
  w18  = (w25*w26);
  /* #136: (@5[2] += @18) */
  for (rr=w5+2, ss=(&w18); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #137: @26 = (@13*@26) */
  w26  = (w13*w26);
  /* #138: (@5[1] += @26) */
  for (rr=w5+1, ss=(&w26); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #139: @16 = (-@16) */
  w16 = (- w16 );
  /* #140: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #141: @28 = (@28*@16) */
  w28 *= w16;
  /* #142: (@5[3] += @28) */
  for (rr=w5+3, ss=(&w28); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #143: @14 = (@14*@16) */
  w14 *= w16;
  /* #144: (@5[2] += @14) */
  for (rr=w5+2, ss=(&w14); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #145: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 4, res[0]+3);
  /* #146: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #147: @22 = 
  [[0.315, 0, 0], 
   [0, 0.315, 0], 
   [0, 0, 0.315]] */
  casadi_copy(casadi_c0, 9, w22);
  /* #148: @21 = @22' */
  for (i=0, rr=w21, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #149: @14 = 0 */
  w14 = 0.;
  /* #150: @16 = (-@12) */
  w16 = (- w12 );
  /* #151: @23 = horzcat(@14, @16, @11) */
  rr=w23;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w11;
  /* #152: @23 = @23' */
  /* #153: @16 = (-@6) */
  w16 = (- w6 );
  /* #154: @24 = horzcat(@12, @14, @16) */
  rr=w24;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w16;
  /* #155: @24 = @24' */
  /* #156: @11 = (-@11) */
  w11 = (- w11 );
  /* #157: @30 = horzcat(@11, @6, @14) */
  rr=w30;
  *rr++ = w11;
  *rr++ = w6;
  *rr++ = w14;
  /* #158: @30 = @30' */
  /* #159: @31 = horzcat(@23, @24, @30) */
  rr=w31;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #160: @32 = 
  [[3.1746, 0, 0], 
   [0, 3.1746, 0], 
   [0, 0, 3.1746]] */
  casadi_copy(casadi_c1, 9, w32);
  /* #161: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #162: @23 = mac(@33,@4,@20) */
  casadi_copy(w20, 3, w23);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w33+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #163: @4 = (-@23) */
  for (i=0, rr=w4, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #164: @24 = mac(@31,@4,@20) */
  casadi_copy(w20, 3, w24);
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w31+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #165: @30 = mac(@21,@24,@20) */
  casadi_copy(w20, 3, w30);
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #166: @24 = mac(@22,@1,@20) */
  casadi_copy(w20, 3, w24);
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #167: @24 = @24' */
  /* #168: @15 = mac(@4,@24,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w24+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #169: @22 = @15' */
  for (i=0, rr=w22, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #170: {@4, @24, @1} = horzsplit(@22) */
  casadi_copy(w22, 3, w4);
  casadi_copy(w22+3, 3, w24);
  casadi_copy(w22+6, 3, w1);
  /* #171: @1 = @1' */
  /* #172: {@11, @6, NULL} = horzsplit(@1) */
  w11 = w1[0];
  w6 = w1[1];
  /* #173: (@30[0] += @6) */
  for (rr=w30+0, ss=(&w6); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #174: @11 = (-@11) */
  w11 = (- w11 );
  /* #175: (@30[1] += @11) */
  for (rr=w30+1, ss=(&w11); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #176: @24 = @24' */
  /* #177: {@11, NULL, @6} = horzsplit(@24) */
  w11 = w24[0];
  w6 = w24[2];
  /* #178: @6 = (-@6) */
  w6 = (- w6 );
  /* #179: (@30[0] += @6) */
  for (rr=w30+0, ss=(&w6); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #180: (@30[2] += @11) */
  for (rr=w30+2, ss=(&w11); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #181: @4 = @4' */
  /* #182: {NULL, @11, @6} = horzsplit(@4) */
  w11 = w4[1];
  w6 = w4[2];
  /* #183: (@30[1] += @6) */
  for (rr=w30+1, ss=(&w6); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #184: @11 = (-@11) */
  w11 = (- w11 );
  /* #185: (@30[2] += @11) */
  for (rr=w30+2, ss=(&w11); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #186: @11 = (@13*@10) */
  w11  = (w13*w10);
  /* #187: @11 = (-@11) */
  w11 = (- w11 );
  /* #188: (@30[0] += @11) */
  for (rr=w30+0, ss=(&w11); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #189: @11 = (@25*@10) */
  w11  = (w25*w10);
  /* #190: (@30[1] += @11) */
  for (rr=w30+1, ss=(&w11); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #191: @10 = (@19*@10) */
  w10  = (w19*w10);
  /* #192: (@30[2] += @10) */
  for (rr=w30+2, ss=(&w10); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #193: @10 = (@27*@9) */
  w10  = (w27*w9);
  /* #194: (@30[0] += @10) */
  for (rr=w30+0, ss=(&w10); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #195: @10 = (@25*@9) */
  w10  = (w25*w9);
  /* #196: @10 = (-@10) */
  w10 = (- w10 );
  /* #197: (@30[2] += @10) */
  for (rr=w30+2, ss=(&w10); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #198: @9 = (@19*@9) */
  w9  = (w19*w9);
  /* #199: (@30[1] += @9) */
  for (rr=w30+1, ss=(&w9); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #200: @9 = (@27*@8) */
  w9  = (w27*w8);
  /* #201: @9 = (-@9) */
  w9 = (- w9 );
  /* #202: (@30[1] += @9) */
  for (rr=w30+1, ss=(&w9); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #203: @9 = (@13*@8) */
  w9  = (w13*w8);
  /* #204: (@30[2] += @9) */
  for (rr=w30+2, ss=(&w9); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #205: @8 = (@19*@8) */
  w8  = (w19*w8);
  /* #206: (@30[0] += @8) */
  for (rr=w30+0, ss=(&w8); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #207: @8 = (@27*@7) */
  w8  = (w27*w7);
  /* #208: @8 = (-@8) */
  w8 = (- w8 );
  /* #209: (@30[2] += @8) */
  for (rr=w30+2, ss=(&w8); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #210: @8 = (@13*@7) */
  w8  = (w13*w7);
  /* #211: @8 = (-@8) */
  w8 = (- w8 );
  /* #212: (@30[1] += @8) */
  for (rr=w30+1, ss=(&w8); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #213: @7 = (@25*@7) */
  w7  = (w25*w7);
  /* #214: @7 = (-@7) */
  w7 = (- w7 );
  /* #215: (@30[0] += @7) */
  for (rr=w30+0, ss=(&w7); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #216: output[0][2] = @30 */
  if (res[0]) casadi_copy(w30, 3, res[0]+7);
  /* #217: @17 = zeros(6x1) */
  casadi_clear(w17, 6);
  /* #218: {@7, @8, @9} = vertsplit(@23) */
  w7 = w23[0];
  w8 = w23[1];
  w9 = w23[2];
  /* #219: (@17[5] += @9) */
  for (rr=w17+5, ss=(&w9); rr!=w17+6; rr+=1) *rr += *ss++;
  /* #220: (@17[4] += @8) */
  for (rr=w17+4, ss=(&w8); rr!=w17+5; rr+=1) *rr += *ss++;
  /* #221: (@17[3] += @7) */
  for (rr=w17+3, ss=(&w7); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #222: @7 = 1 */
  w7 = 1.;
  /* #223: @8 = sq(@13) */
  w8 = casadi_sq( w13 );
  /* #224: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #225: @9 = (@7-@8) */
  w9  = (w7-w8);
  /* #226: @10 = sq(@27) */
  w10 = casadi_sq( w27 );
  /* #227: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #228: @9 = (@9-@10) */
  w9 -= w10;
  /* #229: @11 = (@25*@13) */
  w11  = (w25*w13);
  /* #230: @6 = (@19*@27) */
  w6  = (w19*w27);
  /* #231: @14 = (@11-@6) */
  w14  = (w11-w6);
  /* #232: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #233: @12 = (@25*@27) */
  w12  = (w25*w27);
  /* #234: @16 = (@19*@13) */
  w16  = (w19*w13);
  /* #235: @28 = (@12+@16) */
  w28  = (w12+w16);
  /* #236: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #237: @23 = horzcat(@9, @14, @28) */
  rr=w23;
  *rr++ = w9;
  *rr++ = w14;
  *rr++ = w28;
  /* #238: @23 = @23' */
  /* #239: @11 = (@11+@6) */
  w11 += w6;
  /* #240: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #241: @6 = sq(@25) */
  w6 = casadi_sq( w25 );
  /* #242: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #243: @7 = (@7-@6) */
  w7 -= w6;
  /* #244: @10 = (@7-@10) */
  w10  = (w7-w10);
  /* #245: @13 = (@13*@27) */
  w13 *= w27;
  /* #246: @19 = (@19*@25) */
  w19 *= w25;
  /* #247: @25 = (@13-@19) */
  w25  = (w13-w19);
  /* #248: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #249: @30 = horzcat(@11, @10, @25) */
  rr=w30;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w25;
  /* #250: @30 = @30' */
  /* #251: @12 = (@12-@16) */
  w12 -= w16;
  /* #252: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #253: @13 = (@13+@19) */
  w13 += w19;
  /* #254: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #255: @7 = (@7-@8) */
  w7 -= w8;
  /* #256: @4 = horzcat(@12, @13, @7) */
  rr=w4;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w7;
  /* #257: @4 = @4' */
  /* #258: @22 = horzcat(@23, @30, @4) */
  rr=w22;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #259: @20 = mac(@22,@2,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #260: {@12, @13, @7} = vertsplit(@20) */
  w12 = w20[0];
  w13 = w20[1];
  w7 = w20[2];
  /* #261: (@17[2] += @7) */
  for (rr=w17+2, ss=(&w7); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #262: (@17[1] += @13) */
  for (rr=w17+1, ss=(&w13); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #263: (@17[0] += @12) */
  for (rr=w17+0, ss=(&w12); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #264: output[0][3] = @17 */
  if (res[0]) casadi_copy(w17, 6, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void atmos_ff_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int atmos_ff_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real atmos_ff_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* atmos_ff_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* atmos_ff_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 122;
  return 0;
}

CASADI_SYMBOL_EXPORT int atmos_ff_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 122*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
