/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

static const casadi_int casadi_s0[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {18, 19, 20, 24, 25, 26, 30, 31, 32};
static const casadi_int casadi_s2[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s3[9] = {49, 50, 51, 62, 63, 64, 75, 76, 77};
static const casadi_int casadi_s4[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s7[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};

static const casadi_real casadi_c0[6] = {1.3699999999999999e+01, 0., 33., 0., 8.0000000000000004e-01, 0.};
static const casadi_real casadi_c1[6] = {1.4490000000000000e+01, 1.4490000000000000e+01, 1.4490000000000000e+01, 2.6000000000000001e-01, 2.3000000000000001e-01, 3.7000000000000000e-01};
static const casadi_real casadi_c2[6] = {6.3600000000000003e+00, 7.1200000000000001e+00, 1.8680000000000000e+01, 1.8900000000000000e-01, 1.3500000000000001e-01, 2.2200000000000000e-01};
static const casadi_real casadi_c3[3] = {0., 0., 2.9999999999999999e-02};
static const casadi_real casadi_c4[3] = {0., 0., 2.0000000000000000e-02};
static const casadi_real casadi_c5[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};

/* nu_r_euler:(i0[7],i1[6])->(o0[6],o1[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+6, *w2=w+13, *w3=w+17, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  /* #2: @1 = input[0][0] */
  casadi_copy(arg[0], 7, w1);
  /* #3: @2 = @1[3:7] */
  for (rr=w2, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #4: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #5: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #6: @2 = (@2/@4) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w4;
  /* #7: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #8: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #9: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #10: @7 = @2[1] */
  for (rr=(&w7), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #11: @8 = @2[2] */
  for (rr=(&w8), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @6 = (@6+@9) */
  w6 += w9;
  /* #14: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #15: @9 = 1 */
  w9 = 1.;
  /* #16: @10 = sq(@8) */
  w10 = casadi_sq( w8 );
  /* #17: @11 = sq(@5) */
  w11 = casadi_sq( w5 );
  /* #18: @10 = (@10+@11) */
  w10 += w11;
  /* #19: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #20: @9 = (@9-@10) */
  w9 -= w10;
  /* #21: @6 = atan2(@6,@9) */
  w6  = atan2(w6,w9);
  /* #22: output[1][0] = @6 */
  if (res[1]) res[1][0] = w6;
  /* #23: @6 = (@4*@8) */
  w6  = (w4*w8);
  /* #24: @9 = (@5*@7) */
  w9  = (w5*w7);
  /* #25: @6 = (@6-@9) */
  w6 -= w9;
  /* #26: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #27: @6 = asin(@6) */
  w6 = asin( w6 );
  /* #28: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #29: @4 = (@4*@7) */
  w4 *= w7;
  /* #30: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #31: @4 = (@4+@5) */
  w4 += w5;
  /* #32: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #33: @5 = 1 */
  w5 = 1.;
  /* #34: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #35: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #36: @7 = (@7+@8) */
  w7 += w8;
  /* #37: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #38: @5 = (@5-@7) */
  w5 -= w7;
  /* #39: @4 = atan2(@4,@5) */
  w4  = atan2(w4,w5);
  /* #40: output[1][2] = @4 */
  if (res[1]) res[1][2] = w4;
  return 0;
}

/* adj1_eta_dynamics:(i0[7],i1[6],out_o0[7x1,0nz],adj_o0[7])->(adj_i0[7],adj_i1[6]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, *w1=w+10, w2, w3, *w4=w+18, *w5=w+25, *w6=w+28, w7, w8, w9, *w10=w+35, *w11=w+44, *w12=w+47, *w13=w+56, *w14=w+59, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+76;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #3: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 7, w4);
  /* #5: {@5, @6} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  /* #6: @6 = (@3*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #7: {@3, @7, @8, @9} = vertsplit(@6) */
  w3 = w6[0];
  w7 = w6[1];
  w8 = w6[2];
  w9 = w6[3];
  /* #8: @2 = (@2*@9) */
  w2 *= w9;
  /* #9: @2 = (-@2) */
  w2 = (- w2 );
  /* #10: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #11: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #12: @2 = (@2*@9) */
  w2 *= w9;
  /* #13: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #14: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #15: @2 = (@2*@9) */
  w2 *= w9;
  /* #16: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #17: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #18: @2 = (@2*@8) */
  w2 *= w8;
  /* #19: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #20: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #21: @2 = (@2*@8) */
  w2 *= w8;
  /* #22: @2 = (-@2) */
  w2 = (- w2 );
  /* #23: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #24: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #25: @2 = (@2*@8) */
  w2 *= w8;
  /* #26: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #27: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #28: @2 = (@2*@7) */
  w2 *= w7;
  /* #29: @2 = (-@2) */
  w2 = (- w2 );
  /* #30: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #31: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #32: @2 = (@2*@7) */
  w2 *= w7;
  /* #33: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #34: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #35: @2 = (@2*@7) */
  w2 *= w7;
  /* #36: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #37: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #38: @2 = (@2*@3) */
  w2 *= w3;
  /* #39: @2 = (-@2) */
  w2 = (- w2 );
  /* #40: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #41: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #42: @2 = (@2*@3) */
  w2 *= w3;
  /* #43: @2 = (-@2) */
  w2 = (- w2 );
  /* #44: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #45: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #46: @2 = (@2*@3) */
  w2 *= w3;
  /* #47: @2 = (-@2) */
  w2 = (- w2 );
  /* #48: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #49: @4 = input[0][0] */
  casadi_copy(arg[0], 7, w4);
  /* #50: @2 = @4[4] */
  for (rr=(&w2), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #51: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #52: @11 = @1[:3] */
  for (rr=w11, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #53: @11 = @11' */
  /* #54: @10 = mac(@5,@11,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w11+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #55: @12 = @10' */
  for (i=0, rr=w12, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #56: {@11, @13, @14} = horzsplit(@12) */
  casadi_copy(w12, 3, w11);
  casadi_copy(w12+3, 3, w13);
  casadi_copy(w12+6, 3, w14);
  /* #57: @14 = @14' */
  /* #58: {@15, @16, @17} = horzsplit(@14) */
  w15 = w14[0];
  w16 = w14[1];
  w17 = w14[2];
  /* #59: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #60: @18 = (@2*@16) */
  w18  = (w2*w16);
  /* #61: @19 = @4[5] */
  for (rr=(&w19), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #62: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #63: @20 = (@19*@15) */
  w20  = (w19*w15);
  /* #64: @18 = (@18-@20) */
  w18 -= w20;
  /* #65: @13 = @13' */
  /* #66: {@20, @21, @22} = horzsplit(@13) */
  w20 = w13[0];
  w21 = w13[1];
  w22 = w13[2];
  /* #67: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #68: @23 = (@2*@22) */
  w23  = (w2*w22);
  /* #69: @18 = (@18-@23) */
  w18 -= w23;
  /* #70: @23 = @4[6] */
  for (rr=(&w23), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #71: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #72: @24 = (@23*@20) */
  w24  = (w23*w20);
  /* #73: @18 = (@18+@24) */
  w18 += w24;
  /* #74: @11 = @11' */
  /* #75: {@24, @25, @26} = horzsplit(@11) */
  w24 = w11[0];
  w25 = w11[1];
  w26 = w11[2];
  /* #76: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #77: @27 = (@19*@26) */
  w27  = (w19*w26);
  /* #78: @18 = (@18+@27) */
  w18 += w27;
  /* #79: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #80: @27 = (@23*@25) */
  w27  = (w23*w25);
  /* #81: @18 = (@18-@27) */
  w18 -= w27;
  /* #82: (@0[3] += @18) */
  for (rr=w0+3, ss=(&w18); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #83: @18 = (2.*@2) */
  w18 = (2.* w2 );
  /* #84: @17 = (-@17) */
  w17 = (- w17 );
  /* #85: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #86: @18 = (@18*@17) */
  w18 *= w17;
  /* #87: @27 = @4[3] */
  for (rr=(&w27), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #88: @28 = (@27*@16) */
  w28  = (w27*w16);
  /* #89: @18 = (@18+@28) */
  w18 += w28;
  /* #90: @28 = (@23*@15) */
  w28  = (w23*w15);
  /* #91: @18 = (@18+@28) */
  w18 += w28;
  /* #92: @28 = (@27*@22) */
  w28  = (w27*w22);
  /* #93: @18 = (@18-@28) */
  w18 -= w28;
  /* #94: @28 = (2.*@2) */
  w28 = (2.* w2 );
  /* #95: @21 = (-@21) */
  w21 = (- w21 );
  /* #96: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #97: @28 = (@28*@21) */
  w28 *= w21;
  /* #98: @18 = (@18+@28) */
  w18 += w28;
  /* #99: @28 = (@19*@20) */
  w28  = (w19*w20);
  /* #100: @18 = (@18+@28) */
  w18 += w28;
  /* #101: @28 = (@23*@26) */
  w28  = (w23*w26);
  /* #102: @18 = (@18+@28) */
  w18 += w28;
  /* #103: @28 = (@19*@25) */
  w28  = (w19*w25);
  /* #104: @18 = (@18+@28) */
  w18 += w28;
  /* #105: (@0[4] += @18) */
  for (rr=w0+4, ss=(&w18); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #106: @18 = (@19*@16) */
  w18  = (w19*w16);
  /* #107: @28 = (@2*@15) */
  w28  = (w2*w15);
  /* #108: @18 = (@18+@28) */
  w18 += w28;
  /* #109: @28 = (@19*@22) */
  w28  = (w19*w22);
  /* #110: @18 = (@18+@28) */
  w18 += w28;
  /* #111: @28 = (2.*@23) */
  w28 = (2.* w23 );
  /* #112: @28 = (@28*@21) */
  w28 *= w21;
  /* #113: @18 = (@18+@28) */
  w18 += w28;
  /* #114: @28 = (@27*@20) */
  w28  = (w27*w20);
  /* #115: @18 = (@18+@28) */
  w18 += w28;
  /* #116: @28 = (@2*@26) */
  w28  = (w2*w26);
  /* #117: @18 = (@18+@28) */
  w18 += w28;
  /* #118: @28 = (@27*@25) */
  w28  = (w27*w25);
  /* #119: @18 = (@18-@28) */
  w18 -= w28;
  /* #120: @28 = (2.*@23) */
  w28 = (2.* w23 );
  /* #121: @24 = (-@24) */
  w24 = (- w24 );
  /* #122: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #123: @28 = (@28*@24) */
  w28 *= w24;
  /* #124: @18 = (@18+@28) */
  w18 += w28;
  /* #125: (@0[6] += @18) */
  for (rr=w0+6, ss=(&w18); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #126: @18 = (2.*@19) */
  w18 = (2.* w19 );
  /* #127: @18 = (@18*@17) */
  w18 *= w17;
  /* #128: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #129: @18 = (@18+@16) */
  w18 += w16;
  /* #130: @15 = (@27*@15) */
  w15  = (w27*w15);
  /* #131: @18 = (@18-@15) */
  w18 -= w15;
  /* #132: @22 = (@23*@22) */
  w22  = (w23*w22);
  /* #133: @18 = (@18+@22) */
  w18 += w22;
  /* #134: @20 = (@2*@20) */
  w20  = (w2*w20);
  /* #135: @18 = (@18+@20) */
  w18 += w20;
  /* #136: @26 = (@27*@26) */
  w26  = (w27*w26);
  /* #137: @18 = (@18+@26) */
  w18 += w26;
  /* #138: @25 = (@2*@25) */
  w25  = (w2*w25);
  /* #139: @18 = (@18+@25) */
  w18 += w25;
  /* #140: @25 = (2.*@19) */
  w25 = (2.* w19 );
  /* #141: @25 = (@25*@24) */
  w25 *= w24;
  /* #142: @18 = (@18+@25) */
  w18 += w25;
  /* #143: (@0[5] += @18) */
  for (rr=w0+5, ss=(&w18); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #144: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  /* #145: @1 = zeros(6x1) */
  casadi_clear(w1, 6);
  /* #146: @18 = @4[5] */
  for (rr=(&w18), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #147: @18 = (@18*@9) */
  w18 *= w9;
  /* #148: @18 = (-@18) */
  w18 = (- w18 );
  /* #149: (@1[3] += @18) */
  for (rr=w1+3, ss=(&w18); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #150: @18 = @4[4] */
  for (rr=(&w18), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #151: @18 = (@18*@9) */
  w18 *= w9;
  /* #152: (@1[4] += @18) */
  for (rr=w1+4, ss=(&w18); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #153: @18 = @4[3] */
  for (rr=(&w18), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #154: @18 = (@18*@9) */
  w18 *= w9;
  /* #155: (@1[5] += @18) */
  for (rr=w1+5, ss=(&w18); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #156: @18 = @4[6] */
  for (rr=(&w18), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #157: @18 = (@18*@8) */
  w18 *= w8;
  /* #158: (@1[3] += @18) */
  for (rr=w1+3, ss=(&w18); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #159: @18 = @4[4] */
  for (rr=(&w18), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #160: @18 = (@18*@8) */
  w18 *= w8;
  /* #161: @18 = (-@18) */
  w18 = (- w18 );
  /* #162: (@1[5] += @18) */
  for (rr=w1+5, ss=(&w18); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #163: @18 = @4[3] */
  for (rr=(&w18), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #164: @18 = (@18*@8) */
  w18 *= w8;
  /* #165: (@1[4] += @18) */
  for (rr=w1+4, ss=(&w18); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #166: @18 = @4[6] */
  for (rr=(&w18), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #167: @18 = (@18*@7) */
  w18 *= w7;
  /* #168: @18 = (-@18) */
  w18 = (- w18 );
  /* #169: (@1[4] += @18) */
  for (rr=w1+4, ss=(&w18); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #170: @18 = @4[5] */
  for (rr=(&w18), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #171: @18 = (@18*@7) */
  w18 *= w7;
  /* #172: (@1[5] += @18) */
  for (rr=w1+5, ss=(&w18); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #173: @18 = @4[3] */
  for (rr=(&w18), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #174: @18 = (@18*@7) */
  w18 *= w7;
  /* #175: (@1[3] += @18) */
  for (rr=w1+3, ss=(&w18); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #176: @18 = @4[6] */
  for (rr=(&w18), ss=w4+6; ss!=w4+7; ss+=1) *rr++ = *ss;
  /* #177: @18 = (@18*@3) */
  w18 *= w3;
  /* #178: @18 = (-@18) */
  w18 = (- w18 );
  /* #179: (@1[5] += @18) */
  for (rr=w1+5, ss=(&w18); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #180: @18 = @4[5] */
  for (rr=(&w18), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #181: @18 = (@18*@3) */
  w18 *= w3;
  /* #182: @18 = (-@18) */
  w18 = (- w18 );
  /* #183: (@1[4] += @18) */
  for (rr=w1+4, ss=(&w18); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #184: @18 = @4[4] */
  for (rr=(&w18), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #185: @18 = (@18*@3) */
  w18 *= w3;
  /* #186: @18 = (-@18) */
  w18 = (- w18 );
  /* #187: (@1[3] += @18) */
  for (rr=w1+3, ss=(&w18); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #188: @11 = zeros(3x1) */
  casadi_clear(w11, 3);
  /* #189: @18 = 1 */
  w18 = 1.;
  /* #190: @3 = sq(@19) */
  w3 = casadi_sq( w19 );
  /* #191: @7 = sq(@23) */
  w7 = casadi_sq( w23 );
  /* #192: @3 = (@3+@7) */
  w3 += w7;
  /* #193: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #194: @18 = (@18-@3) */
  w18 -= w3;
  /* #195: @3 = (@2*@19) */
  w3  = (w2*w19);
  /* #196: @7 = (@27*@23) */
  w7  = (w27*w23);
  /* #197: @3 = (@3-@7) */
  w3 -= w7;
  /* #198: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #199: @7 = (@2*@23) */
  w7  = (w2*w23);
  /* #200: @8 = (@27*@19) */
  w8  = (w27*w19);
  /* #201: @7 = (@7+@8) */
  w7 += w8;
  /* #202: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #203: @13 = horzcat(@18, @3, @7) */
  rr=w13;
  *rr++ = w18;
  *rr++ = w3;
  *rr++ = w7;
  /* #204: @13 = @13' */
  /* #205: @18 = (@2*@19) */
  w18  = (w2*w19);
  /* #206: @3 = (@27*@23) */
  w3  = (w27*w23);
  /* #207: @18 = (@18+@3) */
  w18 += w3;
  /* #208: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #209: @3 = 1 */
  w3 = 1.;
  /* #210: @7 = sq(@2) */
  w7 = casadi_sq( w2 );
  /* #211: @8 = sq(@23) */
  w8 = casadi_sq( w23 );
  /* #212: @7 = (@7+@8) */
  w7 += w8;
  /* #213: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #214: @3 = (@3-@7) */
  w3 -= w7;
  /* #215: @7 = (@19*@23) */
  w7  = (w19*w23);
  /* #216: @8 = (@27*@2) */
  w8  = (w27*w2);
  /* #217: @7 = (@7-@8) */
  w7 -= w8;
  /* #218: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #219: @14 = horzcat(@18, @3, @7) */
  rr=w14;
  *rr++ = w18;
  *rr++ = w3;
  *rr++ = w7;
  /* #220: @14 = @14' */
  /* #221: @18 = (@2*@23) */
  w18  = (w2*w23);
  /* #222: @3 = (@27*@19) */
  w3  = (w27*w19);
  /* #223: @18 = (@18-@3) */
  w18 -= w3;
  /* #224: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #225: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #226: @27 = (@27*@2) */
  w27 *= w2;
  /* #227: @23 = (@23+@27) */
  w23 += w27;
  /* #228: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #229: @27 = 1 */
  w27 = 1.;
  /* #230: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #231: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #232: @2 = (@2+@19) */
  w2 += w19;
  /* #233: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #234: @27 = (@27-@2) */
  w27 -= w2;
  /* #235: @29 = horzcat(@18, @23, @27) */
  rr=w29;
  *rr++ = w18;
  *rr++ = w23;
  *rr++ = w27;
  /* #236: @29 = @29' */
  /* #237: @12 = horzcat(@13, @14, @29) */
  rr=w12;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #238: @11 = mac(@12,@5,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #239: (@1[:3] += @11) */
  for (rr=w1+0, ss=w11; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #240: output[1][0] = @1 */
  casadi_copy(w1, 6, res[1]);
  return 0;
}

/* adj1_D:(i0[6],out_o0[6x6,0nz],adj_o0[6x6,6nz])->(adj_i0[6]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+6, w2, w3, *w4=w+14, w5, w6, w7, w8, w9, w10;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w0, 6);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w1);
  /* #2: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #3: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #4: @3 = 1.5 */
  w3 = 1.5000000000000000e+00;
  /* #5: @4 = input[2][0] */
  casadi_copy(arg[2], 6, w4);
  /* #6: @4 = nonzeros(@4) */
  /* #7: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  /* #8: @3 = (@3*@10) */
  w3 *= w10;
  /* #9: @2 = (@2*@3) */
  w2 *= w3;
  /* #10: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #11: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #12: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #13: @3 = 0.47 */
  w3 = 4.6999999999999997e-01;
  /* #14: @3 = (@3*@9) */
  w3 *= w9;
  /* #15: @2 = (@2*@3) */
  w2 *= w3;
  /* #16: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #17: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #18: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #19: @3 = 1.19 */
  w3 = 1.1899999999999999e+00;
  /* #20: @3 = (@3*@8) */
  w3 *= w8;
  /* #21: @2 = (@2*@3) */
  w2 *= w3;
  /* #22: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #23: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #24: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #25: @3 = 190 */
  w3 = 190.;
  /* #26: @3 = (@3*@7) */
  w3 *= w7;
  /* #27: @2 = (@2*@3) */
  w2 *= w3;
  /* #28: (@0[2] += @2) */
  for (rr=w0+2, ss=(&w2); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #29: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #30: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #31: @3 = 217 */
  w3 = 217.;
  /* #32: @3 = (@3*@6) */
  w3 *= w6;
  /* #33: @2 = (@2*@3) */
  w2 *= w3;
  /* #34: (@0[1] += @2) */
  for (rr=w0+1, ss=(&w2); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #35: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #36: @2 = sign(@2) */
  w2 = casadi_sign( w2 );
  /* #37: @3 = 141 */
  w3 = 141.;
  /* #38: @3 = (@3*@5) */
  w3 *= w5;
  /* #39: @2 = (@2*@3) */
  w2 *= w3;
  /* #40: (@0[0] += @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #41: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  return 0;
}

/* D:(i0[6])->(o0[6x6,6nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, w4, w5, w6, w7, *w8=w+13;
  /* #0: @0 = 141 */
  w0 = 141.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @2 = fabs(@2) */
  w2 = casadi_fabs( w2 );
  /* #4: @0 = (@0*@2) */
  w0 *= w2;
  /* #5: @2 = 217 */
  w2 = 217.;
  /* #6: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #7: @3 = fabs(@3) */
  w3 = casadi_fabs( w3 );
  /* #8: @2 = (@2*@3) */
  w2 *= w3;
  /* #9: @3 = 190 */
  w3 = 190.;
  /* #10: @4 = @1[2] */
  for (rr=(&w4), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #11: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #12: @3 = (@3*@4) */
  w3 *= w4;
  /* #13: @4 = 1.19 */
  w4 = 1.1899999999999999e+00;
  /* #14: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #15: @5 = fabs(@5) */
  w5 = casadi_fabs( w5 );
  /* #16: @4 = (@4*@5) */
  w4 *= w5;
  /* #17: @5 = 0.47 */
  w5 = 4.6999999999999997e-01;
  /* #18: @6 = @1[4] */
  for (rr=(&w6), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #19: @6 = fabs(@6) */
  w6 = casadi_fabs( w6 );
  /* #20: @5 = (@5*@6) */
  w5 *= w6;
  /* #21: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #22: @7 = @1[5] */
  for (rr=(&w7), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #23: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #24: @6 = (@6*@7) */
  w6 *= w7;
  /* #25: @1 = vertcat(@0, @2, @3, @4, @5, @6) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #26: @1 = sparsity_cast(@1) */
  /* #27: @8 = [13.7, 0, 33, 0, 0.8, 0] */
  casadi_copy(casadi_c0, 6, w8);
  /* #28: @8 = sparsity_cast(@8) */
  /* #29: @1 = (@1+@8) */
  for (i=0, rr=w1, cs=w8; i<6; ++i) (*rr++) += (*cs++);
  /* #30: output[0][0] = @1 */
  casadi_copy(w1, 6, res[0]);
  return 0;
}

/* C:(i0[6])->(o0[6x6]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, *w3=w+38, *w4=w+44, *w5=w+50, *w6=w+53, w7, *w8=w+57, *w9=w+60, *w10=w+63, *w11=w+72, *w12=w+81, *w13=w+117;
  /* #0: @0 = zeros(6x6) */
  casadi_clear(w0, 36);
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = [14.49, 14.49, 14.49, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w3);
  /* #4: @3 = sparsity_cast(@3) */
  /* #5: @4 = @3' */
  casadi_trans(w3,casadi_s0, w4, casadi_s0, iw);
  /* #6: @3 = (@3+@4) */
  for (i=0, rr=w3, cs=w4; i<6; ++i) (*rr++) += (*cs++);
  /* #7: @3 = (@2*@3) */
  for (i=0, rr=w3, cs=w3; i<6; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: @5 = @3[:3] */
  for (rr=w5, ss=w3+0; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #9: @5 = nonzeros(@5) */
  /* #10: @4 = input[0][0] */
  casadi_copy(arg[0], 6, w4);
  /* #11: @6 = @4[:3] */
  for (rr=w6, ss=w4+0; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #12: @5 = (@5*@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) *= (*cs++);
  /* #13: @2 = @5[2] */
  for (rr=(&w2), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #14: @2 = (-@2) */
  w2 = (- w2 );
  /* #15: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #16: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #17: @6 = @6' */
  /* #18: @1 = @5[2] */
  for (rr=(&w1), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #19: @2 = 0 */
  w2 = 0.;
  /* #20: @7 = @5[0] */
  for (rr=(&w7), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #21: @7 = (-@7) */
  w7 = (- w7 );
  /* #22: @8 = horzcat(@1, @2, @7) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #23: @8 = @8' */
  /* #24: @1 = @5[1] */
  for (rr=(&w1), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #25: @1 = (-@1) */
  w1 = (- w1 );
  /* #26: @2 = @5[0] */
  for (rr=(&w2), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #27: @7 = 0 */
  w7 = 0.;
  /* #28: @9 = horzcat(@1, @2, @7) */
  rr=w9;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #29: @9 = @9' */
  /* #30: @10 = horzcat(@6, @8, @9) */
  rr=w10;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  /* #31: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #32: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) *rr++ = (- *cs++ );
  /* #33: (@0[18, 19, 20, 24, 25, 26, 30, 31, 32] = @11) */
  for (cii=casadi_s1, rr=w0, ss=w11; cii!=casadi_s1+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #34: @1 = 0 */
  w1 = 0.;
  /* #35: @2 = @5[2] */
  for (rr=(&w2), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #36: @2 = (-@2) */
  w2 = (- w2 );
  /* #37: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #38: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #39: @6 = @6' */
  /* #40: @1 = @5[2] */
  for (rr=(&w1), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #41: @2 = 0 */
  w2 = 0.;
  /* #42: @7 = @5[0] */
  for (rr=(&w7), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #43: @7 = (-@7) */
  w7 = (- w7 );
  /* #44: @8 = horzcat(@1, @2, @7) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #45: @8 = @8' */
  /* #46: @1 = @5[1] */
  for (rr=(&w1), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #47: @1 = (-@1) */
  w1 = (- w1 );
  /* #48: @2 = @5[0] */
  for (rr=(&w2), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #49: @7 = 0 */
  w7 = 0.;
  /* #50: @5 = horzcat(@1, @2, @7) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #51: @5 = @5' */
  /* #52: @11 = horzcat(@6, @8, @5) */
  rr=w11;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #53: @10 = @11' */
  for (i=0, rr=w10, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #54: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) *rr++ = (- *cs++ );
  /* #55: (@0[:18:6;3:6] = @10) */
  for (rr=w0+0, ss=w10; rr!=w0+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #56: @1 = 0 */
  w1 = 0.;
  /* #57: @6 = @3[3:6] */
  for (rr=w6, ss=w3+3; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #58: @6 = nonzeros(@6) */
  /* #59: @8 = @4[3:6] */
  for (rr=w8, ss=w4+3; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #60: @6 = (@6*@8) */
  for (i=0, rr=w6, cs=w8; i<3; ++i) (*rr++) *= (*cs++);
  /* #61: @2 = @6[2] */
  for (rr=(&w2), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #62: @2 = (-@2) */
  w2 = (- w2 );
  /* #63: @7 = @6[1] */
  for (rr=(&w7), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #64: @8 = horzcat(@1, @2, @7) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #65: @8 = @8' */
  /* #66: @1 = @6[2] */
  for (rr=(&w1), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #67: @2 = 0 */
  w2 = 0.;
  /* #68: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #69: @7 = (-@7) */
  w7 = (- w7 );
  /* #70: @5 = horzcat(@1, @2, @7) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #71: @5 = @5' */
  /* #72: @1 = @6[1] */
  for (rr=(&w1), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #73: @1 = (-@1) */
  w1 = (- w1 );
  /* #74: @2 = @6[0] */
  for (rr=(&w2), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #75: @7 = 0 */
  w7 = 0.;
  /* #76: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #77: @6 = @6' */
  /* #78: @10 = horzcat(@8, @5, @6) */
  rr=w10;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  /* #79: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #80: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) *rr++ = (- *cs++ );
  /* #81: (@0[21, 22, 23, 27, 28, 29, 33, 34, 35] = @11) */
  for (cii=casadi_s2, rr=w0, ss=w11; cii!=casadi_s2+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #82: @12 = zeros(6x6) */
  casadi_clear(w12, 36);
  /* #83: @1 = 0 */
  w1 = 0.;
  /* #84: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #85: @3 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w3);
  /* #86: @3 = sparsity_cast(@3) */
  /* #87: @13 = @3' */
  casadi_trans(w3,casadi_s0, w13, casadi_s0, iw);
  /* #88: @3 = (@3+@13) */
  for (i=0, rr=w3, cs=w13; i<6; ++i) (*rr++) += (*cs++);
  /* #89: @3 = (@2*@3) */
  for (i=0, rr=w3, cs=w3; i<6; ++i) (*rr++)  = (w2*(*cs++));
  /* #90: @8 = @3[:3] */
  for (rr=w8, ss=w3+0; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #91: @8 = nonzeros(@8) */
  /* #92: @5 = @4[:3] */
  for (rr=w5, ss=w4+0; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #93: @8 = (@8*@5) */
  for (i=0, rr=w8, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #94: @2 = @8[2] */
  for (rr=(&w2), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #95: @2 = (-@2) */
  w2 = (- w2 );
  /* #96: @7 = @8[1] */
  for (rr=(&w7), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #97: @5 = horzcat(@1, @2, @7) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #98: @5 = @5' */
  /* #99: @1 = @8[2] */
  for (rr=(&w1), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #100: @2 = 0 */
  w2 = 0.;
  /* #101: @7 = @8[0] */
  for (rr=(&w7), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #102: @7 = (-@7) */
  w7 = (- w7 );
  /* #103: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #104: @6 = @6' */
  /* #105: @1 = @8[1] */
  for (rr=(&w1), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #106: @1 = (-@1) */
  w1 = (- w1 );
  /* #107: @2 = @8[0] */
  for (rr=(&w2), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #108: @7 = 0 */
  w7 = 0.;
  /* #109: @9 = horzcat(@1, @2, @7) */
  rr=w9;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #110: @9 = @9' */
  /* #111: @11 = horzcat(@5, @6, @9) */
  rr=w11;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  /* #112: @10 = @11' */
  for (i=0, rr=w10, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #113: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) *rr++ = (- *cs++ );
  /* #114: (@12[18, 19, 20, 24, 25, 26, 30, 31, 32] = @10) */
  for (cii=casadi_s1, rr=w12, ss=w10; cii!=casadi_s1+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #115: @1 = 0 */
  w1 = 0.;
  /* #116: @2 = @8[2] */
  for (rr=(&w2), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #117: @2 = (-@2) */
  w2 = (- w2 );
  /* #118: @7 = @8[1] */
  for (rr=(&w7), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #119: @5 = horzcat(@1, @2, @7) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #120: @5 = @5' */
  /* #121: @1 = @8[2] */
  for (rr=(&w1), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #122: @2 = 0 */
  w2 = 0.;
  /* #123: @7 = @8[0] */
  for (rr=(&w7), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #124: @7 = (-@7) */
  w7 = (- w7 );
  /* #125: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #126: @6 = @6' */
  /* #127: @1 = @8[1] */
  for (rr=(&w1), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #128: @1 = (-@1) */
  w1 = (- w1 );
  /* #129: @2 = @8[0] */
  for (rr=(&w2), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #130: @7 = 0 */
  w7 = 0.;
  /* #131: @8 = horzcat(@1, @2, @7) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #132: @8 = @8' */
  /* #133: @10 = horzcat(@5, @6, @8) */
  rr=w10;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  /* #134: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #135: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) *rr++ = (- *cs++ );
  /* #136: (@12[:18:6;3:6] = @11) */
  for (rr=w12+0, ss=w11; rr!=w12+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #137: @1 = 0 */
  w1 = 0.;
  /* #138: @5 = @3[3:6] */
  for (rr=w5, ss=w3+3; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #139: @5 = nonzeros(@5) */
  /* #140: @6 = @4[3:6] */
  for (rr=w6, ss=w4+3; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #141: @5 = (@5*@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) *= (*cs++);
  /* #142: @2 = @5[2] */
  for (rr=(&w2), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #143: @2 = (-@2) */
  w2 = (- w2 );
  /* #144: @7 = @5[1] */
  for (rr=(&w7), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #145: @6 = horzcat(@1, @2, @7) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #146: @6 = @6' */
  /* #147: @1 = @5[2] */
  for (rr=(&w1), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #148: @2 = 0 */
  w2 = 0.;
  /* #149: @7 = @5[0] */
  for (rr=(&w7), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #150: @7 = (-@7) */
  w7 = (- w7 );
  /* #151: @8 = horzcat(@1, @2, @7) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #152: @8 = @8' */
  /* #153: @1 = @5[1] */
  for (rr=(&w1), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #154: @1 = (-@1) */
  w1 = (- w1 );
  /* #155: @2 = @5[0] */
  for (rr=(&w2), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #156: @7 = 0 */
  w7 = 0.;
  /* #157: @5 = horzcat(@1, @2, @7) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w7;
  /* #158: @5 = @5' */
  /* #159: @11 = horzcat(@6, @8, @5) */
  rr=w11;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #160: @10 = @11' */
  for (i=0, rr=w10, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #161: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) *rr++ = (- *cs++ );
  /* #162: (@12[21, 22, 23, 27, 28, 29, 33, 34, 35] = @10) */
  for (cii=casadi_s2, rr=w12, ss=w10; cii!=casadi_s2+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #163: @0 = (@0+@12) */
  for (i=0, rr=w0, cs=w12; i<36; ++i) (*rr++) += (*cs++);
  /* #164: output[0][0] = @0 */
  casadi_copy(w0, 36, res[0]);
  return 0;
}

/* adj1_C:(i0[6],out_o0[6x6,0nz],adj_o0[6x6])->(adj_i0[6]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, *w2=w+7, *w3=w+13, *w4=w+19, *w5=w+22, *w6=w+25, *w7=w+61, *w8=w+70, *w9=w+79, *w10=w+82, *w11=w+85, w12, *w13=w+89;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w0, 6);
  /* #1: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #2: @2 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w2);
  /* #3: @2 = sparsity_cast(@2) */
  /* #4: @3 = @2' */
  casadi_trans(w2,casadi_s0, w3, casadi_s0, iw);
  /* #5: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<6; ++i) (*rr++) += (*cs++);
  /* #6: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #7: @4 = @2[3:6] */
  for (rr=w4, ss=w2+3; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #8: @4 = nonzeros(@4) */
  /* #9: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #10: @6 = input[2][0] */
  casadi_copy(arg[2], 36, w6);
  /* #11: @7 = @6[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s2, rr=w7, ss=w6; cii!=casadi_s2+9; ++cii) *rr++ = ss[*cii];
  /* #12: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) *rr++ = (- *cs++ );
  /* #13: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #14: {@9, @10, @11} = horzsplit(@8) */
  casadi_copy(w8, 3, w9);
  casadi_copy(w8+3, 3, w10);
  casadi_copy(w8+6, 3, w11);
  /* #15: @11 = @11' */
  /* #16: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #17: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #18: @1 = (-@1) */
  w1 = (- w1 );
  /* #19: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #20: @10 = @10' */
  /* #21: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #22: @12 = (-@12) */
  w12 = (- w12 );
  /* #23: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #24: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #25: @9 = @9' */
  /* #26: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #27: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #28: @1 = (-@1) */
  w1 = (- w1 );
  /* #29: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #30: @4 = (@4*@5) */
  for (i=0, rr=w4, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #31: (@0[3:6] += @4) */
  for (rr=w0+3, ss=w4; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #32: @4 = @2[:3] */
  for (rr=w4, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #33: @4 = nonzeros(@4) */
  /* #34: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #35: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #36: @13 = @6; (@13[21, 22, 23, 27, 28, 29, 33, 34, 35] = @8) */
  casadi_copy(w6, 36, w13);
  for (cii=casadi_s2, rr=w13, ss=w8; cii!=casadi_s2+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #37: @8 = @13[:18:6;3:6] */
  for (rr=w8, ss=w13+0; ss!=w13+18; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #38: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) *rr++ = (- *cs++ );
  /* #39: @7 = @8' */
  for (i=0, rr=w7, cs=w8; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #40: {@9, @10, @11} = horzsplit(@7) */
  casadi_copy(w7, 3, w9);
  casadi_copy(w7+3, 3, w10);
  casadi_copy(w7+6, 3, w11);
  /* #41: @11 = @11' */
  /* #42: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #43: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #44: @1 = (-@1) */
  w1 = (- w1 );
  /* #45: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #46: @10 = @10' */
  /* #47: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #48: @12 = (-@12) */
  w12 = (- w12 );
  /* #49: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #50: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #51: @9 = @9' */
  /* #52: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #53: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #54: @1 = (-@1) */
  w1 = (- w1 );
  /* #55: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #56: @7 = zeros(3x3) */
  casadi_clear(w7, 9);
  /* #57: (@13[:18:6;3:6] = @7) */
  for (rr=w13+0, ss=w7; rr!=w13+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #58: @7 = @13[18, 19, 20, 24, 25, 26, 30, 31, 32] */
  for (cii=casadi_s1, rr=w7, ss=w13; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #59: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) *rr++ = (- *cs++ );
  /* #60: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #61: {@9, @10, @11} = horzsplit(@8) */
  casadi_copy(w8, 3, w9);
  casadi_copy(w8+3, 3, w10);
  casadi_copy(w8+6, 3, w11);
  /* #62: @11 = @11' */
  /* #63: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #64: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #65: @1 = (-@1) */
  w1 = (- w1 );
  /* #66: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #67: @10 = @10' */
  /* #68: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #69: @12 = (-@12) */
  w12 = (- w12 );
  /* #70: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #71: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #72: @9 = @9' */
  /* #73: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #74: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #75: @1 = (-@1) */
  w1 = (- w1 );
  /* #76: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #77: @4 = (@4*@5) */
  for (i=0, rr=w4, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #78: (@0[:3] += @4) */
  for (rr=w0+0, ss=w4; rr!=w0+3; rr+=1) *rr += *ss++;
  /* #79: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #80: @2 = [14.49, 14.49, 14.49, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w2);
  /* #81: @2 = sparsity_cast(@2) */
  /* #82: @3 = @2' */
  casadi_trans(w2,casadi_s0, w3, casadi_s0, iw);
  /* #83: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<6; ++i) (*rr++) += (*cs++);
  /* #84: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<6; ++i) (*rr++)  = (w1*(*cs++));
  /* #85: @4 = @2[3:6] */
  for (rr=w4, ss=w2+3; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #86: @4 = nonzeros(@4) */
  /* #87: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #88: @8 = @6[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s2, rr=w8, ss=w6; cii!=casadi_s2+9; ++cii) *rr++ = ss[*cii];
  /* #89: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) *rr++ = (- *cs++ );
  /* #90: @7 = @8' */
  for (i=0, rr=w7, cs=w8; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #91: {@9, @10, @11} = horzsplit(@7) */
  casadi_copy(w7, 3, w9);
  casadi_copy(w7+3, 3, w10);
  casadi_copy(w7+6, 3, w11);
  /* #92: @11 = @11' */
  /* #93: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #94: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #95: @1 = (-@1) */
  w1 = (- w1 );
  /* #96: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #97: @10 = @10' */
  /* #98: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #99: @12 = (-@12) */
  w12 = (- w12 );
  /* #100: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #101: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #102: @9 = @9' */
  /* #103: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #104: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #105: @1 = (-@1) */
  w1 = (- w1 );
  /* #106: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #107: @4 = (@4*@5) */
  for (i=0, rr=w4, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #108: (@0[3:6] += @4) */
  for (rr=w0+3, ss=w4; rr!=w0+6; rr+=1) *rr += *ss++;
  /* #109: @4 = @2[:3] */
  for (rr=w4, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #110: @4 = nonzeros(@4) */
  /* #111: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #112: @7 = zeros(3x3) */
  casadi_clear(w7, 9);
  /* #113: (@6[21, 22, 23, 27, 28, 29, 33, 34, 35] = @7) */
  for (cii=casadi_s2, rr=w6, ss=w7; cii!=casadi_s2+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #114: @7 = @6[:18:6;3:6] */
  for (rr=w7, ss=w6+0; ss!=w6+18; ss+=6) for (tt=ss+3; tt!=ss+6; tt+=1) *rr++ = *tt;
  /* #115: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) *rr++ = (- *cs++ );
  /* #116: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #117: {@9, @10, @11} = horzsplit(@8) */
  casadi_copy(w8, 3, w9);
  casadi_copy(w8+3, 3, w10);
  casadi_copy(w8+6, 3, w11);
  /* #118: @11 = @11' */
  /* #119: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #120: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #121: @1 = (-@1) */
  w1 = (- w1 );
  /* #122: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #123: @10 = @10' */
  /* #124: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #125: @12 = (-@12) */
  w12 = (- w12 );
  /* #126: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #127: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #128: @9 = @9' */
  /* #129: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #130: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #131: @1 = (-@1) */
  w1 = (- w1 );
  /* #132: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #133: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #134: (@6[:18:6;3:6] = @8) */
  for (rr=w6+0, ss=w8; rr!=w6+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #135: @8 = @6[18, 19, 20, 24, 25, 26, 30, 31, 32] */
  for (cii=casadi_s1, rr=w8, ss=w6; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #136: @8 = (-@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) *rr++ = (- *cs++ );
  /* #137: @7 = @8' */
  for (i=0, rr=w7, cs=w8; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #138: {@9, @10, @11} = horzsplit(@7) */
  casadi_copy(w7, 3, w9);
  casadi_copy(w7+3, 3, w10);
  casadi_copy(w7+6, 3, w11);
  /* #139: @11 = @11' */
  /* #140: {@1, @12, NULL} = horzsplit(@11) */
  w1 = w11[0];
  w12 = w11[1];
  /* #141: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #142: @1 = (-@1) */
  w1 = (- w1 );
  /* #143: (@5[1] += @1) */
  for (rr=w5+1, ss=(&w1); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #144: @10 = @10' */
  /* #145: {@1, NULL, @12} = horzsplit(@10) */
  w1 = w10[0];
  w12 = w10[2];
  /* #146: @12 = (-@12) */
  w12 = (- w12 );
  /* #147: (@5[0] += @12) */
  for (rr=w5+0, ss=(&w12); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #148: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #149: @9 = @9' */
  /* #150: {NULL, @1, @12} = horzsplit(@9) */
  w1 = w9[1];
  w12 = w9[2];
  /* #151: (@5[1] += @12) */
  for (rr=w5+1, ss=(&w12); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #152: @1 = (-@1) */
  w1 = (- w1 );
  /* #153: (@5[2] += @1) */
  for (rr=w5+2, ss=(&w1); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #154: @4 = (@4*@5) */
  for (i=0, rr=w4, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #155: (@0[:3] += @4) */
  for (rr=w0+0, ss=w4; rr!=w0+3; rr+=1) *rr += *ss++;
  /* #156: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  return 0;
}

/* adj1_g:(i0[3],out_o0[6x1,0nz],adj_o0[6])->(adj_i0[3]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+3, w2, w3, w4, *w5=w+9, w6, *w7=w+13, w8, w9, *w10=w+18, w11, w12, w13, w14, w15, w16, w17, w18, w19;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = 142.147 */
  w4 = 1.4214690000000002e+02;
  /* #5: @5 = [0, 0, 0.03] */
  casadi_copy(casadi_c3, 3, w5);
  /* #6: @6 = @5[2] */
  for (rr=(&w6), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #7: @4 = (@4*@6) */
  w4 *= w6;
  /* #8: @6 = 142.147 */
  w6 = 1.4214690000000002e+02;
  /* #9: @7 = [0, 0, 0.02] */
  casadi_copy(casadi_c4, 3, w7);
  /* #10: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #11: @6 = (@6*@8) */
  w6 *= w8;
  /* #12: @4 = (@4-@6) */
  w4 -= w6;
  /* #13: @6 = @1[1] */
  for (rr=(&w6), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @8 = cos(@6) */
  w8 = cos( w6 );
  /* #15: @9 = (@4*@8) */
  w9  = (w4*w8);
  /* #16: @10 = input[2][0] */
  casadi_copy(arg[2], 6, w10);
  /* #17: {NULL, NULL, NULL, @11, @12, @13} = vertsplit(@10) */
  w11 = w10[3];
  w12 = w10[4];
  w13 = w10[5];
  /* #18: @9 = (@9*@11) */
  w9 *= w11;
  /* #19: @14 = 142.147 */
  w14 = 1.4214690000000002e+02;
  /* #20: @15 = @5[0] */
  for (rr=(&w15), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #21: @14 = (@14*@15) */
  w14 *= w15;
  /* #22: @15 = 142.147 */
  w15 = 1.4214690000000002e+02;
  /* #23: @16 = @7[0] */
  for (rr=(&w16), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #24: @15 = (@15*@16) */
  w15 *= w16;
  /* #25: @14 = (@14-@15) */
  w14 -= w15;
  /* #26: @15 = (@14*@8) */
  w15  = (w14*w8);
  /* #27: @15 = (@15*@13) */
  w15 *= w13;
  /* #28: @9 = (@9-@15) */
  w9 -= w15;
  /* #29: @3 = (@3*@9) */
  w3 *= w9;
  /* #30: @9 = sin(@2) */
  w9 = sin( w2 );
  /* #31: @15 = 142.147 */
  w15 = 1.4214690000000002e+02;
  /* #32: @16 = @5[0] */
  for (rr=(&w16), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #33: @15 = (@15*@16) */
  w15 *= w16;
  /* #34: @16 = 142.147 */
  w16 = 1.4214690000000002e+02;
  /* #35: @17 = @7[0] */
  for (rr=(&w17), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #36: @16 = (@16*@17) */
  w16 *= w17;
  /* #37: @15 = (@15-@16) */
  w15 -= w16;
  /* #38: @16 = (@15*@8) */
  w16  = (w15*w8);
  /* #39: @16 = (@16*@12) */
  w16 *= w12;
  /* #40: @17 = 142.147 */
  w17 = 1.4214690000000002e+02;
  /* #41: @18 = @5[1] */
  for (rr=(&w18), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #42: @17 = (@17*@18) */
  w17 *= w18;
  /* #43: @18 = 142.147 */
  w18 = 1.4214690000000002e+02;
  /* #44: @19 = @7[1] */
  for (rr=(&w19), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #45: @18 = (@18*@19) */
  w18 *= w19;
  /* #46: @17 = (@17-@18) */
  w17 -= w18;
  /* #47: @8 = (@17*@8) */
  w8  = (w17*w8);
  /* #48: @8 = (@8*@11) */
  w8 *= w11;
  /* #49: @16 = (@16-@8) */
  w16 -= w8;
  /* #50: @9 = (@9*@16) */
  w9 *= w16;
  /* #51: @3 = (@3-@9) */
  w3 -= w9;
  /* #52: (@0[2] += @3) */
  for (rr=w0+2, ss=(&w3); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #53: @3 = cos(@6) */
  w3 = cos( w6 );
  /* #54: @9 = 142.147 */
  w9 = 1.4214690000000002e+02;
  /* #55: @16 = @5[2] */
  for (rr=(&w16), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #56: @9 = (@9*@16) */
  w9 *= w16;
  /* #57: @16 = 142.147 */
  w16 = 1.4214690000000002e+02;
  /* #58: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #59: @16 = (@16*@8) */
  w16 *= w8;
  /* #60: @9 = (@9-@16) */
  w9 -= w16;
  /* #61: @9 = (@9*@12) */
  w9 *= w12;
  /* #62: @16 = 142.147 */
  w16 = 1.4214690000000002e+02;
  /* #63: @8 = @5[1] */
  for (rr=(&w8), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #64: @16 = (@16*@8) */
  w16 *= w8;
  /* #65: @8 = 142.147 */
  w8 = 1.4214690000000002e+02;
  /* #66: @18 = @7[1] */
  for (rr=(&w18), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #67: @8 = (@8*@18) */
  w8 *= w18;
  /* #68: @16 = (@16-@8) */
  w16 -= w8;
  /* #69: @16 = (@16*@13) */
  w16 *= w13;
  /* #70: @9 = (@9-@16) */
  w9 -= w16;
  /* #71: @3 = (@3*@9) */
  w3 *= w9;
  /* #72: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #73: @9 = cos(@2) */
  w9 = cos( w2 );
  /* #74: @12 = (@9*@12) */
  w12  = (w9*w12);
  /* #75: @15 = (@15*@12) */
  w15 *= w12;
  /* #76: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #77: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #78: @14 = (@14*@13) */
  w14 *= w13;
  /* #79: @15 = (@15-@14) */
  w15 -= w14;
  /* #80: @9 = (@9*@11) */
  w9 *= w11;
  /* #81: @17 = (@17*@9) */
  w17 *= w9;
  /* #82: @15 = (@15-@17) */
  w15 -= w17;
  /* #83: @2 = (@2*@11) */
  w2 *= w11;
  /* #84: @4 = (@4*@2) */
  w4 *= w2;
  /* #85: @15 = (@15+@4) */
  w15 += w4;
  /* #86: @6 = (@6*@15) */
  w6 *= w15;
  /* #87: @3 = (@3-@6) */
  w3 -= w6;
  /* #88: (@0[1] += @3) */
  for (rr=w0+1, ss=(&w3); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #89: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  return 0;
}

/* adj1_fx:(i0[7],i1[6],i2[6],i3[3],out_o0[13x1,0nz],adj_o0[13])->(adj_i0[7],adj_i1[6],adj_i2[6],adj_i3[3]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+4, *rr, *ss, *tt;
  const casadi_real **arg1=arg+6, *cr, *cs;
  casadi_real *w0=w+125, *w1=w+132, *w3=w+138, *w4=w+151, *w5=w+158, *w6=w+164, *w7=w+171, *w8=w+177, *w9=w+213, *w10=w+219, *w11=w+225, *w12=w+261, *w13=w+264;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = zeros(7x1,0nz) */
  /* #3: @3 = input[5][0] */
  casadi_copy(arg[5], 13, w3);
  /* #4: {@4, @5} = vertsplit(@3) */
  casadi_copy(w3, 7, w4);
  casadi_copy(w3+7, 6, w5);
  /* #5: {@6, @7} = adj1_eta_dynamics(@0, @1, @2, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=0;
  arg1[3]=w4;
  res1[0]=w6;
  res1[1]=w7;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @6 */
  casadi_copy(w6, 7, res[0]);
  /* #7: output[1][0] = @7 */
  casadi_copy(w7, 6, res[1]);
  /* #8: @7 = input[2][0] */
  casadi_copy(arg[2], 6, w7);
  /* #9: @2 = zeros(6x6,0nz) */
  /* #10: @1 = zeros(6x1) */
  casadi_clear(w1, 6);
  /* #11: @8 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 36, w8);
  /* #12: @9 = [14.49, 14.49, 14.49, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w9);
  /* #13: @9 = sparsity_cast(@9) */
  /* #14: @10 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w10);
  /* #15: @10 = sparsity_cast(@10) */
  /* #16: @9 = (@9+@10) */
  for (i=0, rr=w9, cs=w10; i<6; ++i) (*rr++) += (*cs++);
  /* #17: @8 = (@9\@8) */
  casadi_triusolve(casadi_s0, w9, w8, 0, 0, 6);
  /* #18: @11 = @8' */
  for (i=0, rr=w11, cs=w8; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #19: @1 = mac(@11,@5,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w11+j, tt=w5+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #20: @5 = (@7*@1) */
  for (i=0, rr=w5, cr=w7, cs=w1; i<6; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #21: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<6; ++i) *rr++ = (- *cs++ );
  /* #22: @5 = sparsity_cast(@5) */
  /* #23: @9 = adj1_D(@7, @2, @5) */
  arg1[0]=w7;
  arg1[1]=0;
  arg1[2]=w5;
  res1[0]=w9;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #24: @5 = D(@7) */
  arg1[0]=w7;
  res1[0]=w5;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #25: @5 = nonzeros(@5) */
  /* #26: @5 = (@5*@1) */
  for (i=0, rr=w5, cs=w1; i<6; ++i) (*rr++) *= (*cs++);
  /* #27: @9 = (@9-@5) */
  for (i=0, rr=w9, cs=w5; i<6; ++i) (*rr++) -= (*cs++);
  /* #28: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #29: @11 = C(@7) */
  arg1[0]=w7;
  res1[0]=w11;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #30: @8 = @11' */
  for (i=0, rr=w8, cs=w11; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #31: @10 = (-@1) */
  for (i=0, rr=w10, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #32: @5 = mac(@8,@10,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w8+j, tt=w10+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #33: @9 = (@9+@5) */
  for (i=0, rr=w9, cs=w5; i<6; ++i) (*rr++) += (*cs++);
  /* #34: @2 = zeros(6x6,0nz) */
  /* #35: @8 = zeros(6x6) */
  casadi_clear(w8, 36);
  /* #36: @5 = @7' */
  casadi_copy(w7, 6, w5);
  /* #37: @8 = mac(@10,@5,@8) */
  for (i=0, rr=w8; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w10+j, tt=w5+i*1; k<1; ++k) *rr += ss[k*6]**tt++;
  /* #38: @10 = adj1_C(@7, @2, @8) */
  arg1[0]=w7;
  arg1[1]=0;
  arg1[2]=w8;
  res1[0]=w10;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #39: @9 = (@9+@10) */
  for (i=0, rr=w9, cs=w10; i<6; ++i) (*rr++) += (*cs++);
  /* #40: output[2][0] = @9 */
  casadi_copy(w9, 6, res[2]);
  /* #41: @12 = input[3][0] */
  casadi_copy(arg[3], 3, w12);
  /* #42: @2 = zeros(6x1,0nz) */
  /* #43: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #44: @13 = adj1_g(@12, @2, @1) */
  arg1[0]=w12;
  arg1[1]=0;
  arg1[2]=w1;
  res1[0]=w13;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #45: output[3][0] = @13 */
  casadi_copy(w13, 3, res[3]);
  return 0;
}

/* adj1_nu_r_euler:(i0[7],i1[6],out_o0[6x1,0nz],out_o1[3x1,0nz],adj_o0[6],adj_o1[3])->(adj_i0[7],adj_i1[6]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+7, *w2=w+14, *w3=w+18, w4, *w5=w+23, *w6=w+27, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+41, w18, w19, w20, w21, w22, *w23=w+49;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 7, w1);
  /* #2: @2 = @1[3:7] */
  for (rr=w2, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #3: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #4: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #5: @2 = (@2/@4) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w4;
  /* #6: @5 = (@2/@4) */
  for (i=0, rr=w5, cr=w2; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #7: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<4; ++i) *rr++ = (- *cs++ );
  /* #8: @6 = zeros(4x1) */
  casadi_clear(w6, 4);
  /* #9: @7 = @2[2] */
  for (rr=(&w7), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #10: @8 = (2.*@7) */
  w8 = (2.* w7 );
  /* #11: @9 = @2[0] */
  for (rr=(&w9), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #12: @10 = @2[1] */
  for (rr=(&w10), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #13: @11 = (@9*@10) */
  w11  = (w9*w10);
  /* #14: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #15: @13 = (@7*@12) */
  w13  = (w7*w12);
  /* #16: @11 = (@11+@13) */
  w11 += w13;
  /* #17: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #18: @13 = sq(@11) */
  w13 = casadi_sq( w11 );
  /* #19: @14 = 1 */
  w14 = 1.;
  /* #20: @15 = sq(@10) */
  w15 = casadi_sq( w10 );
  /* #21: @16 = sq(@7) */
  w16 = casadi_sq( w7 );
  /* #22: @15 = (@15+@16) */
  w15 += w16;
  /* #23: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #24: @14 = (@14-@15) */
  w14 -= w15;
  /* #25: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: @11 = (@11/@13) */
  w11 /= w13;
  /* #28: @17 = input[5][0] */
  casadi_copy(arg[5], 3, w17);
  /* #29: {@15, @16, @18} = vertsplit(@17) */
  w15 = w17[0];
  w16 = w17[1];
  w18 = w17[2];
  /* #30: @11 = (@11*@18) */
  w11 *= w18;
  /* #31: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #32: @8 = (@8*@11) */
  w8 *= w11;
  /* #33: @14 = (@14/@13) */
  w14 /= w13;
  /* #34: @14 = (@14*@18) */
  w14 *= w18;
  /* #35: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #36: @18 = (@12*@14) */
  w18  = (w12*w14);
  /* #37: @8 = (@8+@18) */
  w8 += w18;
  /* #38: @18 = 1 */
  w18 = 1.;
  /* #39: @13 = (@9*@7) */
  w13  = (w9*w7);
  /* #40: @19 = (@12*@10) */
  w19  = (w12*w10);
  /* #41: @13 = (@13-@19) */
  w13 -= w19;
  /* #42: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #43: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #44: @18 = (@18-@13) */
  w18 -= w13;
  /* #45: @18 = sqrt(@18) */
  w18 = sqrt( w18 );
  /* #46: @16 = (@16/@18) */
  w16 /= w18;
  /* #47: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #48: @18 = (@9*@16) */
  w18  = (w9*w16);
  /* #49: @8 = (@8+@18) */
  w8 += w18;
  /* #50: @18 = (2.*@7) */
  w18 = (2.* w7 );
  /* #51: @13 = (@9*@12) */
  w13  = (w9*w12);
  /* #52: @19 = (@10*@7) */
  w19  = (w10*w7);
  /* #53: @13 = (@13+@19) */
  w13 += w19;
  /* #54: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #55: @19 = sq(@13) */
  w19 = casadi_sq( w13 );
  /* #56: @20 = 1 */
  w20 = 1.;
  /* #57: @21 = sq(@7) */
  w21 = casadi_sq( w7 );
  /* #58: @22 = sq(@12) */
  w22 = casadi_sq( w12 );
  /* #59: @21 = (@21+@22) */
  w21 += w22;
  /* #60: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #61: @20 = (@20-@21) */
  w20 -= w21;
  /* #62: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #63: @19 = (@19+@21) */
  w19 += w21;
  /* #64: @13 = (@13/@19) */
  w13 /= w19;
  /* #65: @13 = (@13*@15) */
  w13 *= w15;
  /* #66: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #67: @18 = (@18*@13) */
  w18 *= w13;
  /* #68: @8 = (@8+@18) */
  w8 += w18;
  /* #69: @20 = (@20/@19) */
  w20 /= w19;
  /* #70: @20 = (@20*@15) */
  w20 *= w15;
  /* #71: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #72: @15 = (@10*@20) */
  w15  = (w10*w20);
  /* #73: @8 = (@8+@15) */
  w8 += w15;
  /* #74: (@6[2] += @8) */
  for (rr=w6+2, ss=(&w8); rr!=w6+3; rr+=1) *rr += *ss++;
  /* #75: @8 = (2.*@10) */
  w8 = (2.* w10 );
  /* #76: @8 = (@8*@11) */
  w8 *= w11;
  /* #77: @11 = (@9*@14) */
  w11  = (w9*w14);
  /* #78: @8 = (@8+@11) */
  w8 += w11;
  /* #79: @11 = (@12*@16) */
  w11  = (w12*w16);
  /* #80: @8 = (@8-@11) */
  w8 -= w11;
  /* #81: @11 = (@7*@20) */
  w11  = (w7*w20);
  /* #82: @8 = (@8+@11) */
  w8 += w11;
  /* #83: (@6[1] += @8) */
  for (rr=w6+1, ss=(&w8); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #84: @8 = (@7*@14) */
  w8  = (w7*w14);
  /* #85: @11 = (@10*@16) */
  w11  = (w10*w16);
  /* #86: @8 = (@8-@11) */
  w8 -= w11;
  /* #87: @11 = (2.*@12) */
  w11 = (2.* w12 );
  /* #88: @11 = (@11*@13) */
  w11 *= w13;
  /* #89: @8 = (@8+@11) */
  w8 += w11;
  /* #90: @9 = (@9*@20) */
  w9 *= w20;
  /* #91: @8 = (@8+@9) */
  w8 += w9;
  /* #92: (@6[3] += @8) */
  for (rr=w6+3, ss=(&w8); rr!=w6+4; rr+=1) *rr += *ss++;
  /* #93: @10 = (@10*@14) */
  w10 *= w14;
  /* #94: @7 = (@7*@16) */
  w7 *= w16;
  /* #95: @10 = (@10+@7) */
  w10 += w7;
  /* #96: @12 = (@12*@20) */
  w12 *= w20;
  /* #97: @10 = (@10+@12) */
  w10 += w12;
  /* #98: (@6[0] += @10) */
  for (rr=w6+0, ss=(&w10); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #99: @10 = dot(@5, @6) */
  w10 = casadi_dot(4, w5, w6);
  /* #100: @10 = (@10/@4) */
  w10 /= w4;
  /* #101: @3 = (@10*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #102: (@0[3:7] += @3) */
  for (rr=w0+3, ss=w3; rr!=w0+7; rr+=1) *rr += *ss++;
  /* #103: @6 = (@6/@4) */
  for (i=0, rr=w6; i<4; ++i) (*rr++) /= w4;
  /* #104: (@0[3:7] += @6) */
  for (rr=w0+3, ss=w6; rr!=w0+7; rr+=1) *rr += *ss++;
  /* #105: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  /* #106: @23 = input[4][0] */
  casadi_copy(arg[4], 6, w23);
  /* #107: output[1][0] = @23 */
  casadi_copy(w23, 6, res[1]);
  return 0;
}

/* gx:(i0[13])->(o0[13x6]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+18, *w2=w+42, *w3=w+78, *w4=w+84, *w5=w+90, *w6=w+126, *w7=w+204;
  /* #0: @0 = zeros(6x3) */
  casadi_clear(w0, 18);
  /* #1: @1 = zeros(6x4) */
  casadi_clear(w1, 24);
  /* #2: @2 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 36, w2);
  /* #3: @3 = [14.49, 14.49, 14.49, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w3);
  /* #4: @3 = sparsity_cast(@3) */
  /* #5: @4 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w4);
  /* #6: @4 = sparsity_cast(@4) */
  /* #7: @3 = (@3+@4) */
  for (i=0, rr=w3, cs=w4; i<6; ++i) (*rr++) += (*cs++);
  /* #8: @2 = (@3\@2) */
  casadi_triusolve(casadi_s0, w3, w2, 0, 0, 6);
  /* #9: @5 = @2' */
  for (i=0, rr=w5, cs=w2; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #10: @6 = horzcat(@0, @1, @5) */
  rr=w6;
  for (i=0, cs=w0; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<24; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<36; ++i) *rr++ = *cs++;
  /* #11: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<13; ++i) for (j=0; j<6; ++j) rr[i+j*13] = *cs++;
  /* #12: output[0][0] = @7 */
  casadi_copy(w7, 78, res[0]);
  return 0;
}

/* cx:(i0[3],i1[4],i2[3],i3[3])->(o0[13x6]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+78, *w2=w+114, *w3=w+120, *w4=w+126;
  /* #0: @0 = zeros(13x6) */
  casadi_clear(w0, 78);
  /* #1: @1 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c5, 36, w1);
  /* #2: @2 = [14.49, 14.49, 14.49, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w2);
  /* #3: @2 = sparsity_cast(@2) */
  /* #4: @3 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w3);
  /* #5: @3 = sparsity_cast(@3) */
  /* #6: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<6; ++i) (*rr++) += (*cs++);
  /* #7: @1 = (@2\@1) */
  casadi_triusolve(casadi_s0, w2, w1, 0, 0, 6);
  /* #8: @4 = @1[:18:6;:3] */
  for (rr=w4, ss=w1+0; ss!=w1+18; ss+=6) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #9: (@0[:39:13;7:10] = @4) */
  for (rr=w0+0, ss=w4; rr!=w0+39; rr+=13) for (tt=rr+7; tt!=rr+10; tt+=1) *tt = *ss++;
  /* #10: @4 = @1[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s2, rr=w4, ss=w1; cii!=casadi_s2+9; ++cii) *rr++ = ss[*cii];
  /* #11: (@0[49, 50, 51, 62, 63, 64, 75, 76, 77] = @4) */
  for (cii=casadi_s3, rr=w0, ss=w4; cii!=casadi_s3+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #12: output[0][0] = @0 */
  casadi_copy(w0, 78, res[0]);
  return 0;
}

/* adj1_disturbed_dynamics:(i0[13],i1[6],i2[3],i3[3],out_o0[13x1,0nz],adj_o0[13])->(adj_i0[13],adj_i1[6],adj_i2[3],adj_i3[3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+4, *rr, *ss, *tt;
  const casadi_real **arg1=arg+6, *cs;
  casadi_real *w0=w+282, *w1=w+295, *w2=w+308, *w3=w+315, *w4=w+321, *w5=w+327, *w7=w+330, *w8=w+343, *w9=w+350, *w10=w+356, *w11=w+362, *w13=w+365, *w14=w+372, *w15=w+450, *w16=w+528, *w17=w+532;
  /* #0: @0 = zeros(13x1) */
  casadi_clear(w0, 13);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 13, w1);
  /* #2: @2 = @1[:7] */
  for (rr=w2, ss=w1+0; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #3: @3 = @1[7:13] */
  for (rr=w3, ss=w1+7; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #4: {@4, @5} = nu_r_euler(@2, @3) */
  arg1[0]=w2;
  arg1[1]=w3;
  res1[0]=w4;
  res1[1]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @6 = zeros(13x1,0nz) */
  /* #6: @7 = input[5][0] */
  casadi_copy(arg[5], 13, w7);
  /* #7: {@8, @9, @10, @11} = adj1_fx(@2, @3, @4, @5, @6, @7) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=w4;
  arg1[3]=w5;
  arg1[4]=0;
  arg1[5]=w7;
  res1[0]=w8;
  res1[1]=w9;
  res1[2]=w10;
  res1[3]=w11;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @6 = zeros(6x1,0nz) */
  /* #9: @12 = zeros(3x1,0nz) */
  /* #10: {@13, @4} = adj1_nu_r_euler(@2, @3, @6, @12, @10, @11) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=w10;
  arg1[5]=w11;
  res1[0]=w13;
  res1[1]=w4;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #11: @9 = (@9+@4) */
  for (i=0, rr=w9, cs=w4; i<6; ++i) (*rr++) += (*cs++);
  /* #12: (@0[7:13] += @9) */
  for (rr=w0+7, ss=w9; rr!=w0+13; rr+=1) *rr += *ss++;
  /* #13: @8 = (@8+@13) */
  for (i=0, rr=w8, cs=w13; i<7; ++i) (*rr++) += (*cs++);
  /* #14: (@0[:7] += @8) */
  for (rr=w0+0, ss=w8; rr!=w0+7; rr+=1) *rr += *ss++;
  /* #15: output[0][0] = @0 */
  casadi_copy(w0, 13, res[0]);
  /* #16: @9 = zeros(6x1) */
  casadi_clear(w9, 6);
  /* #17: @14 = gx(@1) */
  arg1[0]=w1;
  res1[0]=w14;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #18: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<6; ++i) for (j=0; j<13; ++j) rr[i+j*6] = *cs++;
  /* #19: @9 = mac(@15,@7,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w15+j, tt=w7+i*13; k<13; ++k) *rr += ss[k*6]**tt++;
  /* #20: output[1][0] = @9 */
  casadi_copy(w9, 6, res[1]);
  /* #21: @9 = zeros(6x1) */
  casadi_clear(w9, 6);
  /* #22: @11 = @1[:3] */
  for (rr=w11, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #23: @16 = @1[3:7] */
  for (rr=w16, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #24: @5 = @1[7:10] */
  for (rr=w5, ss=w1+7; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #25: @17 = @1[10:13] */
  for (rr=w17, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #26: @15 = cx(@11, @16, @5, @17) */
  arg1[0]=w11;
  arg1[1]=w16;
  arg1[2]=w5;
  arg1[3]=w17;
  res1[0]=w15;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #27: @14 = @15' */
  for (i=0, rr=w14, cs=w15; i<6; ++i) for (j=0; j<13; ++j) rr[i+j*6] = *cs++;
  /* #28: @9 = mac(@14,@7,@9) */
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w14+j, tt=w7+i*13; k<13; ++k) *rr += ss[k*6]**tt++;
  /* #29: {@11, @5} = vertsplit(@9) */
  casadi_copy(w9, 3, w11);
  casadi_copy(w9+3, 3, w5);
  /* #30: output[2][0] = @11 */
  casadi_copy(w11, 3, res[2]);
  /* #31: output[3][0] = @5 */
  casadi_copy(w5, 3, res[3]);
  return 0;
}

/* bluerov_expl_vde_adj:(i0[13],i1[13],i2[6],i3[25])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+535, *w1=w+538, *w2=w+542, *w3=w+545, *w4=w+548, *w5=w+561, *w7=w+567, *w8=w+580, *w9=w+593;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w2);
  /* #3: @3 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w3);
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  /* #5: @5 = input[2][0] */
  casadi_copy(arg[2], 6, w5);
  /* #6: @0 = input[3][2] */
  casadi_copy(arg[3] ? arg[3]+19 : 0, 3, w0);
  /* #7: @2 = input[3][3] */
  casadi_copy(arg[3] ? arg[3]+22 : 0, 3, w2);
  /* #8: @6 = zeros(13x1,0nz) */
  /* #9: @7 = input[1][0] */
  casadi_copy(arg[1], 13, w7);
  /* #10: {@8, @9, NULL, NULL} = adj1_disturbed_dynamics(@4, @5, @0, @2, @6, @7) */
  arg1[0]=w4;
  arg1[1]=w5;
  arg1[2]=w0;
  arg1[3]=w2;
  arg1[4]=0;
  arg1[5]=w7;
  res1[0]=w8;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #11: {@0, @1, @2, @3} = vertsplit(@8) */
  casadi_copy(w8, 3, w0);
  casadi_copy(w8+3, 4, w1);
  casadi_copy(w8+7, 3, w2);
  casadi_copy(w8+10, 3, w3);
  /* #12: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #13: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+3);
  /* #14: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 3, res[0]+7);
  /* #15: output[0][3] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+10);
  /* #16: output[0][4] = @9 */
  if (res[0]) casadi_copy(w9, 6, res[0]+13);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 599;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 599*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
