/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s2[64] = {6, 13, 0, 6, 12, 18, 24, 30, 36, 42, 43, 44, 45, 46, 47, 48, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[57] = {13, 6, 0, 8, 16, 24, 32, 40, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 8, 0, 1, 2, 3, 4, 5, 6, 9, 0, 1, 2, 3, 4, 5, 6, 10, 0, 1, 2, 3, 4, 5, 6, 11, 0, 1, 2, 3, 4, 5, 6, 12};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s7[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};

static const casadi_real casadi_c0[6] = {1.3500000000000000e+01, 1.3500000000000000e+01, 1.3500000000000000e+01, 2.6000000000000001e-01, 2.3000000000000001e-01, 3.7000000000000000e-01};
static const casadi_real casadi_c1[6] = {6.3600000000000003e+00, 7.1200000000000001e+00, 1.8680000000000000e+01, 1.8900000000000000e-01, 1.3500000000000001e-01, 2.2200000000000000e-01};
static const casadi_real casadi_c2[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};

/* adj1_gx:(i0[13],out_o0[13x6,0nz],adj_o0[13x6])->(adj_i0[13]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+13, w2, w3, *w4=w+28, *w5=w+106, *w6=w+184, *w7=w+202, *w8=w+220, *w9=w+229, *w10=w+238, *w11=w+241, *w12=w+244, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25;
  /* #0: @0 = zeros(13x1) */
  casadi_clear(w0, 13);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 13, w1);
  /* #2: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #3: @3 = 0.0740741 */
  w3 = 7.4074074074074070e-02;
  /* #4: @4 = input[2][0] */
  casadi_copy(arg[2], 78, w4);
  /* #5: @5 = @4' */
  for (i=0, rr=w5, cs=w4; i<6; ++i) for (j=0; j<13; ++j) rr[i+j*6] = *cs++;
  /* #6: {NULL, @6, NULL} = horzsplit(@5) */
  casadi_copy(w5+42, 18, w6);
  /* #7: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<6; ++j) rr[i+j*3] = *cs++;
  /* #8: {@8, NULL} = horzsplit(@7) */
  casadi_copy(w7, 9, w8);
  /* #9: @8 = (@3*@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) (*rr++)  = (w3*(*cs++));
  /* #10: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #11: {@10, @11, @12} = horzsplit(@9) */
  casadi_copy(w9, 3, w10);
  casadi_copy(w9+3, 3, w11);
  casadi_copy(w9+6, 3, w12);
  /* #12: @12 = @12' */
  /* #13: {@3, @13, @14} = horzsplit(@12) */
  w3 = w12[0];
  w13 = w12[1];
  w14 = w12[2];
  /* #14: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #15: @15 = (@2*@13) */
  w15  = (w2*w13);
  /* #16: @16 = @1[5] */
  for (rr=(&w16), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #17: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #18: @17 = (@16*@3) */
  w17  = (w16*w3);
  /* #19: @15 = (@15-@17) */
  w15 -= w17;
  /* #20: @11 = @11' */
  /* #21: {@17, @18, @19} = horzsplit(@11) */
  w17 = w11[0];
  w18 = w11[1];
  w19 = w11[2];
  /* #22: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #23: @20 = (@2*@19) */
  w20  = (w2*w19);
  /* #24: @15 = (@15-@20) */
  w15 -= w20;
  /* #25: @20 = @1[6] */
  for (rr=(&w20), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #26: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #27: @21 = (@20*@17) */
  w21  = (w20*w17);
  /* #28: @15 = (@15+@21) */
  w15 += w21;
  /* #29: @10 = @10' */
  /* #30: {@21, @22, @23} = horzsplit(@10) */
  w21 = w10[0];
  w22 = w10[1];
  w23 = w10[2];
  /* #31: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #32: @24 = (@16*@23) */
  w24  = (w16*w23);
  /* #33: @15 = (@15+@24) */
  w15 += w24;
  /* #34: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #35: @24 = (@20*@22) */
  w24  = (w20*w22);
  /* #36: @15 = (@15-@24) */
  w15 -= w24;
  /* #37: (@0[3] += @15) */
  for (rr=w0+3, ss=(&w15); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #38: @15 = (2.*@2) */
  w15 = (2.* w2 );
  /* #39: @14 = (-@14) */
  w14 = (- w14 );
  /* #40: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #41: @15 = (@15*@14) */
  w15 *= w14;
  /* #42: @24 = @1[3] */
  for (rr=(&w24), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #43: @25 = (@24*@13) */
  w25  = (w24*w13);
  /* #44: @15 = (@15+@25) */
  w15 += w25;
  /* #45: @25 = (@20*@3) */
  w25  = (w20*w3);
  /* #46: @15 = (@15+@25) */
  w15 += w25;
  /* #47: @25 = (@24*@19) */
  w25  = (w24*w19);
  /* #48: @15 = (@15-@25) */
  w15 -= w25;
  /* #49: @25 = (2.*@2) */
  w25 = (2.* w2 );
  /* #50: @18 = (-@18) */
  w18 = (- w18 );
  /* #51: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #52: @25 = (@25*@18) */
  w25 *= w18;
  /* #53: @15 = (@15+@25) */
  w15 += w25;
  /* #54: @25 = (@16*@17) */
  w25  = (w16*w17);
  /* #55: @15 = (@15+@25) */
  w15 += w25;
  /* #56: @25 = (@20*@23) */
  w25  = (w20*w23);
  /* #57: @15 = (@15+@25) */
  w15 += w25;
  /* #58: @25 = (@16*@22) */
  w25  = (w16*w22);
  /* #59: @15 = (@15+@25) */
  w15 += w25;
  /* #60: (@0[4] += @15) */
  for (rr=w0+4, ss=(&w15); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #61: @15 = (@16*@13) */
  w15  = (w16*w13);
  /* #62: @25 = (@2*@3) */
  w25  = (w2*w3);
  /* #63: @15 = (@15+@25) */
  w15 += w25;
  /* #64: @25 = (@16*@19) */
  w25  = (w16*w19);
  /* #65: @15 = (@15+@25) */
  w15 += w25;
  /* #66: @25 = (2.*@20) */
  w25 = (2.* w20 );
  /* #67: @25 = (@25*@18) */
  w25 *= w18;
  /* #68: @15 = (@15+@25) */
  w15 += w25;
  /* #69: @25 = (@24*@17) */
  w25  = (w24*w17);
  /* #70: @15 = (@15+@25) */
  w15 += w25;
  /* #71: @25 = (@2*@23) */
  w25  = (w2*w23);
  /* #72: @15 = (@15+@25) */
  w15 += w25;
  /* #73: @25 = (@24*@22) */
  w25  = (w24*w22);
  /* #74: @15 = (@15-@25) */
  w15 -= w25;
  /* #75: @25 = (2.*@20) */
  w25 = (2.* w20 );
  /* #76: @21 = (-@21) */
  w21 = (- w21 );
  /* #77: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #78: @25 = (@25*@21) */
  w25 *= w21;
  /* #79: @15 = (@15+@25) */
  w15 += w25;
  /* #80: (@0[6] += @15) */
  for (rr=w0+6, ss=(&w15); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #81: @15 = (2.*@16) */
  w15 = (2.* w16 );
  /* #82: @15 = (@15*@14) */
  w15 *= w14;
  /* #83: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #84: @15 = (@15+@13) */
  w15 += w13;
  /* #85: @3 = (@24*@3) */
  w3  = (w24*w3);
  /* #86: @15 = (@15-@3) */
  w15 -= w3;
  /* #87: @20 = (@20*@19) */
  w20 *= w19;
  /* #88: @15 = (@15+@20) */
  w15 += w20;
  /* #89: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #90: @15 = (@15+@17) */
  w15 += w17;
  /* #91: @24 = (@24*@23) */
  w24 *= w23;
  /* #92: @15 = (@15+@24) */
  w15 += w24;
  /* #93: @2 = (@2*@22) */
  w2 *= w22;
  /* #94: @15 = (@15+@2) */
  w15 += w2;
  /* #95: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #96: @16 = (@16*@21) */
  w16 *= w21;
  /* #97: @15 = (@15+@16) */
  w15 += w16;
  /* #98: (@0[5] += @15) */
  for (rr=w0+5, ss=(&w15); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #99: output[0][0] = @0 */
  casadi_copy(w0, 13, res[0]);
  return 0;
}

/* nu_r_euler:(i0[7],i1[6])->(o0[6],o1[3]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+6, *w2=w+13, *w3=w+17, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  /* #2: @1 = input[0][0] */
  casadi_copy(arg[0], 7, w1);
  /* #3: @2 = @1[3:7] */
  for (rr=w2, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #4: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #5: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #6: @2 = (@2/@4) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w4;
  /* #7: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #8: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #9: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #10: @7 = @2[1] */
  for (rr=(&w7), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #11: @8 = @2[2] */
  for (rr=(&w8), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @6 = (@6+@9) */
  w6 += w9;
  /* #14: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #15: @9 = 1 */
  w9 = 1.;
  /* #16: @10 = sq(@8) */
  w10 = casadi_sq( w8 );
  /* #17: @11 = sq(@5) */
  w11 = casadi_sq( w5 );
  /* #18: @10 = (@10+@11) */
  w10 += w11;
  /* #19: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #20: @9 = (@9-@10) */
  w9 -= w10;
  /* #21: @6 = atan2(@6,@9) */
  w6  = atan2(w6,w9);
  /* #22: output[1][0] = @6 */
  if (res[1]) res[1][0] = w6;
  /* #23: @6 = (@4*@8) */
  w6  = (w4*w8);
  /* #24: @9 = (@5*@7) */
  w9  = (w5*w7);
  /* #25: @6 = (@6-@9) */
  w6 -= w9;
  /* #26: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #27: @6 = asin(@6) */
  w6 = asin( w6 );
  /* #28: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #29: @4 = (@4*@7) */
  w4 *= w7;
  /* #30: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #31: @4 = (@4+@5) */
  w4 += w5;
  /* #32: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #33: @5 = 1 */
  w5 = 1.;
  /* #34: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #35: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #36: @7 = (@7+@8) */
  w7 += w8;
  /* #37: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #38: @5 = (@5-@7) */
  w5 -= w7;
  /* #39: @4 = atan2(@4,@5) */
  w4  = atan2(w4,w5);
  /* #40: output[1][2] = @4 */
  if (res[1]) res[1][2] = w4;
  return 0;
}

/* adj1_eta_dynamics:(i0[7],i1[6],out_o0[7x1,0nz],adj_o0[7])->(adj_i0[7],adj_i1[6]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+7, w2, w3, *w4=w+15, *w5=w+22, *w6=w+25, w7, w8, w9;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #3: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #4: @4 = input[3][0] */
  casadi_copy(arg[3], 7, w4);
  /* #5: {@5, @6} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  /* #6: @6 = (@3*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #7: {@3, @7, @8, @9} = vertsplit(@6) */
  w3 = w6[0];
  w7 = w6[1];
  w8 = w6[2];
  w9 = w6[3];
  /* #8: @2 = (@2*@9) */
  w2 *= w9;
  /* #9: @2 = (-@2) */
  w2 = (- w2 );
  /* #10: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #11: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #12: @2 = (@2*@9) */
  w2 *= w9;
  /* #13: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #14: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #15: @2 = (@2*@9) */
  w2 *= w9;
  /* #16: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #17: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #18: @2 = (@2*@8) */
  w2 *= w8;
  /* #19: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #20: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #21: @2 = (@2*@8) */
  w2 *= w8;
  /* #22: @2 = (-@2) */
  w2 = (- w2 );
  /* #23: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #24: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #25: @2 = (@2*@8) */
  w2 *= w8;
  /* #26: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #27: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #28: @2 = (@2*@7) */
  w2 *= w7;
  /* #29: @2 = (-@2) */
  w2 = (- w2 );
  /* #30: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #31: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #32: @2 = (@2*@7) */
  w2 *= w7;
  /* #33: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #34: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #35: @2 = (@2*@7) */
  w2 *= w7;
  /* #36: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #37: @2 = @1[5] */
  for (rr=(&w2), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #38: @2 = (@2*@3) */
  w2 *= w3;
  /* #39: @2 = (-@2) */
  w2 = (- w2 );
  /* #40: (@0[6] += @2) */
  for (rr=w0+6, ss=(&w2); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #41: @2 = @1[4] */
  for (rr=(&w2), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #42: @2 = (@2*@3) */
  w2 *= w3;
  /* #43: @2 = (-@2) */
  w2 = (- w2 );
  /* #44: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #45: @2 = @1[3] */
  for (rr=(&w2), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #46: @2 = (@2*@3) */
  w2 *= w3;
  /* #47: @2 = (-@2) */
  w2 = (- w2 );
  /* #48: (@0[4] += @2) */
  for (rr=w0+4, ss=(&w2); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #49: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  /* #50: @1 = zeros(6x1) */
  casadi_clear(w1, 6);
  /* #51: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #52: @2 = @0[5] */
  for (rr=(&w2), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #53: @2 = (@2*@9) */
  w2 *= w9;
  /* #54: @2 = (-@2) */
  w2 = (- w2 );
  /* #55: (@1[3] += @2) */
  for (rr=w1+3, ss=(&w2); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #56: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #57: @2 = (@2*@9) */
  w2 *= w9;
  /* #58: (@1[4] += @2) */
  for (rr=w1+4, ss=(&w2); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #59: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #60: @2 = (@2*@9) */
  w2 *= w9;
  /* #61: (@1[5] += @2) */
  for (rr=w1+5, ss=(&w2); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #62: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #63: @2 = (@2*@8) */
  w2 *= w8;
  /* #64: (@1[3] += @2) */
  for (rr=w1+3, ss=(&w2); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #65: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #66: @2 = (@2*@8) */
  w2 *= w8;
  /* #67: @2 = (-@2) */
  w2 = (- w2 );
  /* #68: (@1[5] += @2) */
  for (rr=w1+5, ss=(&w2); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #69: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #70: @2 = (@2*@8) */
  w2 *= w8;
  /* #71: (@1[4] += @2) */
  for (rr=w1+4, ss=(&w2); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #72: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #73: @2 = (@2*@7) */
  w2 *= w7;
  /* #74: @2 = (-@2) */
  w2 = (- w2 );
  /* #75: (@1[4] += @2) */
  for (rr=w1+4, ss=(&w2); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #76: @2 = @0[5] */
  for (rr=(&w2), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #77: @2 = (@2*@7) */
  w2 *= w7;
  /* #78: (@1[5] += @2) */
  for (rr=w1+5, ss=(&w2); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #79: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #80: @2 = (@2*@7) */
  w2 *= w7;
  /* #81: (@1[3] += @2) */
  for (rr=w1+3, ss=(&w2); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #82: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #83: @2 = (@2*@3) */
  w2 *= w3;
  /* #84: @2 = (-@2) */
  w2 = (- w2 );
  /* #85: (@1[5] += @2) */
  for (rr=w1+5, ss=(&w2); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #86: @2 = @0[5] */
  for (rr=(&w2), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #87: @2 = (@2*@3) */
  w2 *= w3;
  /* #88: @2 = (-@2) */
  w2 = (- w2 );
  /* #89: (@1[4] += @2) */
  for (rr=w1+4, ss=(&w2); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #90: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #91: @2 = (@2*@3) */
  w2 *= w3;
  /* #92: @2 = (-@2) */
  w2 = (- w2 );
  /* #93: (@1[3] += @2) */
  for (rr=w1+3, ss=(&w2); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #94: (@1[:3] += @5) */
  for (rr=w1+0, ss=w5; rr!=w1+3; rr+=1) *rr += *ss++;
  /* #95: output[1][0] = @1 */
  casadi_copy(w1, 6, res[1]);
  return 0;
}

/* adj1_fx:(i0[7],i1[6],i2[6],i3[3],out_o0[13x1,0nz],adj_o0[13])->(adj_i0[7],adj_i1[6],adj_i2[6x1,0nz],adj_i3[3x1,0nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+4, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+6, *cr, *cs;
  casadi_real *w0=w+32, *w1=w+39, *w3=w+45, *w4=w+58, *w5=w+65, *w6=w+68, *w7=w+75, *w8=w+81, *w9=w+87, *w10=w+93, *w11=w+99, *w12=w+102, w13, w14, w15, *w16=w+108, *w17=w+111, *w18=w+114, *w19=w+117, *w20=w+126, *w21=w+162, *w22=w+171;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = zeros(7x1,0nz) */
  /* #3: @3 = input[5][0] */
  casadi_copy(arg[5], 13, w3);
  /* #4: {@4, NULL, @5} = vertsplit(@3) */
  casadi_copy(w3, 7, w4);
  casadi_copy(w3+10, 3, w5);
  /* #5: {@6, @7} = adj1_eta_dynamics(@0, @1, @2, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=0;
  arg1[3]=w4;
  res1[0]=w6;
  res1[1]=w7;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @6 */
  casadi_copy(w6, 7, res[0]);
  /* #7: @8 = zeros(6x1) */
  casadi_clear(w8, 6);
  /* #8: @9 = [13.5, 13.5, 13.5, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c0, 6, w9);
  /* #9: @9 = sparsity_cast(@9) */
  /* #10: @10 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c1, 6, w10);
  /* #11: @10 = sparsity_cast(@10) */
  /* #12: @9 = (@9+@10) */
  for (i=0, rr=w9, cs=w10; i<6; ++i) (*rr++) += (*cs++);
  /* #13: @11 = @9[3:6] */
  for (rr=w11, ss=w9+3; ss!=w9+6; ss+=1) *rr++ = *ss;
  /* #14: @11 = nonzeros(@11) */
  /* #15: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #16: @13 = 0 */
  w13 = 0.;
  /* #17: @14 = @1[5] */
  for (rr=(&w14), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #18: @14 = (-@14) */
  w14 = (- w14 );
  /* #19: @15 = @1[4] */
  for (rr=(&w15), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #20: @16 = horzcat(@13, @14, @15) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #21: @16 = @16' */
  /* #22: @13 = @1[4] */
  for (rr=(&w13), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #23: @14 = 0 */
  w14 = 0.;
  /* #24: @15 = @1[3] */
  for (rr=(&w15), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #25: @15 = (-@15) */
  w15 = (- w15 );
  /* #26: @17 = horzcat(@13, @14, @15) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #27: @17 = @17' */
  /* #28: @13 = @1[4] */
  for (rr=(&w13), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #29: @13 = (-@13) */
  w13 = (- w13 );
  /* #30: @14 = @1[3] */
  for (rr=(&w14), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #31: @15 = 0 */
  w15 = 0.;
  /* #32: @18 = horzcat(@13, @14, @15) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #33: @18 = @18' */
  /* #34: @19 = horzcat(@16, @17, @18) */
  rr=w19;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #35: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #36: @20 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c2, 36, w20);
  /* #37: @20 = (@9\@20) */
  casadi_triusolve(casadi_s0, w9, w20, 0, 0, 6);
  /* #38: @21 = @20[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s1, rr=w21, ss=w20; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #39: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<9; ++i) *rr++ = (- *cs++ );
  /* #40: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #41: @16 = mac(@22,@5,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #42: @12 = mac(@19,@16,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #43: @12 = (@11*@12) */
  for (i=0, rr=w12, cr=w11, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #44: (@8[3:6] += @12) */
  for (rr=w8+3, ss=w12; rr!=w8+6; rr+=1) *rr += *ss++;
  /* #45: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #46: @12 = @1[3:6] */
  for (rr=w12, ss=w1+3; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #47: @11 = (@11*@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) *= (*cs++);
  /* #48: @11 = @11' */
  /* #49: @19 = mac(@16,@11,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w11+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #50: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #51: {@16, @11, @12} = horzsplit(@22) */
  casadi_copy(w22, 3, w16);
  casadi_copy(w22+3, 3, w11);
  casadi_copy(w22+6, 3, w12);
  /* #52: @12 = @12' */
  /* #53: {@13, @14, NULL} = horzsplit(@12) */
  w13 = w12[0];
  w14 = w12[1];
  /* #54: (@8[3] += @14) */
  for (rr=w8+3, ss=(&w14); rr!=w8+4; rr+=1) *rr += *ss++;
  /* #55: @13 = (-@13) */
  w13 = (- w13 );
  /* #56: (@8[4] += @13) */
  for (rr=w8+4, ss=(&w13); rr!=w8+5; rr+=1) *rr += *ss++;
  /* #57: @11 = @11' */
  /* #58: {@13, NULL, @14} = horzsplit(@11) */
  w13 = w11[0];
  w14 = w11[2];
  /* #59: @14 = (-@14) */
  w14 = (- w14 );
  /* #60: (@8[3] += @14) */
  for (rr=w8+3, ss=(&w14); rr!=w8+4; rr+=1) *rr += *ss++;
  /* #61: (@8[4] += @13) */
  for (rr=w8+4, ss=(&w13); rr!=w8+5; rr+=1) *rr += *ss++;
  /* #62: @16 = @16' */
  /* #63: {NULL, @13, @14} = horzsplit(@16) */
  w13 = w16[1];
  w14 = w16[2];
  /* #64: (@8[4] += @14) */
  for (rr=w8+4, ss=(&w14); rr!=w8+5; rr+=1) *rr += *ss++;
  /* #65: @13 = (-@13) */
  w13 = (- w13 );
  /* #66: (@8[5] += @13) */
  for (rr=w8+5, ss=(&w13); rr!=w8+6; rr+=1) *rr += *ss++;
  /* #67: @8 = (@8+@7) */
  for (i=0, rr=w8, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #68: output[1][0] = @8 */
  casadi_copy(w8, 6, res[1]);
  return 0;
}

/* gx:(i0[13])->(o0[13x6]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, *w2=w+43, w3, w4, w5, w6, w7, w8, w9, *w10=w+63, *w11=w+66, *w12=w+69, *w13=w+72, *w14=w+81, *w15=w+90, *w16=w+108, *w17=w+126, *w18=w+162, *w19=w+168, *w20=w+174, *w21=w+192, *w22=w+270;
  /* #0: @0 = zeros(6x7) */
  casadi_clear(w0, 42);
  /* #1: @1 = 1 */
  w1 = 1.;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 13, w2);
  /* #3: @3 = @2[5] */
  for (rr=(&w3), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #4: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #5: @5 = @2[6] */
  for (rr=(&w5), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #6: @6 = sq(@5) */
  w6 = casadi_sq( w5 );
  /* #7: @4 = (@4+@6) */
  w4 += w6;
  /* #8: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #9: @1 = (@1-@4) */
  w1 -= w4;
  /* #10: @4 = @2[4] */
  for (rr=(&w4), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #11: @6 = (@4*@3) */
  w6  = (w4*w3);
  /* #12: @7 = @2[3] */
  for (rr=(&w7), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #13: @8 = (@7*@5) */
  w8  = (w7*w5);
  /* #14: @6 = (@6-@8) */
  w6 -= w8;
  /* #15: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #16: @8 = (@4*@5) */
  w8  = (w4*w5);
  /* #17: @9 = (@7*@3) */
  w9  = (w7*w3);
  /* #18: @8 = (@8+@9) */
  w8 += w9;
  /* #19: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #20: @10 = horzcat(@1, @6, @8) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #21: @10 = @10' */
  /* #22: @1 = (@4*@3) */
  w1  = (w4*w3);
  /* #23: @6 = (@7*@5) */
  w6  = (w7*w5);
  /* #24: @1 = (@1+@6) */
  w1 += w6;
  /* #25: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #26: @6 = 1 */
  w6 = 1.;
  /* #27: @8 = sq(@4) */
  w8 = casadi_sq( w4 );
  /* #28: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #29: @8 = (@8+@9) */
  w8 += w9;
  /* #30: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #31: @6 = (@6-@8) */
  w6 -= w8;
  /* #32: @8 = (@3*@5) */
  w8  = (w3*w5);
  /* #33: @9 = (@7*@4) */
  w9  = (w7*w4);
  /* #34: @8 = (@8-@9) */
  w8 -= w9;
  /* #35: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #36: @11 = horzcat(@1, @6, @8) */
  rr=w11;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #37: @11 = @11' */
  /* #38: @1 = (@4*@5) */
  w1  = (w4*w5);
  /* #39: @6 = (@7*@3) */
  w6  = (w7*w3);
  /* #40: @1 = (@1-@6) */
  w1 -= w6;
  /* #41: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #42: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #43: @7 = (@7*@4) */
  w7 *= w4;
  /* #44: @5 = (@5+@7) */
  w5 += w7;
  /* #45: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #46: @7 = 1 */
  w7 = 1.;
  /* #47: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #48: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #49: @4 = (@4+@3) */
  w4 += w3;
  /* #50: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #51: @7 = (@7-@4) */
  w7 -= w4;
  /* #52: @12 = horzcat(@1, @5, @7) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w5;
  *rr++ = w7;
  /* #53: @12 = @12' */
  /* #54: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #55: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #56: @1 = 13.5 */
  w1 = 1.3500000000000000e+01;
  /* #57: @14 = (@14/@1) */
  for (i=0, rr=w14; i<9; ++i) (*rr++) /= w1;
  /* #58: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #59: @15 = horzcat(@14, @13) */
  rr=w15;
  for (i=0, cs=w14; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<9; ++i) *rr++ = *cs++;
  /* #60: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #61: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #62: @17 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c2, 36, w17);
  /* #63: @18 = [13.5, 13.5, 13.5, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c0, 6, w18);
  /* #64: @18 = sparsity_cast(@18) */
  /* #65: @19 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c1, 6, w19);
  /* #66: @19 = sparsity_cast(@19) */
  /* #67: @18 = (@18+@19) */
  for (i=0, rr=w18, cs=w19; i<6; ++i) (*rr++) += (*cs++);
  /* #68: @17 = (@18\@17) */
  casadi_triusolve(casadi_s0, w18, w17, 0, 0, 6);
  /* #69: @13 = @17[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s1, rr=w13, ss=w17; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #70: @15 = horzcat(@14, @13) */
  rr=w15;
  for (i=0, cs=w14; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<9; ++i) *rr++ = *cs++;
  /* #71: @20 = @15' */
  for (i=0, rr=w20, cs=w15; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #72: @21 = horzcat(@0, @16, @20) */
  rr=w21;
  for (i=0, cs=w0; i<42; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<18; ++i) *rr++ = *cs++;
  /* #73: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<13; ++i) for (j=0; j<6; ++j) rr[i+j*13] = *cs++;
  /* #74: output[0][0] = @22 */
  casadi_copy(w22, 78, res[0]);
  return 0;
}

/* cx:(i0[3],i1[4],i2[3],i3[3])->(o0[13x6,48nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+48;
  /* #0: @0 = zeros(13x6,48nz) */
  casadi_clear(w0, 48);
  /* #1: @1 = ones(6x6,6nz) */
  casadi_fill(w1, 6, 1.);
  /* #2: (@0[7:55:8] = @1) */
  for (rr=w0+7, ss=w1; rr!=w0+55; rr+=8) *rr = *ss++;
  /* #3: output[0][0] = @0 */
  casadi_copy(w0, 48, res[0]);
  return 0;
}

/* adj1_disturbed_dynamics:(i0[13],i1[6],i2[3],i3[3],out_o0[13x1,0nz],adj_o0[13])->(adj_i0[13],adj_i1[6],adj_i2[3],adj_i3[3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+4, *rr, *ss, *tt;
  const casadi_real **arg1=arg+6, *cs;
  casadi_real *w0=w+348, *w2=w+361, *w3=w+439, *w4=w+452, *w5=w+458, *w6=w+471, *w7=w+478, *w8=w+484, *w9=w+487, *w10=w+494, *w11=w+500, *w12=w+578, *w13=w+582, *w14=w+585, *w15=w+588, *w16=w+636;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 13, w0);
  /* #1: @1 = zeros(13x6,0nz) */
  /* #2: @2 = zeros(13x6) */
  casadi_clear(w2, 78);
  /* #3: @3 = input[5][0] */
  casadi_copy(arg[5], 13, w3);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 6, w4);
  /* #5: @4 = @4' */
  /* #6: @2 = mac(@3,@4,@2) */
  for (i=0, rr=w2; i<6; ++i) for (j=0; j<13; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*1; k<1; ++k) *rr += ss[k*13]**tt++;
  /* #7: @5 = adj1_gx(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=0;
  arg1[2]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @6 = @0[:7] */
  for (rr=w6, ss=w0+0; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #9: @4 = @0[7:13] */
  for (rr=w4, ss=w0+7; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #10: {@7, @8} = nu_r_euler(@6, @4) */
  arg1[0]=w6;
  arg1[1]=w4;
  res1[0]=w7;
  res1[1]=w8;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #11: @1 = zeros(13x1,0nz) */
  /* #12: {@9, @10, NULL, NULL} = adj1_fx(@6, @4, @7, @8, @1, @3) */
  arg1[0]=w6;
  arg1[1]=w4;
  arg1[2]=w7;
  arg1[3]=w8;
  arg1[4]=0;
  arg1[5]=w3;
  res1[0]=w9;
  res1[1]=w10;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #13: (@5[7:13] += @10) */
  for (rr=w5+7, ss=w10; rr!=w5+13; rr+=1) *rr += *ss++;
  /* #14: (@5[:7] += @9) */
  for (rr=w5+0, ss=w9; rr!=w5+7; rr+=1) *rr += *ss++;
  /* #15: output[0][0] = @5 */
  casadi_copy(w5, 13, res[0]);
  /* #16: @10 = zeros(6x1) */
  casadi_clear(w10, 6);
  /* #17: @2 = gx(@0) */
  arg1[0]=w0;
  res1[0]=w2;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #18: @11 = @2' */
  for (i=0, rr=w11, cs=w2; i<6; ++i) for (j=0; j<13; ++j) rr[i+j*6] = *cs++;
  /* #19: @10 = mac(@11,@3,@10) */
  for (i=0, rr=w10; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w11+j, tt=w3+i*13; k<13; ++k) *rr += ss[k*6]**tt++;
  /* #20: output[1][0] = @10 */
  casadi_copy(w10, 6, res[1]);
  /* #21: @10 = zeros(6x1) */
  casadi_clear(w10, 6);
  /* #22: @8 = @0[:3] */
  for (rr=w8, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #23: @12 = @0[3:7] */
  for (rr=w12, ss=w0+3; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #24: @13 = @0[7:10] */
  for (rr=w13, ss=w0+7; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #25: @14 = @0[10:13] */
  for (rr=w14, ss=w0+10; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #26: @15 = cx(@8, @12, @13, @14) */
  arg1[0]=w8;
  arg1[1]=w12;
  arg1[2]=w13;
  arg1[3]=w14;
  res1[0]=w15;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #27: @16 = @15' */
  casadi_trans(w15,casadi_s3, w16, casadi_s2, iw);
  /* #28: @10 = mac(@16,@3,@10) */
  casadi_mtimes(w16, casadi_s2, w3, casadi_s5, w10, casadi_s4, w, 0);
  /* #29: {@8, @13} = vertsplit(@10) */
  casadi_copy(w10, 3, w8);
  casadi_copy(w10+3, 3, w13);
  /* #30: output[2][0] = @8 */
  casadi_copy(w8, 3, res[2]);
  /* #31: output[3][0] = @13 */
  casadi_copy(w13, 3, res[3]);
  return 0;
}

/* bluerov_expl_vde_adj:(i0[13],i1[13],i2[6],i3[25])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+684, *w1=w+687, *w2=w+691, *w3=w+694, *w4=w+697, *w5=w+710, *w7=w+716, *w8=w+729, *w9=w+742;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w2);
  /* #3: @3 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w3);
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  /* #5: @5 = input[2][0] */
  casadi_copy(arg[2], 6, w5);
  /* #6: @0 = input[3][2] */
  casadi_copy(arg[3] ? arg[3]+19 : 0, 3, w0);
  /* #7: @2 = input[3][3] */
  casadi_copy(arg[3] ? arg[3]+22 : 0, 3, w2);
  /* #8: @6 = zeros(13x1,0nz) */
  /* #9: @7 = input[1][0] */
  casadi_copy(arg[1], 13, w7);
  /* #10: {@8, @9, NULL, NULL} = adj1_disturbed_dynamics(@4, @5, @0, @2, @6, @7) */
  arg1[0]=w4;
  arg1[1]=w5;
  arg1[2]=w0;
  arg1[3]=w2;
  arg1[4]=0;
  arg1[5]=w7;
  res1[0]=w8;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #11: {@0, @1, @2, @3} = vertsplit(@8) */
  casadi_copy(w8, 3, w0);
  casadi_copy(w8+3, 4, w1);
  casadi_copy(w8+7, 3, w2);
  casadi_copy(w8+10, 3, w3);
  /* #12: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #13: output[0][1] = @1 */
  if (res[0]) casadi_copy(w1, 4, res[0]+3);
  /* #14: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 3, res[0]+7);
  /* #15: output[0][3] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+10);
  /* #16: output[0][4] = @9 */
  if (res[0]) casadi_copy(w9, 6, res[0]+13);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s4;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 748;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 14*sizeof(casadi_int);
  if (sz_w) *sz_w = 748*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
