/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[57] = {13, 6, 0, 8, 16, 24, 32, 40, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 8, 0, 1, 2, 3, 4, 5, 6, 9, 0, 1, 2, 3, 4, 5, 6, 10, 0, 1, 2, 3, 4, 5, 6, 11, 0, 1, 2, 3, 4, 5, 6, 12};
static const casadi_int casadi_s5[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

static const casadi_real casadi_c0[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c1[6] = {1.3500000000000000e+01, 1.3500000000000000e+01, 1.3500000000000000e+01, 2.6000000000000001e-01, 2.3000000000000001e-01, 3.7000000000000000e-01};
static const casadi_real casadi_c2[6] = {6.3600000000000003e+00, 7.1200000000000001e+00, 1.8680000000000000e+01, 1.8900000000000000e-01, 1.3500000000000001e-01, 2.2200000000000000e-01};

/* nu_r_euler:(i0[7],i1[6])->(o0[6],o1[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+6, *w2=w+13, *w3=w+17, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  /* #2: @1 = input[0][0] */
  casadi_copy(arg[0], 7, w1);
  /* #3: @2 = @1[3:7] */
  for (rr=w2, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #4: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #5: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #6: @2 = (@2/@4) */
  for (i=0, rr=w2; i<4; ++i) (*rr++) /= w4;
  /* #7: @4 = @2[0] */
  for (rr=(&w4), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #8: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #9: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #10: @7 = @2[1] */
  for (rr=(&w7), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #11: @8 = @2[2] */
  for (rr=(&w8), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @6 = (@6+@9) */
  w6 += w9;
  /* #14: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #15: @9 = 1 */
  w9 = 1.;
  /* #16: @10 = sq(@8) */
  w10 = casadi_sq( w8 );
  /* #17: @11 = sq(@5) */
  w11 = casadi_sq( w5 );
  /* #18: @10 = (@10+@11) */
  w10 += w11;
  /* #19: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #20: @9 = (@9-@10) */
  w9 -= w10;
  /* #21: @6 = atan2(@6,@9) */
  w6  = atan2(w6,w9);
  /* #22: output[1][0] = @6 */
  if (res[1]) res[1][0] = w6;
  /* #23: @6 = (@4*@8) */
  w6  = (w4*w8);
  /* #24: @9 = (@5*@7) */
  w9  = (w5*w7);
  /* #25: @6 = (@6-@9) */
  w6 -= w9;
  /* #26: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #27: @6 = asin(@6) */
  w6 = asin( w6 );
  /* #28: output[1][1] = @6 */
  if (res[1]) res[1][1] = w6;
  /* #29: @4 = (@4*@7) */
  w4 *= w7;
  /* #30: @5 = (@8*@5) */
  w5  = (w8*w5);
  /* #31: @4 = (@4+@5) */
  w4 += w5;
  /* #32: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #33: @5 = 1 */
  w5 = 1.;
  /* #34: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #35: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #36: @7 = (@7+@8) */
  w7 += w8;
  /* #37: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #38: @5 = (@5-@7) */
  w5 -= w7;
  /* #39: @4 = atan2(@4,@5) */
  w4  = atan2(w4,w5);
  /* #40: output[1][2] = @4 */
  if (res[1]) res[1][2] = w4;
  return 0;
}

/* eta_dynamics:(i0[7],i1[6])->(o0[7]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+6, w2, *w3=w+10, w4, w5, w6, w7, w8, w9, *w10=w+23;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: @1 = @0[:3] */
  for (rr=w1, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #4: @3 = input[0][0] */
  casadi_copy(arg[0], 7, w3);
  /* #5: @4 = @3[4] */
  for (rr=(&w4), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #6: @5 = @0[3] */
  for (rr=(&w5), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #7: @4 = (@4*@5) */
  w4 *= w5;
  /* #8: @4 = (-@4) */
  w4 = (- w4 );
  /* #9: @5 = @3[5] */
  for (rr=(&w5), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #10: @6 = @0[4] */
  for (rr=(&w6), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #11: @5 = (@5*@6) */
  w5 *= w6;
  /* #12: @4 = (@4-@5) */
  w4 -= w5;
  /* #13: @5 = @3[6] */
  for (rr=(&w5), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #14: @6 = @0[5] */
  for (rr=(&w6), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #15: @5 = (@5*@6) */
  w5 *= w6;
  /* #16: @4 = (@4-@5) */
  w4 -= w5;
  /* #17: @5 = @3[3] */
  for (rr=(&w5), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #18: @6 = @0[3] */
  for (rr=(&w6), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #19: @5 = (@5*@6) */
  w5 *= w6;
  /* #20: @6 = @3[5] */
  for (rr=(&w6), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #21: @7 = @0[5] */
  for (rr=(&w7), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #22: @6 = (@6*@7) */
  w6 *= w7;
  /* #23: @5 = (@5+@6) */
  w5 += w6;
  /* #24: @6 = @3[6] */
  for (rr=(&w6), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #25: @7 = @0[4] */
  for (rr=(&w7), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #26: @6 = (@6*@7) */
  w6 *= w7;
  /* #27: @5 = (@5-@6) */
  w5 -= w6;
  /* #28: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #29: @7 = @0[4] */
  for (rr=(&w7), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #30: @6 = (@6*@7) */
  w6 *= w7;
  /* #31: @7 = @3[4] */
  for (rr=(&w7), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #32: @8 = @0[5] */
  for (rr=(&w8), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #33: @7 = (@7*@8) */
  w7 *= w8;
  /* #34: @6 = (@6-@7) */
  w6 -= w7;
  /* #35: @7 = @3[6] */
  for (rr=(&w7), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #36: @8 = @0[3] */
  for (rr=(&w8), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #37: @7 = (@7*@8) */
  w7 *= w8;
  /* #38: @6 = (@6+@7) */
  w6 += w7;
  /* #39: @7 = @3[3] */
  for (rr=(&w7), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #40: @8 = @0[5] */
  for (rr=(&w8), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #41: @7 = (@7*@8) */
  w7 *= w8;
  /* #42: @8 = @3[4] */
  for (rr=(&w8), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #43: @9 = @0[4] */
  for (rr=(&w9), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #44: @8 = (@8*@9) */
  w8 *= w9;
  /* #45: @7 = (@7+@8) */
  w7 += w8;
  /* #46: @8 = @3[5] */
  for (rr=(&w8), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #47: @9 = @0[3] */
  for (rr=(&w9), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #48: @8 = (@8*@9) */
  w8 *= w9;
  /* #49: @7 = (@7-@8) */
  w7 -= w8;
  /* #50: @10 = vertcat(@4, @5, @6, @7) */
  rr=w10;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #51: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #52: output[0][1] = @10 */
  if (res[0]) casadi_copy(w10, 4, res[0]+3);
  return 0;
}

/* fx:(i0[7],i1[6],i2[6],i3[3])->(o0[13]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+27, *w1=w+34, *w2=w+40, *w3=w+47, *w4=w+50, *w5=w+86, *w6=w+92, *w7=w+98, *w8=w+107, w9, w10, w11, *w12=w+113, *w13=w+116, *w14=w+119, *w15=w+122, *w16=w+131;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = eta_dynamics(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 7, res[0]);
  /* #4: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #5: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+7);
  /* #6: @3 = zeros(3x1) */
  casadi_clear(w3, 3);
  /* #7: @4 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w4);
  /* #8: @5 = [13.5, 13.5, 13.5, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w5);
  /* #9: @5 = sparsity_cast(@5) */
  /* #10: @6 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w6);
  /* #11: @6 = sparsity_cast(@6) */
  /* #12: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<6; ++i) (*rr++) += (*cs++);
  /* #13: @4 = (@5\@4) */
  casadi_triusolve(casadi_s0, w5, w4, 0, 0, 6);
  /* #14: @7 = @4[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s1, rr=w7, ss=w4; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #15: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) *rr++ = (- *cs++ );
  /* #16: @8 = zeros(3x1) */
  casadi_clear(w8, 3);
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @10 = @1[5] */
  for (rr=(&w10), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #19: @10 = (-@10) */
  w10 = (- w10 );
  /* #20: @11 = @1[4] */
  for (rr=(&w11), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #21: @12 = horzcat(@9, @10, @11) */
  rr=w12;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #22: @12 = @12' */
  /* #23: @9 = @1[4] */
  for (rr=(&w9), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #24: @10 = 0 */
  w10 = 0.;
  /* #25: @11 = @1[3] */
  for (rr=(&w11), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #26: @11 = (-@11) */
  w11 = (- w11 );
  /* #27: @13 = horzcat(@9, @10, @11) */
  rr=w13;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #28: @13 = @13' */
  /* #29: @9 = @1[4] */
  for (rr=(&w9), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #30: @9 = (-@9) */
  w9 = (- w9 );
  /* #31: @10 = @1[3] */
  for (rr=(&w10), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #32: @11 = 0 */
  w11 = 0.;
  /* #33: @14 = horzcat(@9, @10, @11) */
  rr=w14;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #34: @14 = @14' */
  /* #35: @15 = horzcat(@12, @13, @14) */
  rr=w15;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #36: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #37: @12 = @5[3:6] */
  for (rr=w12, ss=w5+3; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #38: @12 = nonzeros(@12) */
  /* #39: @13 = @1[3:6] */
  for (rr=w13, ss=w1+3; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #40: @12 = (@12*@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) *= (*cs++);
  /* #41: @8 = mac(@16,@12,@8) */
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #42: @3 = mac(@7,@8,@3) */
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #43: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+10);
  return 0;
}

/* gx:(i0[13])->(o0[13x6]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, *w2=w+43, w3, w4, w5, w6, w7, w8, w9, *w10=w+63, *w11=w+66, *w12=w+69, *w13=w+72, *w14=w+81, *w15=w+90, *w16=w+108, *w17=w+126, *w18=w+162, *w19=w+168, *w20=w+174, *w21=w+192, *w22=w+270;
  /* #0: @0 = zeros(6x7) */
  casadi_clear(w0, 42);
  /* #1: @1 = 1 */
  w1 = 1.;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 13, w2);
  /* #3: @3 = @2[5] */
  for (rr=(&w3), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #4: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #5: @5 = @2[6] */
  for (rr=(&w5), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #6: @6 = sq(@5) */
  w6 = casadi_sq( w5 );
  /* #7: @4 = (@4+@6) */
  w4 += w6;
  /* #8: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #9: @1 = (@1-@4) */
  w1 -= w4;
  /* #10: @4 = @2[4] */
  for (rr=(&w4), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #11: @6 = (@4*@3) */
  w6  = (w4*w3);
  /* #12: @7 = @2[3] */
  for (rr=(&w7), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #13: @8 = (@7*@5) */
  w8  = (w7*w5);
  /* #14: @6 = (@6-@8) */
  w6 -= w8;
  /* #15: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #16: @8 = (@4*@5) */
  w8  = (w4*w5);
  /* #17: @9 = (@7*@3) */
  w9  = (w7*w3);
  /* #18: @8 = (@8+@9) */
  w8 += w9;
  /* #19: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #20: @10 = horzcat(@1, @6, @8) */
  rr=w10;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #21: @10 = @10' */
  /* #22: @1 = (@4*@3) */
  w1  = (w4*w3);
  /* #23: @6 = (@7*@5) */
  w6  = (w7*w5);
  /* #24: @1 = (@1+@6) */
  w1 += w6;
  /* #25: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #26: @6 = 1 */
  w6 = 1.;
  /* #27: @8 = sq(@4) */
  w8 = casadi_sq( w4 );
  /* #28: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #29: @8 = (@8+@9) */
  w8 += w9;
  /* #30: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #31: @6 = (@6-@8) */
  w6 -= w8;
  /* #32: @8 = (@3*@5) */
  w8  = (w3*w5);
  /* #33: @9 = (@7*@4) */
  w9  = (w7*w4);
  /* #34: @8 = (@8-@9) */
  w8 -= w9;
  /* #35: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #36: @11 = horzcat(@1, @6, @8) */
  rr=w11;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #37: @11 = @11' */
  /* #38: @1 = (@4*@5) */
  w1  = (w4*w5);
  /* #39: @6 = (@7*@3) */
  w6  = (w7*w3);
  /* #40: @1 = (@1-@6) */
  w1 -= w6;
  /* #41: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #42: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #43: @7 = (@7*@4) */
  w7 *= w4;
  /* #44: @5 = (@5+@7) */
  w5 += w7;
  /* #45: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #46: @7 = 1 */
  w7 = 1.;
  /* #47: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #48: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #49: @4 = (@4+@3) */
  w4 += w3;
  /* #50: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #51: @7 = (@7-@4) */
  w7 -= w4;
  /* #52: @12 = horzcat(@1, @5, @7) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w5;
  *rr++ = w7;
  /* #53: @12 = @12' */
  /* #54: @13 = horzcat(@10, @11, @12) */
  rr=w13;
  for (i=0, cs=w10; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  /* #55: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #56: @1 = 13.5 */
  w1 = 1.3500000000000000e+01;
  /* #57: @14 = (@14/@1) */
  for (i=0, rr=w14; i<9; ++i) (*rr++) /= w1;
  /* #58: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #59: @15 = horzcat(@14, @13) */
  rr=w15;
  for (i=0, cs=w14; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<9; ++i) *rr++ = *cs++;
  /* #60: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #61: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #62: @17 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w17);
  /* #63: @18 = [13.5, 13.5, 13.5, 0.26, 0.23, 0.37] */
  casadi_copy(casadi_c1, 6, w18);
  /* #64: @18 = sparsity_cast(@18) */
  /* #65: @19 = [6.36, 7.12, 18.68, 0.189, 0.135, 0.222] */
  casadi_copy(casadi_c2, 6, w19);
  /* #66: @19 = sparsity_cast(@19) */
  /* #67: @18 = (@18+@19) */
  for (i=0, rr=w18, cs=w19; i<6; ++i) (*rr++) += (*cs++);
  /* #68: @17 = (@18\@17) */
  casadi_triusolve(casadi_s0, w18, w17, 0, 0, 6);
  /* #69: @13 = @17[21, 22, 23, 27, 28, 29, 33, 34, 35] */
  for (cii=casadi_s1, rr=w13, ss=w17; cii!=casadi_s1+9; ++cii) *rr++ = ss[*cii];
  /* #70: @15 = horzcat(@14, @13) */
  rr=w15;
  for (i=0, cs=w14; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<9; ++i) *rr++ = *cs++;
  /* #71: @20 = @15' */
  for (i=0, rr=w20, cs=w15; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #72: @21 = horzcat(@0, @16, @20) */
  rr=w21;
  for (i=0, cs=w0; i<42; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<18; ++i) *rr++ = *cs++;
  /* #73: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<13; ++i) for (j=0; j<6; ++j) rr[i+j*13] = *cs++;
  /* #74: output[0][0] = @22 */
  casadi_copy(w22, 78, res[0]);
  return 0;
}

/* cx:(i0[3],i1[4],i2[3],i3[3])->(o0[13x6,48nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+48;
  /* #0: @0 = zeros(13x6,48nz) */
  casadi_clear(w0, 48);
  /* #1: @1 = ones(6x6,6nz) */
  casadi_fill(w1, 6, 1.);
  /* #2: (@0[7:55:8] = @1) */
  for (rr=w0+7, ss=w1; rr!=w0+55; rr+=8) *rr = *ss++;
  /* #3: output[0][0] = @0 */
  casadi_copy(w0, 48, res[0]);
  return 0;
}

/* disturbed_dynamics:(i0[13],i1[6],i2[3],i3[3])->(o0[13]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cs;
  casadi_real *w0=w+348, *w1=w+361, *w2=w+368, *w3=w+374, *w4=w+380, *w5=w+383, *w6=w+396, *w7=w+409, *w8=w+487, *w9=w+491, *w10=w+494, *w11=w+497;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 13, w0);
  /* #1: @1 = @0[:7] */
  for (rr=w1, ss=w0+0; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[7:13] */
  for (rr=w2, ss=w0+7; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #3: {@3, @4} = nu_r_euler(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  res1[1]=w4;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #4: @5 = fx(@1, @2, @3, @4) */
  arg1[0]=w1;
  arg1[1]=w2;
  arg1[2]=w3;
  arg1[3]=w4;
  res1[0]=w5;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #5: @6 = zeros(13x1) */
  casadi_clear(w6, 13);
  /* #6: @7 = gx(@0) */
  arg1[0]=w0;
  res1[0]=w7;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #7: @2 = input[1][0] */
  casadi_copy(arg[1], 6, w2);
  /* #8: @6 = mac(@7,@2,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<13; ++j, ++rr) for (k=0, ss=w7+j, tt=w2+i*6; k<6; ++k) *rr += ss[k*13]**tt++;
  /* #9: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<13; ++i) (*rr++) += (*cs++);
  /* #10: @6 = zeros(13x1) */
  casadi_clear(w6, 13);
  /* #11: @4 = @0[:3] */
  for (rr=w4, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #12: @8 = @0[3:7] */
  for (rr=w8, ss=w0+3; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #13: @9 = @0[7:10] */
  for (rr=w9, ss=w0+7; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #14: @10 = @0[10:13] */
  for (rr=w10, ss=w0+10; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #15: @11 = cx(@4, @8, @9, @10) */
  arg1[0]=w4;
  arg1[1]=w8;
  arg1[2]=w9;
  arg1[3]=w10;
  res1[0]=w11;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #16: @4 = input[2][0] */
  casadi_copy(arg[2], 3, w4);
  /* #17: @9 = input[3][0] */
  casadi_copy(arg[3], 3, w9);
  /* #18: @2 = vertcat(@4, @9) */
  rr=w2;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  /* #19: @6 = mac(@11,@2,@6) */
  casadi_mtimes(w11, casadi_s4, w2, casadi_s3, w6, casadi_s2, w, 0);
  /* #20: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<13; ++i) (*rr++) += (*cs++);
  /* #21: output[0][0] = @5 */
  casadi_copy(w5, 13, res[0]);
  return 0;
}

/* bluerov_expl_ode_fun:(i0[13],i1[6],i2[25])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real *w0=w+545, *w1=w+548, *w2=w+552, *w3=w+555, *w4=w+558, *w5=w+571, *w6=w+577;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w2);
  /* #3: @3 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w3);
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  /* #5: @5 = input[1][0] */
  casadi_copy(arg[1], 6, w5);
  /* #6: @0 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+19 : 0, 3, w0);
  /* #7: @2 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+22 : 0, 3, w2);
  /* #8: @6 = disturbed_dynamics(@4, @5, @0, @2) */
  arg1[0]=w4;
  arg1[1]=w5;
  arg1[2]=w0;
  arg1[3]=w2;
  res1[0]=w6;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #9: output[0][0] = @6 */
  casadi_copy(w6, 13, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 590;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 590*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
