/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sparsify CASADI_PREFIX(sparsify)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[19] = {0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s5[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s10[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s11[53] = {19, 19, 0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 6, 7, 8, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s12[3] = {19, 0, 0};

/* bluerov_cost_y_0_fun_jac_ut_xt:(i0[13],i1[6],i2[0],i3[],i4[25])->(o0[19],o1[19x19,31nz],o2[19x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+16, w3, *w4=w+20, w5, w6, w7, w8, *w9=w+28, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+40, *w19=w+44, *w20=w+50, *w21=w+56, *w22=w+87, *w23=w+103, *w25=w+106, w26, *w27=w+111;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @3 = @1[3] */
  for (rr=(&w3), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w4);
  /* #7: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #8: @6 = @4[1] */
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #9: @6 = (-@6) */
  w6 = (- w6 );
  /* #10: @7 = @4[2] */
  for (rr=(&w7), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (-@7) */
  w7 = (- w7 );
  /* #12: @8 = @4[3] */
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #13: @8 = (-@8) */
  w8 = (- w8 );
  /* #14: @9 = vertcat(@5, @6, @7, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #15: @5 = ||@4||_F */
  w5 = sqrt(casadi_dot(4, w4, w4));
  /* #16: @9 = (@9/@5) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w5;
  /* #17: @6 = @9[0] */
  for (rr=(&w6), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #18: @7 = (@3*@6) */
  w7  = (w3*w6);
  /* #19: @8 = @1[4] */
  for (rr=(&w8), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #20: @10 = @9[1] */
  for (rr=(&w10), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #21: @11 = (@8*@10) */
  w11  = (w8*w10);
  /* #22: @7 = (@7-@11) */
  w7 -= w11;
  /* #23: @11 = @1[5] */
  for (rr=(&w11), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #24: @12 = @9[2] */
  for (rr=(&w12), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #25: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #26: @7 = (@7-@13) */
  w7 -= w13;
  /* #27: @13 = @1[6] */
  for (rr=(&w13), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #28: @14 = @9[3] */
  for (rr=(&w14), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #29: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #30: @7 = (@7-@15) */
  w7 -= w15;
  /* #31: @15 = (@3*@10) */
  w15  = (w3*w10);
  /* #32: @16 = (@8*@6) */
  w16  = (w8*w6);
  /* #33: @15 = (@15+@16) */
  w15 += w16;
  /* #34: @16 = (@11*@14) */
  w16  = (w11*w14);
  /* #35: @15 = (@15+@16) */
  w15 += w16;
  /* #36: @16 = (@13*@12) */
  w16  = (w13*w12);
  /* #37: @15 = (@15-@16) */
  w15 -= w16;
  /* #38: @16 = (@3*@12) */
  w16  = (w3*w12);
  /* #39: @17 = (@8*@14) */
  w17  = (w8*w14);
  /* #40: @16 = (@16-@17) */
  w16 -= w17;
  /* #41: @17 = (@11*@6) */
  w17  = (w11*w6);
  /* #42: @16 = (@16+@17) */
  w16 += w17;
  /* #43: @17 = (@13*@10) */
  w17  = (w13*w10);
  /* #44: @16 = (@16+@17) */
  w16 += w17;
  /* #45: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #46: @12 = (@8*@12) */
  w12  = (w8*w12);
  /* #47: @14 = (@14+@12) */
  w14 += w12;
  /* #48: @10 = (@11*@10) */
  w10  = (w11*w10);
  /* #49: @14 = (@14-@10) */
  w14 -= w10;
  /* #50: @6 = (@13*@6) */
  w6  = (w13*w6);
  /* #51: @14 = (@14+@6) */
  w14 += w6;
  /* #52: @18 = vertcat(@7, @15, @16, @14) */
  rr=w18;
  *rr++ = w7;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w14;
  /* #53: @7 = sign(@7) */
  w7 = casadi_sign( w7 );
  /* #54: @18 = (@18*@7) */
  for (i=0, rr=w18; i<4; ++i) (*rr++) *= w7;
  /* #55: output[0][1] = @18 */
  if (res[0]) casadi_copy(w18, 4, res[0]+3);
  /* #56: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #57: @2 = @1[7:10] */
  for (rr=w2, ss=w1+7; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #58: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #59: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #60: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #61: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #62: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #63: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+10);
  /* #64: @19 = input[1][0] */
  casadi_copy(arg[1], 6, w19);
  /* #65: @20 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+13 : 0, 6, w20);
  /* #66: @19 = (@19-@20) */
  for (i=0, rr=w19, cs=w20; i<6; ++i) (*rr++) -= (*cs++);
  /* #67: output[0][4] = @19 */
  if (res[0]) casadi_copy(w19, 6, res[0]+13);
  /* #68: @21 = zeros(19x19,31nz) */
  casadi_clear(w21, 31);
  /* #69: @22 = ones(19x1,16nz) */
  casadi_fill(w22, 16, 1.);
  /* #70: {@19, @0, @15, @2, @23} = vertsplit(@22) */
  casadi_copy(w22, 6, w19);
  casadi_copy(w22+6, 3, w0);
  w15 = w22[9];
  casadi_copy(w22+10, 3, w2);
  casadi_copy(w22+13, 3, w23);
  /* #71: @16 = @15[0] */
  for (rr=(&w16), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #72: @24 = 00 */
  /* #73: @14 = vertcat(@16, @24, @24, @24) */
  rr=(&w14);
  *rr++ = w16;
  /* #74: @14 = (@14/@5) */
  w14 /= w5;
  /* #75: @18 = dense(@14) */
  casadi_densify((&w14), casadi_s0, w18, 0);
  /* #76: @9 = (@9/@5) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w5;
  /* #77: @14 = project(@4) */
  casadi_sparsify(w4, (&w14), casadi_s0, 0);
  /* #78: @16 = dot(@14, @15) */
  w16 = casadi_dot(1, (&w14), (&w15));
  /* #79: @16 = (@16/@5) */
  w16 /= w5;
  /* #80: @25 = (@9*@16) */
  for (i=0, rr=w25, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #81: @18 = (@18-@25) */
  for (i=0, rr=w18, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #82: @16 = @18[0] */
  for (rr=(&w16), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #83: @14 = (@3*@16) */
  w14  = (w3*w16);
  /* #84: @15 = @18[1] */
  for (rr=(&w15), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #85: @6 = (@8*@15) */
  w6  = (w8*w15);
  /* #86: @14 = (@14-@6) */
  w14 -= w6;
  /* #87: @6 = @18[2] */
  for (rr=(&w6), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #88: @10 = (@11*@6) */
  w10  = (w11*w6);
  /* #89: @14 = (@14-@10) */
  w14 -= w10;
  /* #90: @10 = @18[3] */
  for (rr=(&w10), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #91: @12 = (@13*@10) */
  w12  = (w13*w10);
  /* #92: @14 = (@14-@12) */
  w14 -= w12;
  /* #93: @12 = (@3*@15) */
  w12  = (w3*w15);
  /* #94: @17 = (@8*@16) */
  w17  = (w8*w16);
  /* #95: @12 = (@12+@17) */
  w12 += w17;
  /* #96: @17 = (@11*@10) */
  w17  = (w11*w10);
  /* #97: @12 = (@12+@17) */
  w12 += w17;
  /* #98: @17 = (@13*@6) */
  w17  = (w13*w6);
  /* #99: @12 = (@12-@17) */
  w12 -= w17;
  /* #100: @17 = (@3*@6) */
  w17  = (w3*w6);
  /* #101: @26 = (@8*@10) */
  w26  = (w8*w10);
  /* #102: @17 = (@17-@26) */
  w17 -= w26;
  /* #103: @26 = (@11*@16) */
  w26  = (w11*w16);
  /* #104: @17 = (@17+@26) */
  w17 += w26;
  /* #105: @26 = (@13*@15) */
  w26  = (w13*w15);
  /* #106: @17 = (@17+@26) */
  w17 += w26;
  /* #107: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #108: @6 = (@8*@6) */
  w6  = (w8*w6);
  /* #109: @10 = (@10+@6) */
  w10 += w6;
  /* #110: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #111: @10 = (@10-@15) */
  w10 -= w15;
  /* #112: @16 = (@13*@16) */
  w16  = (w13*w16);
  /* #113: @10 = (@10+@16) */
  w10 += w16;
  /* #114: @18 = vertcat(@14, @12, @17, @10) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w10;
  /* #115: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #116: @27 = vertcat(@0, @18, @2, @23, @19) */
  rr=w27;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  /* #117: (@21[0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] = @27) */
  for (cii=casadi_s1, rr=w21, ss=w27; cii!=casadi_s1+19; ++cii, ++ss) rr[*cii] = *ss;
  /* #118: @14 = ones(19x1,1nz) */
  w14 = 1.;
  /* #119: {NULL, NULL, @12, NULL, NULL} = vertsplit(@14) */
  w12 = w14;
  /* #120: @14 = @12[0] */
  for (rr=(&w14), ss=(&w12)+0; ss!=(&w12)+1; ss+=1) *rr++ = *ss;
  /* #121: @14 = (-@14) */
  w14 = (- w14 );
  /* #122: @17 = vertcat(@24, @14, @24, @24) */
  rr=(&w17);
  *rr++ = w14;
  /* #123: @17 = (@17/@5) */
  w17 /= w5;
  /* #124: @18 = dense(@17) */
  casadi_densify((&w17), casadi_s2, w18, 0);
  /* #125: @17 = project(@4) */
  casadi_sparsify(w4, (&w17), casadi_s2, 0);
  /* #126: @14 = dot(@17, @12) */
  w14 = casadi_dot(1, (&w17), (&w12));
  /* #127: @14 = (@14/@5) */
  w14 /= w5;
  /* #128: @25 = (@9*@14) */
  for (i=0, rr=w25, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w14);
  /* #129: @18 = (@18-@25) */
  for (i=0, rr=w18, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #130: @14 = @18[0] */
  for (rr=(&w14), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #131: @17 = (@3*@14) */
  w17  = (w3*w14);
  /* #132: @12 = @18[1] */
  for (rr=(&w12), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #133: @10 = (@8*@12) */
  w10  = (w8*w12);
  /* #134: @17 = (@17-@10) */
  w17 -= w10;
  /* #135: @10 = @18[2] */
  for (rr=(&w10), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #136: @16 = (@11*@10) */
  w16  = (w11*w10);
  /* #137: @17 = (@17-@16) */
  w17 -= w16;
  /* #138: @16 = @18[3] */
  for (rr=(&w16), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #139: @15 = (@13*@16) */
  w15  = (w13*w16);
  /* #140: @17 = (@17-@15) */
  w17 -= w15;
  /* #141: @15 = (@3*@12) */
  w15  = (w3*w12);
  /* #142: @6 = (@8*@14) */
  w6  = (w8*w14);
  /* #143: @15 = (@15+@6) */
  w15 += w6;
  /* #144: @6 = (@11*@16) */
  w6  = (w11*w16);
  /* #145: @15 = (@15+@6) */
  w15 += w6;
  /* #146: @6 = (@13*@10) */
  w6  = (w13*w10);
  /* #147: @15 = (@15-@6) */
  w15 -= w6;
  /* #148: @6 = (@3*@10) */
  w6  = (w3*w10);
  /* #149: @26 = (@8*@16) */
  w26  = (w8*w16);
  /* #150: @6 = (@6-@26) */
  w6 -= w26;
  /* #151: @26 = (@11*@14) */
  w26  = (w11*w14);
  /* #152: @6 = (@6+@26) */
  w6 += w26;
  /* #153: @26 = (@13*@12) */
  w26  = (w13*w12);
  /* #154: @6 = (@6+@26) */
  w6 += w26;
  /* #155: @16 = (@3*@16) */
  w16  = (w3*w16);
  /* #156: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #157: @16 = (@16+@10) */
  w16 += w10;
  /* #158: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #159: @16 = (@16-@12) */
  w16 -= w12;
  /* #160: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #161: @16 = (@16+@14) */
  w16 += w14;
  /* #162: @18 = vertcat(@17, @15, @6, @16) */
  rr=w18;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w6;
  *rr++ = w16;
  /* #163: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #164: (@21[4:20:4] = @18) */
  for (rr=w21+4, ss=w18; rr!=w21+20; rr+=4) *rr = *ss++;
  /* #165: @17 = ones(19x1,1nz) */
  w17 = 1.;
  /* #166: {NULL, NULL, @15, NULL, NULL} = vertsplit(@17) */
  w15 = w17;
  /* #167: @17 = @15[0] */
  for (rr=(&w17), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #168: @17 = (-@17) */
  w17 = (- w17 );
  /* #169: @6 = vertcat(@24, @24, @17, @24) */
  rr=(&w6);
  *rr++ = w17;
  /* #170: @6 = (@6/@5) */
  w6 /= w5;
  /* #171: @18 = dense(@6) */
  casadi_densify((&w6), casadi_s3, w18, 0);
  /* #172: @6 = project(@4) */
  casadi_sparsify(w4, (&w6), casadi_s3, 0);
  /* #173: @17 = dot(@6, @15) */
  w17 = casadi_dot(1, (&w6), (&w15));
  /* #174: @17 = (@17/@5) */
  w17 /= w5;
  /* #175: @25 = (@9*@17) */
  for (i=0, rr=w25, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #176: @18 = (@18-@25) */
  for (i=0, rr=w18, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #177: @17 = @18[0] */
  for (rr=(&w17), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #178: @6 = (@3*@17) */
  w6  = (w3*w17);
  /* #179: @15 = @18[1] */
  for (rr=(&w15), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #180: @16 = (@8*@15) */
  w16  = (w8*w15);
  /* #181: @6 = (@6-@16) */
  w6 -= w16;
  /* #182: @16 = @18[2] */
  for (rr=(&w16), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #183: @14 = (@11*@16) */
  w14  = (w11*w16);
  /* #184: @6 = (@6-@14) */
  w6 -= w14;
  /* #185: @14 = @18[3] */
  for (rr=(&w14), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #186: @12 = (@13*@14) */
  w12  = (w13*w14);
  /* #187: @6 = (@6-@12) */
  w6 -= w12;
  /* #188: @12 = (@3*@15) */
  w12  = (w3*w15);
  /* #189: @10 = (@8*@17) */
  w10  = (w8*w17);
  /* #190: @12 = (@12+@10) */
  w12 += w10;
  /* #191: @10 = (@11*@14) */
  w10  = (w11*w14);
  /* #192: @12 = (@12+@10) */
  w12 += w10;
  /* #193: @10 = (@13*@16) */
  w10  = (w13*w16);
  /* #194: @12 = (@12-@10) */
  w12 -= w10;
  /* #195: @10 = (@3*@16) */
  w10  = (w3*w16);
  /* #196: @26 = (@8*@14) */
  w26  = (w8*w14);
  /* #197: @10 = (@10-@26) */
  w10 -= w26;
  /* #198: @26 = (@11*@17) */
  w26  = (w11*w17);
  /* #199: @10 = (@10+@26) */
  w10 += w26;
  /* #200: @26 = (@13*@15) */
  w26  = (w13*w15);
  /* #201: @10 = (@10+@26) */
  w10 += w26;
  /* #202: @14 = (@3*@14) */
  w14  = (w3*w14);
  /* #203: @16 = (@8*@16) */
  w16  = (w8*w16);
  /* #204: @14 = (@14+@16) */
  w14 += w16;
  /* #205: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #206: @14 = (@14-@15) */
  w14 -= w15;
  /* #207: @17 = (@13*@17) */
  w17  = (w13*w17);
  /* #208: @14 = (@14+@17) */
  w14 += w17;
  /* #209: @18 = vertcat(@6, @12, @10, @14) */
  rr=w18;
  *rr++ = w6;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w14;
  /* #210: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #211: (@21[5:21:4] = @18) */
  for (rr=w21+5, ss=w18; rr!=w21+21; rr+=4) *rr = *ss++;
  /* #212: @6 = ones(19x1,1nz) */
  w6 = 1.;
  /* #213: {NULL, NULL, @12, NULL, NULL} = vertsplit(@6) */
  w12 = w6;
  /* #214: @6 = @12[0] */
  for (rr=(&w6), ss=(&w12)+0; ss!=(&w12)+1; ss+=1) *rr++ = *ss;
  /* #215: @6 = (-@6) */
  w6 = (- w6 );
  /* #216: @10 = vertcat(@24, @24, @24, @6) */
  rr=(&w10);
  *rr++ = w6;
  /* #217: @10 = (@10/@5) */
  w10 /= w5;
  /* #218: @18 = dense(@10) */
  casadi_densify((&w10), casadi_s4, w18, 0);
  /* #219: @10 = project(@4) */
  casadi_sparsify(w4, (&w10), casadi_s4, 0);
  /* #220: @6 = dot(@10, @12) */
  w6 = casadi_dot(1, (&w10), (&w12));
  /* #221: @6 = (@6/@5) */
  w6 /= w5;
  /* #222: @9 = (@9*@6) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) *= w6;
  /* #223: @18 = (@18-@9) */
  for (i=0, rr=w18, cs=w9; i<4; ++i) (*rr++) -= (*cs++);
  /* #224: @6 = @18[0] */
  for (rr=(&w6), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #225: @5 = (@3*@6) */
  w5  = (w3*w6);
  /* #226: @10 = @18[1] */
  for (rr=(&w10), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #227: @12 = (@8*@10) */
  w12  = (w8*w10);
  /* #228: @5 = (@5-@12) */
  w5 -= w12;
  /* #229: @12 = @18[2] */
  for (rr=(&w12), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #230: @14 = (@11*@12) */
  w14  = (w11*w12);
  /* #231: @5 = (@5-@14) */
  w5 -= w14;
  /* #232: @14 = @18[3] */
  for (rr=(&w14), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #233: @17 = (@13*@14) */
  w17  = (w13*w14);
  /* #234: @5 = (@5-@17) */
  w5 -= w17;
  /* #235: @17 = (@3*@10) */
  w17  = (w3*w10);
  /* #236: @15 = (@8*@6) */
  w15  = (w8*w6);
  /* #237: @17 = (@17+@15) */
  w17 += w15;
  /* #238: @15 = (@11*@14) */
  w15  = (w11*w14);
  /* #239: @17 = (@17+@15) */
  w17 += w15;
  /* #240: @15 = (@13*@12) */
  w15  = (w13*w12);
  /* #241: @17 = (@17-@15) */
  w17 -= w15;
  /* #242: @15 = (@3*@12) */
  w15  = (w3*w12);
  /* #243: @16 = (@8*@14) */
  w16  = (w8*w14);
  /* #244: @15 = (@15-@16) */
  w15 -= w16;
  /* #245: @16 = (@11*@6) */
  w16  = (w11*w6);
  /* #246: @15 = (@15+@16) */
  w15 += w16;
  /* #247: @16 = (@13*@10) */
  w16  = (w13*w10);
  /* #248: @15 = (@15+@16) */
  w15 += w16;
  /* #249: @3 = (@3*@14) */
  w3 *= w14;
  /* #250: @8 = (@8*@12) */
  w8 *= w12;
  /* #251: @3 = (@3+@8) */
  w3 += w8;
  /* #252: @11 = (@11*@10) */
  w11 *= w10;
  /* #253: @3 = (@3-@11) */
  w3 -= w11;
  /* #254: @13 = (@13*@6) */
  w13 *= w6;
  /* #255: @3 = (@3+@13) */
  w3 += w13;
  /* #256: @18 = vertcat(@5, @17, @15, @3) */
  rr=w18;
  *rr++ = w5;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w3;
  /* #257: @18 = (@7*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w7*(*cs++));
  /* #258: (@21[6:22:4] = @18) */
  for (rr=w21+6, ss=w18; rr!=w21+22; rr+=4) *rr = *ss++;
  /* #259: output[1][0] = @21 */
  casadi_copy(w21, 31, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 130;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 130*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
