/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s5[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};

/* bluerov_cost_y_0_fun:(i0[13],i1[6],i2[0],i3[],i4[25])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+16, w3, *w4=w+20, w5, w6, w7, w8, *w9=w+28, w10, w11, w12, w13, w14, w15, w16, *w17=w+39, *w18=w+45;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @3 = @1[3] */
  for (rr=(&w3), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #6: @4 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w4);
  /* #7: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #8: @6 = @4[1] */
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #9: @6 = (-@6) */
  w6 = (- w6 );
  /* #10: @7 = @4[2] */
  for (rr=(&w7), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #11: @7 = (-@7) */
  w7 = (- w7 );
  /* #12: @8 = @4[3] */
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #13: @8 = (-@8) */
  w8 = (- w8 );
  /* #14: @9 = vertcat(@5, @6, @7, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #15: @5 = ||@4||_F */
  w5 = sqrt(casadi_dot(4, w4, w4));
  /* #16: @9 = (@9/@5) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w5;
  /* #17: @5 = @9[0] */
  for (rr=(&w5), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #18: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #19: @7 = @1[4] */
  for (rr=(&w7), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #20: @8 = @9[1] */
  for (rr=(&w8), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #21: @10 = (@7*@8) */
  w10  = (w7*w8);
  /* #22: @6 = (@6-@10) */
  w6 -= w10;
  /* #23: @10 = @1[5] */
  for (rr=(&w10), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #24: @11 = @9[2] */
  for (rr=(&w11), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #25: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #26: @6 = (@6-@12) */
  w6 -= w12;
  /* #27: @12 = @1[6] */
  for (rr=(&w12), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #28: @13 = @9[3] */
  for (rr=(&w13), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #29: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #30: @6 = (@6-@14) */
  w6 -= w14;
  /* #31: @14 = (@3*@8) */
  w14  = (w3*w8);
  /* #32: @15 = (@7*@5) */
  w15  = (w7*w5);
  /* #33: @14 = (@14+@15) */
  w14 += w15;
  /* #34: @15 = (@10*@13) */
  w15  = (w10*w13);
  /* #35: @14 = (@14+@15) */
  w14 += w15;
  /* #36: @15 = (@12*@11) */
  w15  = (w12*w11);
  /* #37: @14 = (@14-@15) */
  w14 -= w15;
  /* #38: @15 = (@3*@11) */
  w15  = (w3*w11);
  /* #39: @16 = (@7*@13) */
  w16  = (w7*w13);
  /* #40: @15 = (@15-@16) */
  w15 -= w16;
  /* #41: @16 = (@10*@5) */
  w16  = (w10*w5);
  /* #42: @15 = (@15+@16) */
  w15 += w16;
  /* #43: @16 = (@12*@8) */
  w16  = (w12*w8);
  /* #44: @15 = (@15+@16) */
  w15 += w16;
  /* #45: @3 = (@3*@13) */
  w3 *= w13;
  /* #46: @7 = (@7*@11) */
  w7 *= w11;
  /* #47: @3 = (@3+@7) */
  w3 += w7;
  /* #48: @10 = (@10*@8) */
  w10 *= w8;
  /* #49: @3 = (@3-@10) */
  w3 -= w10;
  /* #50: @12 = (@12*@5) */
  w12 *= w5;
  /* #51: @3 = (@3+@12) */
  w3 += w12;
  /* #52: @9 = vertcat(@6, @14, @15, @3) */
  rr=w9;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w3;
  /* #53: @6 = sign(@6) */
  w6 = casadi_sign( w6 );
  /* #54: @9 = (@9*@6) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) *= w6;
  /* #55: output[0][1] = @9 */
  if (res[0]) casadi_copy(w9, 4, res[0]+3);
  /* #56: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #57: @2 = @1[7:10] */
  for (rr=w2, ss=w1+7; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #58: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #59: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #60: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #61: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #62: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #63: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+10);
  /* #64: @17 = input[1][0] */
  casadi_copy(arg[1], 6, w17);
  /* #65: @18 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+13 : 0, 6, w18);
  /* #66: @17 = (@17-@18) */
  for (i=0, rr=w17, cs=w18; i<6; ++i) (*rr++) -= (*cs++);
  /* #67: output[0][4] = @17 */
  if (res[0]) casadi_copy(w17, 6, res[0]+13);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 51;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 51*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
