/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s4[38] = {19, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 8, 12, 16, 16, 16, 16, 16, 16, 16, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12};
static const casadi_int casadi_s5[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s9[3] = {0, 0, 0};
static const casadi_int casadi_s10[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* bluerov_cost_y_hess:(i0[13],i1[6],i2[0],i3[19],i4[],i5[25])->(o0[19x19,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+20, w3, w4, w6, *w7=w+39, w8, w9, w10, *w11=w+46, *w12=w+50, *w13=w+54, *w14=w+58, *w15=w+62, w16, w17, w18, *w19=w+78, w20, w21, w22, *w23=w+100;
  /* #0: @0 = zeros(19x19,16nz) */
  casadi_clear(w0, 16);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = ones(19x1,16nz) */
  casadi_fill(w2, 16, 1.);
  /* #3: {NULL, NULL, @3, NULL, NULL} = vertsplit(@2) */
  w3 = w2[9];
  /* #4: @4 = @3[0] */
  for (rr=(&w4), ss=(&w3)+0; ss!=(&w3)+1; ss+=1) *rr++ = *ss;
  /* #5: @5 = 00 */
  /* #6: @6 = vertcat(@4, @5, @5, @5) */
  rr=(&w6);
  *rr++ = w4;
  /* #7: @4 = ||@1||_F */
  w4 = sqrt(casadi_dot(4, w1, w1));
  /* #8: @6 = (@6/@4) */
  w6 /= w4;
  /* #9: @7 = dense(@6) */
  casadi_densify((&w6), casadi_s0, w7, 0);
  /* #10: @6 = @1[0] */
  for (rr=(&w6), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #11: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #12: @8 = (-@8) */
  w8 = (- w8 );
  /* #13: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #14: @9 = (-@9) */
  w9 = (- w9 );
  /* #15: @10 = @1[3] */
  for (rr=(&w10), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #16: @10 = (-@10) */
  w10 = (- w10 );
  /* #17: @11 = vertcat(@6, @8, @9, @10) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #18: @11 = (@11/@4) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w4;
  /* #19: @12 = (@11/@4) */
  for (i=0, rr=w12, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #20: @6 = project(@1) */
  casadi_sparsify(w1, (&w6), casadi_s0, 0);
  /* #21: @8 = dot(@6, @3) */
  w8 = casadi_dot(1, (&w6), (&w3));
  /* #22: @8 = (@8/@4) */
  w8 /= w4;
  /* #23: @13 = (@12*@8) */
  for (i=0, rr=w13, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #24: @7 = (@7-@13) */
  for (i=0, rr=w7, cs=w13; i<4; ++i) (*rr++) -= (*cs++);
  /* #25: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #26: @13 = (@12/@4) */
  for (i=0, rr=w13, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #27: @14 = (@13*@8) */
  for (i=0, rr=w14, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #28: @7 = (@7-@14) */
  for (i=0, rr=w7, cs=w14; i<4; ++i) (*rr++) -= (*cs++);
  /* #29: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #30: @14 = zeros(4x1) */
  casadi_clear(w14, 4);
  /* #31: @15 = input[5][0] */
  casadi_copy(arg[5], 13, w15);
  /* #32: @6 = @15[6] */
  for (rr=(&w6), ss=w15+6; ss!=w15+7; ss+=1) *rr++ = *ss;
  /* #33: @9 = @15[3] */
  for (rr=(&w9), ss=w15+3; ss!=w15+4; ss+=1) *rr++ = *ss;
  /* #34: @10 = @11[0] */
  for (rr=(&w10), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #35: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #36: @16 = @15[4] */
  for (rr=(&w16), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #37: @17 = @11[1] */
  for (rr=(&w17), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #38: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #39: @10 = (@10-@17) */
  w10 -= w17;
  /* #40: @17 = @15[5] */
  for (rr=(&w17), ss=w15+5; ss!=w15+6; ss+=1) *rr++ = *ss;
  /* #41: @18 = @11[2] */
  for (rr=(&w18), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #42: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #43: @10 = (@10-@18) */
  w10 -= w18;
  /* #44: @18 = @11[3] */
  for (rr=(&w18), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #45: @18 = (@6*@18) */
  w18  = (w6*w18);
  /* #46: @10 = (@10-@18) */
  w10 -= w18;
  /* #47: @10 = sign(@10) */
  w10 = casadi_sign( w10 );
  /* #48: @19 = input[3][0] */
  casadi_copy(arg[3], 19, w19);
  /* #49: {NULL, @11, NULL, NULL, NULL} = vertsplit(@19) */
  casadi_copy(w19+3, 4, w11);
  /* #50: @11 = (@10*@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #51: {@10, @18, @20, @21} = vertsplit(@11) */
  w10 = w11[0];
  w18 = w11[1];
  w20 = w11[2];
  w21 = w11[3];
  /* #52: @22 = (@6*@21) */
  w22  = (w6*w21);
  /* #53: (@14[0] += @22) */
  for (rr=w14+0, ss=(&w22); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #54: @22 = (@17*@21) */
  w22  = (w17*w21);
  /* #55: @22 = (-@22) */
  w22 = (- w22 );
  /* #56: (@14[1] += @22) */
  for (rr=w14+1, ss=(&w22); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #57: @22 = (@16*@21) */
  w22  = (w16*w21);
  /* #58: (@14[2] += @22) */
  for (rr=w14+2, ss=(&w22); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #59: @21 = (@9*@21) */
  w21  = (w9*w21);
  /* #60: (@14[3] += @21) */
  for (rr=w14+3, ss=(&w21); rr!=w14+4; rr+=1) *rr += *ss++;
  /* #61: @21 = (@6*@20) */
  w21  = (w6*w20);
  /* #62: (@14[1] += @21) */
  for (rr=w14+1, ss=(&w21); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #63: @21 = (@17*@20) */
  w21  = (w17*w20);
  /* #64: (@14[0] += @21) */
  for (rr=w14+0, ss=(&w21); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #65: @21 = (@16*@20) */
  w21  = (w16*w20);
  /* #66: @21 = (-@21) */
  w21 = (- w21 );
  /* #67: (@14[3] += @21) */
  for (rr=w14+3, ss=(&w21); rr!=w14+4; rr+=1) *rr += *ss++;
  /* #68: @20 = (@9*@20) */
  w20  = (w9*w20);
  /* #69: (@14[2] += @20) */
  for (rr=w14+2, ss=(&w20); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #70: @20 = (@6*@18) */
  w20  = (w6*w18);
  /* #71: @20 = (-@20) */
  w20 = (- w20 );
  /* #72: (@14[2] += @20) */
  for (rr=w14+2, ss=(&w20); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #73: @20 = (@17*@18) */
  w20  = (w17*w18);
  /* #74: (@14[3] += @20) */
  for (rr=w14+3, ss=(&w20); rr!=w14+4; rr+=1) *rr += *ss++;
  /* #75: @20 = (@16*@18) */
  w20  = (w16*w18);
  /* #76: (@14[0] += @20) */
  for (rr=w14+0, ss=(&w20); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #77: @18 = (@9*@18) */
  w18  = (w9*w18);
  /* #78: (@14[1] += @18) */
  for (rr=w14+1, ss=(&w18); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #79: @6 = (@6*@10) */
  w6 *= w10;
  /* #80: @6 = (-@6) */
  w6 = (- w6 );
  /* #81: (@14[3] += @6) */
  for (rr=w14+3, ss=(&w6); rr!=w14+4; rr+=1) *rr += *ss++;
  /* #82: @17 = (@17*@10) */
  w17 *= w10;
  /* #83: @17 = (-@17) */
  w17 = (- w17 );
  /* #84: (@14[2] += @17) */
  for (rr=w14+2, ss=(&w17); rr!=w14+3; rr+=1) *rr += *ss++;
  /* #85: @16 = (@16*@10) */
  w16 *= w10;
  /* #86: @16 = (-@16) */
  w16 = (- w16 );
  /* #87: (@14[1] += @16) */
  for (rr=w14+1, ss=(&w16); rr!=w14+2; rr+=1) *rr += *ss++;
  /* #88: @9 = (@9*@10) */
  w9 *= w10;
  /* #89: (@14[0] += @9) */
  for (rr=w14+0, ss=(&w9); rr!=w14+1; rr+=1) *rr += *ss++;
  /* #90: @9 = dot(@7, @14) */
  w9 = casadi_dot(4, w7, w14);
  /* #91: @9 = (@9/@4) */
  w9 /= w4;
  /* #92: @7 = (-@12) */
  for (i=0, rr=w7, cs=w12; i<4; ++i) *rr++ = (- *cs++ );
  /* #93: @10 = dot(@7, @14) */
  w10 = casadi_dot(4, w7, w14);
  /* #94: @10 = (@10/@4) */
  w10 /= w4;
  /* #95: @16 = (@10/@4) */
  w16  = (w10/w4);
  /* #96: @17 = (@16*@8) */
  w17  = (w16*w8);
  /* #97: @9 = (@9-@17) */
  w9 -= w17;
  /* #98: @7 = (@1*@9) */
  for (i=0, rr=w7, cr=w1; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #99: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #100: @11 = dense(@3) */
  casadi_densify((&w3), casadi_s0, w11, 0);
  /* #101: @7 = (@7+@11) */
  for (i=0, rr=w7, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #102: @11 = (@14/@4) */
  for (i=0, rr=w11, cr=w14; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #103: @11 = (@11/@4) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w4;
  /* #104: @23 = (@11*@8) */
  for (i=0, rr=w23, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #105: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #106: {@8, @3, @9, @17} = vertsplit(@23) */
  w8 = w23[0];
  w3 = w23[1];
  w9 = w23[2];
  w17 = w23[3];
  /* #107: @17 = (-@17) */
  w17 = (- w17 );
  /* #108: (@7[3] += @17) */
  for (rr=w7+3, ss=(&w17); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #109: @9 = (-@9) */
  w9 = (- w9 );
  /* #110: (@7[2] += @9) */
  for (rr=w7+2, ss=(&w9); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #111: @3 = (-@3) */
  w3 = (- w3 );
  /* #112: (@7[1] += @3) */
  for (rr=w7+1, ss=(&w3); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #113: (@7[0] += @8) */
  for (rr=w7+0, ss=(&w8); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #114: (@0[:16:4] = @7) */
  for (rr=w0+0, ss=w7; rr!=w0+16; rr+=4) *rr = *ss++;
  /* #115: @8 = ones(19x1,1nz) */
  w8 = 1.;
  /* #116: {NULL, NULL, @3, NULL, NULL} = vertsplit(@8) */
  w3 = w8;
  /* #117: @8 = @3[0] */
  for (rr=(&w8), ss=(&w3)+0; ss!=(&w3)+1; ss+=1) *rr++ = *ss;
  /* #118: @8 = (-@8) */
  w8 = (- w8 );
  /* #119: @9 = vertcat(@5, @8, @5, @5) */
  rr=(&w9);
  *rr++ = w8;
  /* #120: @9 = (@9/@4) */
  w9 /= w4;
  /* #121: @7 = dense(@9) */
  casadi_densify((&w9), casadi_s1, w7, 0);
  /* #122: @9 = project(@1) */
  casadi_sparsify(w1, (&w9), casadi_s1, 0);
  /* #123: @8 = dot(@9, @3) */
  w8 = casadi_dot(1, (&w9), (&w3));
  /* #124: @8 = (@8/@4) */
  w8 /= w4;
  /* #125: @23 = (@12*@8) */
  for (i=0, rr=w23, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #126: @7 = (@7-@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #127: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #128: @23 = (@13*@8) */
  for (i=0, rr=w23, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #129: @7 = (@7-@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #130: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #131: @9 = dot(@7, @14) */
  w9 = casadi_dot(4, w7, w14);
  /* #132: @9 = (@9/@4) */
  w9 /= w4;
  /* #133: @17 = (@16*@8) */
  w17  = (w16*w8);
  /* #134: @9 = (@9-@17) */
  w9 -= w17;
  /* #135: @7 = (@1*@9) */
  for (i=0, rr=w7, cr=w1; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #136: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #137: @23 = dense(@3) */
  casadi_densify((&w3), casadi_s1, w23, 0);
  /* #138: @7 = (@7+@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #139: @23 = (@11*@8) */
  for (i=0, rr=w23, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #140: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #141: {@8, @3, @9, @17} = vertsplit(@23) */
  w8 = w23[0];
  w3 = w23[1];
  w9 = w23[2];
  w17 = w23[3];
  /* #142: @17 = (-@17) */
  w17 = (- w17 );
  /* #143: (@7[3] += @17) */
  for (rr=w7+3, ss=(&w17); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #144: @9 = (-@9) */
  w9 = (- w9 );
  /* #145: (@7[2] += @9) */
  for (rr=w7+2, ss=(&w9); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #146: @3 = (-@3) */
  w3 = (- w3 );
  /* #147: (@7[1] += @3) */
  for (rr=w7+1, ss=(&w3); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #148: (@7[0] += @8) */
  for (rr=w7+0, ss=(&w8); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #149: (@0[1:17:4] = @7) */
  for (rr=w0+1, ss=w7; rr!=w0+17; rr+=4) *rr = *ss++;
  /* #150: @8 = ones(19x1,1nz) */
  w8 = 1.;
  /* #151: {NULL, NULL, @3, NULL, NULL} = vertsplit(@8) */
  w3 = w8;
  /* #152: @8 = @3[0] */
  for (rr=(&w8), ss=(&w3)+0; ss!=(&w3)+1; ss+=1) *rr++ = *ss;
  /* #153: @8 = (-@8) */
  w8 = (- w8 );
  /* #154: @9 = vertcat(@5, @5, @8, @5) */
  rr=(&w9);
  *rr++ = w8;
  /* #155: @9 = (@9/@4) */
  w9 /= w4;
  /* #156: @7 = dense(@9) */
  casadi_densify((&w9), casadi_s2, w7, 0);
  /* #157: @9 = project(@1) */
  casadi_sparsify(w1, (&w9), casadi_s2, 0);
  /* #158: @8 = dot(@9, @3) */
  w8 = casadi_dot(1, (&w9), (&w3));
  /* #159: @8 = (@8/@4) */
  w8 /= w4;
  /* #160: @23 = (@12*@8) */
  for (i=0, rr=w23, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #161: @7 = (@7-@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #162: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #163: @23 = (@13*@8) */
  for (i=0, rr=w23, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #164: @7 = (@7-@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #165: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #166: @9 = dot(@7, @14) */
  w9 = casadi_dot(4, w7, w14);
  /* #167: @9 = (@9/@4) */
  w9 /= w4;
  /* #168: @17 = (@16*@8) */
  w17  = (w16*w8);
  /* #169: @9 = (@9-@17) */
  w9 -= w17;
  /* #170: @7 = (@1*@9) */
  for (i=0, rr=w7, cr=w1; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #171: @3 = (@10*@3) */
  w3  = (w10*w3);
  /* #172: @23 = dense(@3) */
  casadi_densify((&w3), casadi_s2, w23, 0);
  /* #173: @7 = (@7+@23) */
  for (i=0, rr=w7, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #174: @23 = (@11*@8) */
  for (i=0, rr=w23, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #175: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #176: {@8, @3, @9, @17} = vertsplit(@23) */
  w8 = w23[0];
  w3 = w23[1];
  w9 = w23[2];
  w17 = w23[3];
  /* #177: @17 = (-@17) */
  w17 = (- w17 );
  /* #178: (@7[3] += @17) */
  for (rr=w7+3, ss=(&w17); rr!=w7+4; rr+=1) *rr += *ss++;
  /* #179: @9 = (-@9) */
  w9 = (- w9 );
  /* #180: (@7[2] += @9) */
  for (rr=w7+2, ss=(&w9); rr!=w7+3; rr+=1) *rr += *ss++;
  /* #181: @3 = (-@3) */
  w3 = (- w3 );
  /* #182: (@7[1] += @3) */
  for (rr=w7+1, ss=(&w3); rr!=w7+2; rr+=1) *rr += *ss++;
  /* #183: (@7[0] += @8) */
  for (rr=w7+0, ss=(&w8); rr!=w7+1; rr+=1) *rr += *ss++;
  /* #184: (@0[2:18:4] = @7) */
  for (rr=w0+2, ss=w7; rr!=w0+18; rr+=4) *rr = *ss++;
  /* #185: @8 = ones(19x1,1nz) */
  w8 = 1.;
  /* #186: {NULL, NULL, @3, NULL, NULL} = vertsplit(@8) */
  w3 = w8;
  /* #187: @8 = @3[0] */
  for (rr=(&w8), ss=(&w3)+0; ss!=(&w3)+1; ss+=1) *rr++ = *ss;
  /* #188: @8 = (-@8) */
  w8 = (- w8 );
  /* #189: @9 = vertcat(@5, @5, @5, @8) */
  rr=(&w9);
  *rr++ = w8;
  /* #190: @9 = (@9/@4) */
  w9 /= w4;
  /* #191: @7 = dense(@9) */
  casadi_densify((&w9), casadi_s3, w7, 0);
  /* #192: @9 = project(@1) */
  casadi_sparsify(w1, (&w9), casadi_s3, 0);
  /* #193: @8 = dot(@9, @3) */
  w8 = casadi_dot(1, (&w9), (&w3));
  /* #194: @8 = (@8/@4) */
  w8 /= w4;
  /* #195: @12 = (@12*@8) */
  for (i=0, rr=w12; i<4; ++i) (*rr++) *= w8;
  /* #196: @7 = (@7-@12) */
  for (i=0, rr=w7, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #197: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #198: @13 = (@13*@8) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) *= w8;
  /* #199: @7 = (@7-@13) */
  for (i=0, rr=w7, cs=w13; i<4; ++i) (*rr++) -= (*cs++);
  /* #200: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #201: @9 = dot(@7, @14) */
  w9 = casadi_dot(4, w7, w14);
  /* #202: @9 = (@9/@4) */
  w9 /= w4;
  /* #203: @16 = (@16*@8) */
  w16 *= w8;
  /* #204: @9 = (@9-@16) */
  w9 -= w16;
  /* #205: @1 = (@1*@9) */
  for (i=0, rr=w1; i<4; ++i) (*rr++) *= w9;
  /* #206: @10 = (@10*@3) */
  w10 *= w3;
  /* #207: @7 = dense(@10) */
  casadi_densify((&w10), casadi_s3, w7, 0);
  /* #208: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #209: @11 = (@11*@8) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) *= w8;
  /* #210: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #211: {@8, @10, @3, @9} = vertsplit(@11) */
  w8 = w11[0];
  w10 = w11[1];
  w3 = w11[2];
  w9 = w11[3];
  /* #212: @9 = (-@9) */
  w9 = (- w9 );
  /* #213: (@1[3] += @9) */
  for (rr=w1+3, ss=(&w9); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #214: @3 = (-@3) */
  w3 = (- w3 );
  /* #215: (@1[2] += @3) */
  for (rr=w1+2, ss=(&w3); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #216: @10 = (-@10) */
  w10 = (- w10 );
  /* #217: (@1[1] += @10) */
  for (rr=w1+1, ss=(&w10); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #218: (@1[0] += @8) */
  for (rr=w1+0, ss=(&w8); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #219: (@0[3:19:4] = @1) */
  for (rr=w0+3, ss=w1; rr!=w0+19; rr+=4) *rr = *ss++;
  /* #220: @2 = @0' */
  casadi_trans(w0,casadi_s4, w2, casadi_s4, iw);
  /* #221: output[0][0] = @2 */
  casadi_copy(w2, 16, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    case 5: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 20;
  if (sz_w) *sz_w = 104;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 20*sizeof(casadi_int);
  if (sz_w) *sz_w = 104*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
