/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sparsify CASADI_PREFIX(sparsify)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[19] = {0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s5[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s10[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s11[53] = {19, 19, 0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 6, 7, 8, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s12[3] = {19, 0, 0};

/* bluerov_cost_y_0_fun_jac_ut_xt:(i0[13],i1[6],i2[0],i3[],i4[25])->(o0[19],o1[19x19,31nz],o2[19x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+3, *w2=w+16, *w3=w+19, w4, *w5=w+24, w6, *w7=w+29, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+44, *w20=w+50, *w21=w+56, *w22=w+87, *w23=w+103, *w24=w+106, w25, *w26=w+111;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = input[4][0] */
  casadi_copy(arg[4], 13, w1);
  /* #2: @2 = @1[:3] */
  for (rr=w2, ss=w1+0; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #4: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #5: @3 = @1[3:7] */
  for (rr=w3, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #6: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #7: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #8: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #9: @5 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w5);
  /* #10: @6 = ||@5||_F */
  w6 = sqrt(casadi_dot(4, w5, w5));
  /* #11: @7 = (@5/@6) */
  for (i=0, rr=w7, cr=w5; i<4; ++i) (*rr++)  = ((*cr++)/w6);
  /* #12: @8 = @7[0] */
  for (rr=(&w8), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #13: @9 = (@4*@8) */
  w9  = (w4*w8);
  /* #14: @10 = @3[1] */
  for (rr=(&w10), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #15: @11 = @7[1] */
  for (rr=(&w11), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #16: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #17: @9 = (@9+@12) */
  w9 += w12;
  /* #18: @12 = @3[2] */
  for (rr=(&w12), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #19: @13 = @7[2] */
  for (rr=(&w13), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #20: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #21: @9 = (@9+@14) */
  w9 += w14;
  /* #22: @14 = @3[3] */
  for (rr=(&w14), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #23: @15 = @7[3] */
  for (rr=(&w15), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #24: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #25: @9 = (@9+@16) */
  w9 += w16;
  /* #26: @16 = (@10*@8) */
  w16  = (w10*w8);
  /* #27: @17 = (@4*@11) */
  w17  = (w4*w11);
  /* #28: @16 = (@16-@17) */
  w16 -= w17;
  /* #29: @17 = (@12*@15) */
  w17  = (w12*w15);
  /* #30: @16 = (@16-@17) */
  w16 -= w17;
  /* #31: @17 = (@14*@13) */
  w17  = (w14*w13);
  /* #32: @16 = (@16+@17) */
  w16 += w17;
  /* #33: @17 = (@10*@15) */
  w17  = (w10*w15);
  /* #34: @18 = (@4*@13) */
  w18  = (w4*w13);
  /* #35: @17 = (@17-@18) */
  w17 -= w18;
  /* #36: @18 = (@12*@8) */
  w18  = (w12*w8);
  /* #37: @17 = (@17+@18) */
  w17 += w18;
  /* #38: @18 = (@14*@11) */
  w18  = (w14*w11);
  /* #39: @17 = (@17-@18) */
  w17 -= w18;
  /* #40: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #43: @13 = (@13-@15) */
  w13 -= w15;
  /* #44: @11 = (@12*@11) */
  w11  = (w12*w11);
  /* #45: @13 = (@13+@11) */
  w13 += w11;
  /* #46: @8 = (@14*@8) */
  w8  = (w14*w8);
  /* #47: @13 = (@13+@8) */
  w13 += w8;
  /* #48: @3 = vertcat(@9, @16, @17, @13) */
  rr=w3;
  *rr++ = w9;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w13;
  /* #49: @9 = sign(@9) */
  w9 = casadi_sign( w9 );
  /* #50: @3 = (@3*@9) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) *= w9;
  /* #51: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+3);
  /* #52: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #53: @2 = @1[7:10] */
  for (rr=w2, ss=w1+7; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #54: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #55: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #56: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #57: @2 = @1[10:13] */
  for (rr=w2, ss=w1+10; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #58: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #59: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+10);
  /* #60: @19 = input[1][0] */
  casadi_copy(arg[1], 6, w19);
  /* #61: @20 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+13 : 0, 6, w20);
  /* #62: @19 = (@19-@20) */
  for (i=0, rr=w19, cs=w20; i<6; ++i) (*rr++) -= (*cs++);
  /* #63: output[0][4] = @19 */
  if (res[0]) casadi_copy(w19, 6, res[0]+13);
  /* #64: @21 = zeros(19x19,31nz) */
  casadi_clear(w21, 31);
  /* #65: @22 = ones(19x1,16nz) */
  casadi_fill(w22, 16, 1.);
  /* #66: {@19, @0, @16, @2, @23} = vertsplit(@22) */
  casadi_copy(w22, 6, w19);
  casadi_copy(w22+6, 3, w0);
  w16 = w22[9];
  casadi_copy(w22+10, 3, w2);
  casadi_copy(w22+13, 3, w23);
  /* #67: @17 = (@16/@6) */
  w17  = (w16/w6);
  /* #68: @3 = dense(@17) */
  casadi_densify((&w17), casadi_s0, w3, 0);
  /* #69: @7 = (@7/@6) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w6;
  /* #70: @17 = project(@5) */
  casadi_sparsify(w5, (&w17), casadi_s0, 0);
  /* #71: @13 = dot(@17, @16) */
  w13 = casadi_dot(1, (&w17), (&w16));
  /* #72: @13 = (@13/@6) */
  w13 /= w6;
  /* #73: @24 = (@7*@13) */
  for (i=0, rr=w24, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w13);
  /* #74: @3 = (@3-@24) */
  for (i=0, rr=w3, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #75: @13 = @3[0] */
  for (rr=(&w13), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #76: @17 = (@4*@13) */
  w17  = (w4*w13);
  /* #77: @16 = @3[1] */
  for (rr=(&w16), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #78: @8 = (@10*@16) */
  w8  = (w10*w16);
  /* #79: @17 = (@17+@8) */
  w17 += w8;
  /* #80: @8 = @3[2] */
  for (rr=(&w8), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #81: @11 = (@12*@8) */
  w11  = (w12*w8);
  /* #82: @17 = (@17+@11) */
  w17 += w11;
  /* #83: @11 = @3[3] */
  for (rr=(&w11), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #84: @15 = (@14*@11) */
  w15  = (w14*w11);
  /* #85: @17 = (@17+@15) */
  w17 += w15;
  /* #86: @15 = (@10*@13) */
  w15  = (w10*w13);
  /* #87: @18 = (@4*@16) */
  w18  = (w4*w16);
  /* #88: @15 = (@15-@18) */
  w15 -= w18;
  /* #89: @18 = (@12*@11) */
  w18  = (w12*w11);
  /* #90: @15 = (@15-@18) */
  w15 -= w18;
  /* #91: @18 = (@14*@8) */
  w18  = (w14*w8);
  /* #92: @15 = (@15+@18) */
  w15 += w18;
  /* #93: @18 = (@10*@11) */
  w18  = (w10*w11);
  /* #94: @25 = (@4*@8) */
  w25  = (w4*w8);
  /* #95: @18 = (@18-@25) */
  w18 -= w25;
  /* #96: @25 = (@12*@13) */
  w25  = (w12*w13);
  /* #97: @18 = (@18+@25) */
  w18 += w25;
  /* #98: @25 = (@14*@16) */
  w25  = (w14*w16);
  /* #99: @18 = (@18-@25) */
  w18 -= w25;
  /* #100: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #101: @11 = (-@11) */
  w11 = (- w11 );
  /* #102: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #103: @11 = (@11-@8) */
  w11 -= w8;
  /* #104: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #105: @11 = (@11+@16) */
  w11 += w16;
  /* #106: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #107: @11 = (@11+@13) */
  w11 += w13;
  /* #108: @3 = vertcat(@17, @15, @18, @11) */
  rr=w3;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w18;
  *rr++ = w11;
  /* #109: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #110: @26 = vertcat(@0, @3, @2, @23, @19) */
  rr=w26;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<6; ++i) *rr++ = *cs++;
  /* #111: (@21[0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] = @26) */
  for (cii=casadi_s1, rr=w21, ss=w26; cii!=casadi_s1+19; ++cii, ++ss) rr[*cii] = *ss;
  /* #112: @17 = ones(19x1,1nz) */
  w17 = 1.;
  /* #113: {NULL, NULL, @15, NULL, NULL} = vertsplit(@17) */
  w15 = w17;
  /* #114: @17 = (@15/@6) */
  w17  = (w15/w6);
  /* #115: @3 = dense(@17) */
  casadi_densify((&w17), casadi_s2, w3, 0);
  /* #116: @17 = project(@5) */
  casadi_sparsify(w5, (&w17), casadi_s2, 0);
  /* #117: @18 = dot(@17, @15) */
  w18 = casadi_dot(1, (&w17), (&w15));
  /* #118: @18 = (@18/@6) */
  w18 /= w6;
  /* #119: @24 = (@7*@18) */
  for (i=0, rr=w24, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #120: @3 = (@3-@24) */
  for (i=0, rr=w3, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #121: @18 = @3[0] */
  for (rr=(&w18), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #122: @17 = (@4*@18) */
  w17  = (w4*w18);
  /* #123: @15 = @3[1] */
  for (rr=(&w15), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #124: @11 = (@10*@15) */
  w11  = (w10*w15);
  /* #125: @17 = (@17+@11) */
  w17 += w11;
  /* #126: @11 = @3[2] */
  for (rr=(&w11), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #127: @13 = (@12*@11) */
  w13  = (w12*w11);
  /* #128: @17 = (@17+@13) */
  w17 += w13;
  /* #129: @13 = @3[3] */
  for (rr=(&w13), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #130: @16 = (@14*@13) */
  w16  = (w14*w13);
  /* #131: @17 = (@17+@16) */
  w17 += w16;
  /* #132: @16 = (@10*@18) */
  w16  = (w10*w18);
  /* #133: @8 = (@4*@15) */
  w8  = (w4*w15);
  /* #134: @16 = (@16-@8) */
  w16 -= w8;
  /* #135: @8 = (@12*@13) */
  w8  = (w12*w13);
  /* #136: @16 = (@16-@8) */
  w16 -= w8;
  /* #137: @8 = (@14*@11) */
  w8  = (w14*w11);
  /* #138: @16 = (@16+@8) */
  w16 += w8;
  /* #139: @8 = (@10*@13) */
  w8  = (w10*w13);
  /* #140: @25 = (@4*@11) */
  w25  = (w4*w11);
  /* #141: @8 = (@8-@25) */
  w8 -= w25;
  /* #142: @25 = (@12*@18) */
  w25  = (w12*w18);
  /* #143: @8 = (@8+@25) */
  w8 += w25;
  /* #144: @25 = (@14*@15) */
  w25  = (w14*w15);
  /* #145: @8 = (@8-@25) */
  w8 -= w25;
  /* #146: @13 = (@4*@13) */
  w13  = (w4*w13);
  /* #147: @13 = (-@13) */
  w13 = (- w13 );
  /* #148: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #149: @13 = (@13-@11) */
  w13 -= w11;
  /* #150: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #151: @13 = (@13+@15) */
  w13 += w15;
  /* #152: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #153: @13 = (@13+@18) */
  w13 += w18;
  /* #154: @3 = vertcat(@17, @16, @8, @13) */
  rr=w3;
  *rr++ = w17;
  *rr++ = w16;
  *rr++ = w8;
  *rr++ = w13;
  /* #155: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #156: (@21[4:20:4] = @3) */
  for (rr=w21+4, ss=w3; rr!=w21+20; rr+=4) *rr = *ss++;
  /* #157: @17 = ones(19x1,1nz) */
  w17 = 1.;
  /* #158: {NULL, NULL, @16, NULL, NULL} = vertsplit(@17) */
  w16 = w17;
  /* #159: @17 = (@16/@6) */
  w17  = (w16/w6);
  /* #160: @3 = dense(@17) */
  casadi_densify((&w17), casadi_s3, w3, 0);
  /* #161: @17 = project(@5) */
  casadi_sparsify(w5, (&w17), casadi_s3, 0);
  /* #162: @8 = dot(@17, @16) */
  w8 = casadi_dot(1, (&w17), (&w16));
  /* #163: @8 = (@8/@6) */
  w8 /= w6;
  /* #164: @24 = (@7*@8) */
  for (i=0, rr=w24, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w8);
  /* #165: @3 = (@3-@24) */
  for (i=0, rr=w3, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #166: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #167: @17 = (@4*@8) */
  w17  = (w4*w8);
  /* #168: @16 = @3[1] */
  for (rr=(&w16), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #169: @13 = (@10*@16) */
  w13  = (w10*w16);
  /* #170: @17 = (@17+@13) */
  w17 += w13;
  /* #171: @13 = @3[2] */
  for (rr=(&w13), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #172: @18 = (@12*@13) */
  w18  = (w12*w13);
  /* #173: @17 = (@17+@18) */
  w17 += w18;
  /* #174: @18 = @3[3] */
  for (rr=(&w18), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #175: @15 = (@14*@18) */
  w15  = (w14*w18);
  /* #176: @17 = (@17+@15) */
  w17 += w15;
  /* #177: @15 = (@10*@8) */
  w15  = (w10*w8);
  /* #178: @11 = (@4*@16) */
  w11  = (w4*w16);
  /* #179: @15 = (@15-@11) */
  w15 -= w11;
  /* #180: @11 = (@12*@18) */
  w11  = (w12*w18);
  /* #181: @15 = (@15-@11) */
  w15 -= w11;
  /* #182: @11 = (@14*@13) */
  w11  = (w14*w13);
  /* #183: @15 = (@15+@11) */
  w15 += w11;
  /* #184: @11 = (@10*@18) */
  w11  = (w10*w18);
  /* #185: @25 = (@4*@13) */
  w25  = (w4*w13);
  /* #186: @11 = (@11-@25) */
  w11 -= w25;
  /* #187: @25 = (@12*@8) */
  w25  = (w12*w8);
  /* #188: @11 = (@11+@25) */
  w11 += w25;
  /* #189: @25 = (@14*@16) */
  w25  = (w14*w16);
  /* #190: @11 = (@11-@25) */
  w11 -= w25;
  /* #191: @18 = (@4*@18) */
  w18  = (w4*w18);
  /* #192: @18 = (-@18) */
  w18 = (- w18 );
  /* #193: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #194: @18 = (@18-@13) */
  w18 -= w13;
  /* #195: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #196: @18 = (@18+@16) */
  w18 += w16;
  /* #197: @8 = (@14*@8) */
  w8  = (w14*w8);
  /* #198: @18 = (@18+@8) */
  w18 += w8;
  /* #199: @3 = vertcat(@17, @15, @11, @18) */
  rr=w3;
  *rr++ = w17;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w18;
  /* #200: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #201: (@21[5:21:4] = @3) */
  for (rr=w21+5, ss=w3; rr!=w21+21; rr+=4) *rr = *ss++;
  /* #202: @17 = ones(19x1,1nz) */
  w17 = 1.;
  /* #203: {NULL, NULL, @15, NULL, NULL} = vertsplit(@17) */
  w15 = w17;
  /* #204: @17 = (@15/@6) */
  w17  = (w15/w6);
  /* #205: @3 = dense(@17) */
  casadi_densify((&w17), casadi_s4, w3, 0);
  /* #206: @17 = project(@5) */
  casadi_sparsify(w5, (&w17), casadi_s4, 0);
  /* #207: @11 = dot(@17, @15) */
  w11 = casadi_dot(1, (&w17), (&w15));
  /* #208: @11 = (@11/@6) */
  w11 /= w6;
  /* #209: @7 = (@7*@11) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) *= w11;
  /* #210: @3 = (@3-@7) */
  for (i=0, rr=w3, cs=w7; i<4; ++i) (*rr++) -= (*cs++);
  /* #211: @11 = @3[0] */
  for (rr=(&w11), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #212: @6 = (@4*@11) */
  w6  = (w4*w11);
  /* #213: @17 = @3[1] */
  for (rr=(&w17), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #214: @15 = (@10*@17) */
  w15  = (w10*w17);
  /* #215: @6 = (@6+@15) */
  w6 += w15;
  /* #216: @15 = @3[2] */
  for (rr=(&w15), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #217: @18 = (@12*@15) */
  w18  = (w12*w15);
  /* #218: @6 = (@6+@18) */
  w6 += w18;
  /* #219: @18 = @3[3] */
  for (rr=(&w18), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #220: @8 = (@14*@18) */
  w8  = (w14*w18);
  /* #221: @6 = (@6+@8) */
  w6 += w8;
  /* #222: @8 = (@10*@11) */
  w8  = (w10*w11);
  /* #223: @16 = (@4*@17) */
  w16  = (w4*w17);
  /* #224: @8 = (@8-@16) */
  w8 -= w16;
  /* #225: @16 = (@12*@18) */
  w16  = (w12*w18);
  /* #226: @8 = (@8-@16) */
  w8 -= w16;
  /* #227: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #228: @8 = (@8+@16) */
  w8 += w16;
  /* #229: @16 = (@10*@18) */
  w16  = (w10*w18);
  /* #230: @13 = (@4*@15) */
  w13  = (w4*w15);
  /* #231: @16 = (@16-@13) */
  w16 -= w13;
  /* #232: @13 = (@12*@11) */
  w13  = (w12*w11);
  /* #233: @16 = (@16+@13) */
  w16 += w13;
  /* #234: @13 = (@14*@17) */
  w13  = (w14*w17);
  /* #235: @16 = (@16-@13) */
  w16 -= w13;
  /* #236: @4 = (@4*@18) */
  w4 *= w18;
  /* #237: @4 = (-@4) */
  w4 = (- w4 );
  /* #238: @10 = (@10*@15) */
  w10 *= w15;
  /* #239: @4 = (@4-@10) */
  w4 -= w10;
  /* #240: @12 = (@12*@17) */
  w12 *= w17;
  /* #241: @4 = (@4+@12) */
  w4 += w12;
  /* #242: @14 = (@14*@11) */
  w14 *= w11;
  /* #243: @4 = (@4+@14) */
  w4 += w14;
  /* #244: @3 = vertcat(@6, @8, @16, @4) */
  rr=w3;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w16;
  *rr++ = w4;
  /* #245: @3 = (@9*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #246: (@21[6:22:4] = @3) */
  for (rr=w21+6, ss=w3; rr!=w21+22; rr+=4) *rr = *ss++;
  /* #247: output[1][0] = @21 */
  casadi_copy(w21, 31, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 130;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 130*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
